package es.caib.comanda.usuaris.logic.service;

import com.turkraft.springfilter.FilterBuilder;
import com.turkraft.springfilter.parser.Filter;
import es.caib.comanda.base.config.BaseConfig;
import es.caib.comanda.ms.logic.helper.AuthenticationHelper;
import es.caib.comanda.ms.logic.helper.ParametresHelper;
import es.caib.comanda.ms.logic.intf.exception.AnswerRequiredException;
import es.caib.comanda.ms.logic.intf.exception.PerspectiveApplicationException;
import es.caib.comanda.ms.logic.intf.exception.ResourceNotFoundException;
import es.caib.comanda.ms.logic.service.BaseMutableResourceService;
import es.caib.comanda.usuaris.logic.helper.UsuarisRefreshHelper;
import es.caib.comanda.usuaris.logic.intf.model.Usuari;
import es.caib.comanda.usuaris.logic.intf.service.UsuariService;
import es.caib.comanda.usuaris.persist.entity.UsuariEntity;
import es.caib.comanda.usuaris.persist.repository.UsuariRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.io.Serializable;
import java.util.*;

@Slf4j
@Service
@RequiredArgsConstructor
public class UsuariServiceImpl extends BaseMutableResourceService<Usuari, Long, UsuariEntity> implements UsuariService {

	private final AuthenticationHelper authenticationHelper;
	private final ParametresHelper parametresHelper;
	private final UsuarisRefreshHelper usuarisRefreshHelper;

    @PostConstruct
    public void init() {
        register(Usuari.Fields.alarmaMail, new AlarmaMailOnchangeLogicProcessor());
		register(Usuari.PERSPECTIVE_PREVIEW_AUTOGENERATED_EMAIL, new PreviewAutogeneratedEmailPerspectiveApplicator());
		register(Usuari.PERSPECTIVE_DARRERA_CONNEXIO, new DarreraConnexioPerspectiveApplicator());
    }

	@Override
	protected String additionalSpringFilter(String currentSpringFilter, String[] namedQueries) {
		List<Filter> filters = new ArrayList<>();
		if (currentSpringFilter != null && !currentSpringFilter.isEmpty()) {
			filters.add(Filter.parse(currentSpringFilter));
		}
		filters.add(FilterBuilder.equal("codi", authenticationHelper.getCurrentUserName()));
		return FilterBuilder.and(filters).generate();
	}

	@Override
	protected void afterConversion(UsuariEntity entity, Usuari resource) {
		Usuari usuariAuth = usuarisRefreshHelper.getUsuariFromAuth();
		resource.setRols(usuariAuth.getRols());
	}

    @Override
    public Usuari findOneInternalByCodi(String codi) {
        UsuariEntity usuariEntity = ((UsuariRepository) entityRepository).findByCodi(codi)
                .orElseThrow(() -> new ResourceNotFoundException(Usuari.class, "codi:" + codi));
        return entityToResource(usuariEntity);
    }

    public class AlarmaMailOnchangeLogicProcessor implements OnChangeLogicProcessor<Usuari> {
        @Override
        public void onChange(Serializable id, Usuari previous, String fieldName, Object fieldValue, Map<String, AnswerRequiredException.AnswerValue> answers, String[] previousFieldNames, Usuari target) {
            if (Boolean.FALSE.equals(fieldValue)) {
                target.setAlarmaMailAgrupar(false);
            }
        }
    }

	public class PreviewAutogeneratedEmailPerspectiveApplicator implements PerspectiveApplicator<UsuariEntity, Usuari> {
		@Override
		public void applySingle(String code, UsuariEntity entity, Usuari resource) throws PerspectiveApplicationException {
			String defaultDomainName = parametresHelper.getParametreText(BaseConfig.PROP_ALARMA_MAIL_DEFAULT_DOMAIN, "caib.es");
			resource.setAutogeneratedEmail(entity.getCodi() + "@" + defaultDomainName);
		}
	}

	public class DarreraConnexioPerspectiveApplicator implements PerspectiveApplicator<UsuariEntity, Usuari> {
		@Override
		public void applySingle(String code, UsuariEntity entity, Usuari resource) throws PerspectiveApplicationException {
			resource.setDarreraConnexio(entity.getFiDarrerPeriode());
		}
	}

}
