/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.Manual;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Context o &#39;namespace&#39; funcional exposat per l&#39;aplicació
 */
@JsonPropertyOrder({
  ContextInfo.JSON_PROPERTY_CODI,
  ContextInfo.JSON_PROPERTY_NOM,
  ContextInfo.JSON_PROPERTY_PATH,
  ContextInfo.JSON_PROPERTY_MANUALS,
  ContextInfo.JSON_PROPERTY_API
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ContextInfo {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nonnull
  private String nom;

  public static final String JSON_PROPERTY_PATH = "path";
  @javax.annotation.Nonnull
  private String path;

  public static final String JSON_PROPERTY_MANUALS = "manuals";
  @javax.annotation.Nullable
  private List<Manual> manuals = new ArrayList<>();

  public static final String JSON_PROPERTY_API = "api";
  @javax.annotation.Nullable
  private String api;

  public ContextInfo() {
  }

  public ContextInfo codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi del context
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public ContextInfo nom(@javax.annotation.Nonnull String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Nom descriptiu del context
   * @return nom
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNom(@javax.annotation.Nonnull String nom) {
    this.nom = nom;
  }

  public ContextInfo path(@javax.annotation.Nonnull String path) {
    
    this.path = path;
    return this;
  }

  /**
   * Path base del context
   * @return path
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPath() {
    return path;
  }


  @JsonProperty(value = JSON_PROPERTY_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPath(@javax.annotation.Nonnull String path) {
    this.path = path;
  }

  public ContextInfo manuals(@javax.annotation.Nullable List<Manual> manuals) {
    
    this.manuals = manuals;
    return this;
  }

  public ContextInfo addManualsItem(Manual manualsItem) {
    if (this.manuals == null) {
      this.manuals = new ArrayList<>();
    }
    this.manuals.add(manualsItem);
    return this;
  }

  /**
   * Llista de manuals associats al context
   * @return manuals
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANUALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Manual> getManuals() {
    return manuals;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUALS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManuals(@javax.annotation.Nullable List<Manual> manuals) {
    this.manuals = manuals;
  }

  public ContextInfo api(@javax.annotation.Nullable String api) {
    
    this.api = api;
    return this;
  }

  /**
   * URL o especificació OpenAPI del context, si està disponible
   * @return api
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_API, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApi() {
    return api;
  }


  @JsonProperty(value = JSON_PROPERTY_API, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApi(@javax.annotation.Nullable String api) {
    this.api = api;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContextInfo contextInfo = (ContextInfo) o;
    return Objects.equals(this.codi, contextInfo.codi) &&
        Objects.equals(this.nom, contextInfo.nom) &&
        Objects.equals(this.path, contextInfo.path) &&
        Objects.equals(this.manuals, contextInfo.manuals) &&
        Objects.equals(this.api, contextInfo.api);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom, path, manuals, api);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContextInfo {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    manuals: ").append(toIndentedString(manuals)).append("\n");
    sb.append("    api: ").append(toIndentedString(api)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

