/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.EstatSalutEnum;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EstatSalut
 */
@JsonPropertyOrder({
  EstatSalut.JSON_PROPERTY_ESTAT,
  EstatSalut.JSON_PROPERTY_LATENCIA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class EstatSalut {
  public static final String JSON_PROPERTY_ESTAT = "estat";
  @javax.annotation.Nullable
  private EstatSalutEnum estat;

  public static final String JSON_PROPERTY_LATENCIA = "latencia";
  @javax.annotation.Nullable
  private Integer latencia;

  public EstatSalut() {
  }

  public EstatSalut estat(@javax.annotation.Nullable EstatSalutEnum estat) {
    
    this.estat = estat;
    return this;
  }

  /**
   * Get estat
   * @return estat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ESTAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EstatSalutEnum getEstat() {
    return estat;
  }


  @JsonProperty(value = JSON_PROPERTY_ESTAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstat(@javax.annotation.Nullable EstatSalutEnum estat) {
    this.estat = estat;
  }

  public EstatSalut latencia(@javax.annotation.Nullable Integer latencia) {
    
    this.latencia = latencia;
    return this;
  }

  /**
   * Get latencia
   * @return latencia
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLatencia() {
    return latencia;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatencia(@javax.annotation.Nullable Integer latencia) {
    this.latencia = latencia;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstatSalut estatSalut = (EstatSalut) o;
    return Objects.equals(this.estat, estatSalut.estat) &&
        Objects.equals(this.latencia, estatSalut.latencia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estat, latencia);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstatSalut {\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    latencia: ").append(toIndentedString(latencia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

