/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.DimensioDesc;
import es.caib.comanda.model.monitoring.IndicadorDesc;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Catàleg de dimensions i indicadors d&#39;estadística disponibles per a una APP
 */
@JsonPropertyOrder({
  EstadistiquesInfo.JSON_PROPERTY_CODI,
  EstadistiquesInfo.JSON_PROPERTY_VERSIO,
  EstadistiquesInfo.JSON_PROPERTY_DATA,
  EstadistiquesInfo.JSON_PROPERTY_DIMENSIONS,
  EstadistiquesInfo.JSON_PROPERTY_INDICADORS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class EstadistiquesInfo {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_VERSIO = "versio";
  @javax.annotation.Nullable
  private String versio;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private OffsetDateTime data;

  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  @javax.annotation.Nonnull
  private List<DimensioDesc> dimensions = new ArrayList<>();

  public static final String JSON_PROPERTY_INDICADORS = "indicadors";
  @javax.annotation.Nonnull
  private List<IndicadorDesc> indicadors = new ArrayList<>();

  public EstadistiquesInfo() {
  }

  public EstadistiquesInfo codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi identificador de l&#39;aplicació
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public EstadistiquesInfo versio(@javax.annotation.Nullable String versio) {
    
    this.versio = versio;
    return this;
  }

  /**
   * Versió de l&#39;aplicació
   * @return versio
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersio() {
    return versio;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersio(@javax.annotation.Nullable String versio) {
    this.versio = versio;
  }

  public EstadistiquesInfo data(@javax.annotation.Nullable OffsetDateTime data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable OffsetDateTime data) {
    this.data = data;
  }

  public EstadistiquesInfo dimensions(@javax.annotation.Nonnull List<DimensioDesc> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public EstadistiquesInfo addDimensionsItem(DimensioDesc dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

  /**
   * Dimensions estadístiques disponibles
   * @return dimensions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DIMENSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<DimensioDesc> getDimensions() {
    return dimensions;
  }


  @JsonProperty(value = JSON_PROPERTY_DIMENSIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDimensions(@javax.annotation.Nonnull List<DimensioDesc> dimensions) {
    this.dimensions = dimensions;
  }

  public EstadistiquesInfo indicadors(@javax.annotation.Nonnull List<IndicadorDesc> indicadors) {
    
    this.indicadors = indicadors;
    return this;
  }

  public EstadistiquesInfo addIndicadorsItem(IndicadorDesc indicadorsItem) {
    if (this.indicadors == null) {
      this.indicadors = new ArrayList<>();
    }
    this.indicadors.add(indicadorsItem);
    return this;
  }

  /**
   * Indicadors estadístics disponibles
   * @return indicadors
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_INDICADORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<IndicadorDesc> getIndicadors() {
    return indicadors;
  }


  @JsonProperty(value = JSON_PROPERTY_INDICADORS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIndicadors(@javax.annotation.Nonnull List<IndicadorDesc> indicadors) {
    this.indicadors = indicadors;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EstadistiquesInfo estadistiquesInfo = (EstadistiquesInfo) o;
    return Objects.equals(this.codi, estadistiquesInfo.codi) &&
        Objects.equals(this.versio, estadistiquesInfo.versio) &&
        Objects.equals(this.data, estadistiquesInfo.data) &&
        Objects.equals(this.dimensions, estadistiquesInfo.dimensions) &&
        Objects.equals(this.indicadors, estadistiquesInfo.indicadors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, versio, data, dimensions, indicadors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EstadistiquesInfo {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    versio: ").append(toIndentedString(versio)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    indicadors: ").append(toIndentedString(indicadors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

