/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Mètriques de peticions d&#39;una integració: totals i darrer període
 */
@JsonPropertyOrder({
  IntegracioPeticions.JSON_PROPERTY_TOTAL_OK,
  IntegracioPeticions.JSON_PROPERTY_TOTAL_ERROR,
  IntegracioPeticions.JSON_PROPERTY_TOTAL_TEMPS_MIG,
  IntegracioPeticions.JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE,
  IntegracioPeticions.JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE,
  IntegracioPeticions.JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE,
  IntegracioPeticions.JSON_PROPERTY_ENDPOINT,
  IntegracioPeticions.JSON_PROPERTY_PETICIONS_PER_ENTORN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class IntegracioPeticions {
  public static final String JSON_PROPERTY_TOTAL_OK = "totalOk";
  @javax.annotation.Nullable
  private Long totalOk;

  public static final String JSON_PROPERTY_TOTAL_ERROR = "totalError";
  @javax.annotation.Nullable
  private Long totalError;

  public static final String JSON_PROPERTY_TOTAL_TEMPS_MIG = "totalTempsMig";
  @javax.annotation.Nullable
  private Integer totalTempsMig;

  public static final String JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE = "peticionsOkUltimPeriode";
  @javax.annotation.Nullable
  private Long peticionsOkUltimPeriode;

  public static final String JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE = "peticionsErrorUltimPeriode";
  @javax.annotation.Nullable
  private Long peticionsErrorUltimPeriode;

  public static final String JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE = "tempsMigUltimPeriode";
  @javax.annotation.Nullable
  private Integer tempsMigUltimPeriode;

  public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
  @javax.annotation.Nullable
  private String endpoint;

  public static final String JSON_PROPERTY_PETICIONS_PER_ENTORN = "peticionsPerEntorn";
  @javax.annotation.Nullable
  private Map<String, IntegracioPeticions> peticionsPerEntorn = new HashMap<>();

  public IntegracioPeticions() {
  }

  public IntegracioPeticions totalOk(@javax.annotation.Nullable Long totalOk) {
    
    this.totalOk = totalOk;
    return this;
  }

  /**
   * Nombre total de peticions amb resultat correcte
   * @return totalOk
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_OK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalOk() {
    return totalOk;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_OK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalOk(@javax.annotation.Nullable Long totalOk) {
    this.totalOk = totalOk;
  }

  public IntegracioPeticions totalError(@javax.annotation.Nullable Long totalError) {
    
    this.totalError = totalError;
    return this;
  }

  /**
   * Nombre total de peticions amb error
   * @return totalError
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTotalError() {
    return totalError;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ERROR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalError(@javax.annotation.Nullable Long totalError) {
    this.totalError = totalError;
  }

  public IntegracioPeticions totalTempsMig(@javax.annotation.Nullable Integer totalTempsMig) {
    
    this.totalTempsMig = totalTempsMig;
    return this;
  }

  /**
   * Temps mig total de resposta (ms)
   * @return totalTempsMig
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TEMPS_MIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTotalTempsMig() {
    return totalTempsMig;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TEMPS_MIG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalTempsMig(@javax.annotation.Nullable Integer totalTempsMig) {
    this.totalTempsMig = totalTempsMig;
  }

  public IntegracioPeticions peticionsOkUltimPeriode(@javax.annotation.Nullable Long peticionsOkUltimPeriode) {
    
    this.peticionsOkUltimPeriode = peticionsOkUltimPeriode;
    return this;
  }

  /**
   * Peticions OK en el darrer període
   * @return peticionsOkUltimPeriode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPeticionsOkUltimPeriode() {
    return peticionsOkUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeticionsOkUltimPeriode(@javax.annotation.Nullable Long peticionsOkUltimPeriode) {
    this.peticionsOkUltimPeriode = peticionsOkUltimPeriode;
  }

  public IntegracioPeticions peticionsErrorUltimPeriode(@javax.annotation.Nullable Long peticionsErrorUltimPeriode) {
    
    this.peticionsErrorUltimPeriode = peticionsErrorUltimPeriode;
    return this;
  }

  /**
   * Peticions en error en el darrer període
   * @return peticionsErrorUltimPeriode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPeticionsErrorUltimPeriode() {
    return peticionsErrorUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeticionsErrorUltimPeriode(@javax.annotation.Nullable Long peticionsErrorUltimPeriode) {
    this.peticionsErrorUltimPeriode = peticionsErrorUltimPeriode;
  }

  public IntegracioPeticions tempsMigUltimPeriode(@javax.annotation.Nullable Integer tempsMigUltimPeriode) {
    
    this.tempsMigUltimPeriode = tempsMigUltimPeriode;
    return this;
  }

  /**
   * Temps mig de resposta en el darrer període (ms)
   * @return tempsMigUltimPeriode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTempsMigUltimPeriode() {
    return tempsMigUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTempsMigUltimPeriode(@javax.annotation.Nullable Integer tempsMigUltimPeriode) {
    this.tempsMigUltimPeriode = tempsMigUltimPeriode;
  }

  public IntegracioPeticions endpoint(@javax.annotation.Nullable String endpoint) {
    
    this.endpoint = endpoint;
    return this;
  }

  /**
   * Endpoint concret associat a aquestes mètriques
   * @return endpoint
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndpoint() {
    return endpoint;
  }


  @JsonProperty(value = JSON_PROPERTY_ENDPOINT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndpoint(@javax.annotation.Nullable String endpoint) {
    this.endpoint = endpoint;
  }

  public IntegracioPeticions peticionsPerEntorn(@javax.annotation.Nullable Map<String, IntegracioPeticions> peticionsPerEntorn) {
    
    this.peticionsPerEntorn = peticionsPerEntorn;
    return this;
  }

  public IntegracioPeticions putPeticionsPerEntornItem(String key, IntegracioPeticions peticionsPerEntornItem) {
    if (this.peticionsPerEntorn == null) {
      this.peticionsPerEntorn = new HashMap<>();
    }
    this.peticionsPerEntorn.put(key, peticionsPerEntornItem);
    return this;
  }

  /**
   * Mètriques per entorn (clau &#x3D; codi d&#39;entorn)
   * @return peticionsPerEntorn
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PETICIONS_PER_ENTORN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, IntegracioPeticions> getPeticionsPerEntorn() {
    return peticionsPerEntorn;
  }


  @JsonProperty(value = JSON_PROPERTY_PETICIONS_PER_ENTORN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeticionsPerEntorn(@javax.annotation.Nullable Map<String, IntegracioPeticions> peticionsPerEntorn) {
    this.peticionsPerEntorn = peticionsPerEntorn;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntegracioPeticions integracioPeticions = (IntegracioPeticions) o;
    return Objects.equals(this.totalOk, integracioPeticions.totalOk) &&
        Objects.equals(this.totalError, integracioPeticions.totalError) &&
        Objects.equals(this.totalTempsMig, integracioPeticions.totalTempsMig) &&
        Objects.equals(this.peticionsOkUltimPeriode, integracioPeticions.peticionsOkUltimPeriode) &&
        Objects.equals(this.peticionsErrorUltimPeriode, integracioPeticions.peticionsErrorUltimPeriode) &&
        Objects.equals(this.tempsMigUltimPeriode, integracioPeticions.tempsMigUltimPeriode) &&
        Objects.equals(this.endpoint, integracioPeticions.endpoint) &&
        Objects.equals(this.peticionsPerEntorn, integracioPeticions.peticionsPerEntorn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(totalOk, totalError, totalTempsMig, peticionsOkUltimPeriode, peticionsErrorUltimPeriode, tempsMigUltimPeriode, endpoint, peticionsPerEntorn);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntegracioPeticions {\n");
    sb.append("    totalOk: ").append(toIndentedString(totalOk)).append("\n");
    sb.append("    totalError: ").append(toIndentedString(totalError)).append("\n");
    sb.append("    totalTempsMig: ").append(toIndentedString(totalTempsMig)).append("\n");
    sb.append("    peticionsOkUltimPeriode: ").append(toIndentedString(peticionsOkUltimPeriode)).append("\n");
    sb.append("    peticionsErrorUltimPeriode: ").append(toIndentedString(peticionsErrorUltimPeriode)).append("\n");
    sb.append("    tempsMigUltimPeriode: ").append(toIndentedString(tempsMigUltimPeriode)).append("\n");
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    peticionsPerEntorn: ").append(toIndentedString(peticionsPerEntorn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

