/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.ZoneOffset;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ModelOffsetDateTime
 */
@JsonPropertyOrder({
  ModelOffsetDateTime.JSON_PROPERTY_DATE_TIME,
  ModelOffsetDateTime.JSON_PROPERTY_OFFSET
})
@JsonTypeName("OffsetDateTime")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ModelOffsetDateTime {
  public static final String JSON_PROPERTY_DATE_TIME = "dateTime";
  @javax.annotation.Nullable
  private OffsetDateTime dateTime;

  public static final String JSON_PROPERTY_OFFSET = "offset";
  @javax.annotation.Nullable
  private ZoneOffset offset;

  public ModelOffsetDateTime() {
  }

  public ModelOffsetDateTime dateTime(@javax.annotation.Nullable OffsetDateTime dateTime) {
    
    this.dateTime = dateTime;
    return this;
  }

  /**
   * Get dateTime
   * @return dateTime
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDateTime() {
    return dateTime;
  }


  @JsonProperty(value = JSON_PROPERTY_DATE_TIME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateTime(@javax.annotation.Nullable OffsetDateTime dateTime) {
    this.dateTime = dateTime;
  }

  public ModelOffsetDateTime offset(@javax.annotation.Nullable ZoneOffset offset) {
    
    this.offset = offset;
    return this;
  }

  /**
   * Get offset
   * @return offset
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ZoneOffset getOffset() {
    return offset;
  }


  @JsonProperty(value = JSON_PROPERTY_OFFSET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOffset(@javax.annotation.Nullable ZoneOffset offset) {
    this.offset = offset;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelOffsetDateTime _offsetDateTime = (ModelOffsetDateTime) o;
    return Objects.equals(this.dateTime, _offsetDateTime.dateTime) &&
        Objects.equals(this.offset, _offsetDateTime.offset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateTime, offset);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelOffsetDateTime {\n");
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

