/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.RegistreEstadistic;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Registres estadístics d&#39;un instant de temps amb les seves mesures
 */
@JsonPropertyOrder({
  RegistresEstadistics.JSON_PROPERTY_TEMPS,
  RegistresEstadistics.JSON_PROPERTY_FETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RegistresEstadistics {
  public static final String JSON_PROPERTY_TEMPS = "temps";
  @javax.annotation.Nonnull
  private OffsetDateTime temps;

  public static final String JSON_PROPERTY_FETS = "fets";
  @javax.annotation.Nullable
  private List<RegistreEstadistic> fets = new ArrayList<>();

  public RegistresEstadistics() {
  }

  public RegistresEstadistics temps(@javax.annotation.Nonnull OffsetDateTime temps) {
    
    this.temps = temps;
    return this;
  }

  /**
   * Get temps
   * @return temps
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getTemps() {
    return temps;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTemps(@javax.annotation.Nonnull OffsetDateTime temps) {
    this.temps = temps;
  }

  public RegistresEstadistics fets(@javax.annotation.Nullable List<RegistreEstadistic> fets) {
    
    this.fets = fets;
    return this;
  }

  public RegistresEstadistics addFetsItem(RegistreEstadistic fetsItem) {
    if (this.fets == null) {
      this.fets = new ArrayList<>();
    }
    this.fets.add(fetsItem);
    return this;
  }

  /**
   * Llista de registres o fets estadístics recollits en l&#39;instant indicat
   * @return fets
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RegistreEstadistic> getFets() {
    return fets;
  }


  @JsonProperty(value = JSON_PROPERTY_FETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFets(@javax.annotation.Nullable List<RegistreEstadistic> fets) {
    this.fets = fets;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistresEstadistics registresEstadistics = (RegistresEstadistics) o;
    return Objects.equals(this.temps, registresEstadistics.temps) &&
        Objects.equals(this.fets, registresEstadistics.fets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(temps, fets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistresEstadistics {\n");
    sb.append("    temps: ").append(toIndentedString(temps)).append("\n");
    sb.append("    fets: ").append(toIndentedString(fets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

