/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.EstatSalut;
import es.caib.comanda.model.monitoring.InformacioSistema;
import es.caib.comanda.model.monitoring.IntegracioSalut;
import es.caib.comanda.model.monitoring.MissatgeSalut;
import es.caib.comanda.model.monitoring.SubsistemaSalut;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Estat de salut funcional de l&#39;aplicació i metadades associades
 */
@JsonPropertyOrder({
  SalutInfo.JSON_PROPERTY_CODI,
  SalutInfo.JSON_PROPERTY_DATA,
  SalutInfo.JSON_PROPERTY_ESTAT_GLOBAL,
  SalutInfo.JSON_PROPERTY_ESTAT_BASE_DE_DADES,
  SalutInfo.JSON_PROPERTY_INTEGRACIONS,
  SalutInfo.JSON_PROPERTY_INFORMACIO_SISTEMA,
  SalutInfo.JSON_PROPERTY_MISSATGES,
  SalutInfo.JSON_PROPERTY_VERSIO,
  SalutInfo.JSON_PROPERTY_SUBSISTEMES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SalutInfo {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private OffsetDateTime data;

  public static final String JSON_PROPERTY_ESTAT_GLOBAL = "estatGlobal";
  @javax.annotation.Nonnull
  private EstatSalut estatGlobal;

  public static final String JSON_PROPERTY_ESTAT_BASE_DE_DADES = "estatBaseDeDades";
  @javax.annotation.Nonnull
  private EstatSalut estatBaseDeDades;

  public static final String JSON_PROPERTY_INTEGRACIONS = "integracions";
  @javax.annotation.Nullable
  private List<IntegracioSalut> integracions = new ArrayList<>();

  public static final String JSON_PROPERTY_INFORMACIO_SISTEMA = "informacioSistema";
  @javax.annotation.Nullable
  private InformacioSistema informacioSistema;

  public static final String JSON_PROPERTY_MISSATGES = "missatges";
  @javax.annotation.Nullable
  private List<MissatgeSalut> missatges = new ArrayList<>();

  public static final String JSON_PROPERTY_VERSIO = "versio";
  @javax.annotation.Nullable
  private String versio;

  public static final String JSON_PROPERTY_SUBSISTEMES = "subsistemes";
  @javax.annotation.Nullable
  private List<SubsistemaSalut> subsistemes = new ArrayList<>();

  public SalutInfo() {
  }

  public SalutInfo codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi identificador de l&#39;aplicació
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public SalutInfo data(@javax.annotation.Nonnull OffsetDateTime data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull OffsetDateTime data) {
    this.data = data;
  }

  public SalutInfo estatGlobal(@javax.annotation.Nonnull EstatSalut estatGlobal) {
    
    this.estatGlobal = estatGlobal;
    return this;
  }

  /**
   * Get estatGlobal
   * @return estatGlobal
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ESTAT_GLOBAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EstatSalut getEstatGlobal() {
    return estatGlobal;
  }


  @JsonProperty(value = JSON_PROPERTY_ESTAT_GLOBAL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEstatGlobal(@javax.annotation.Nonnull EstatSalut estatGlobal) {
    this.estatGlobal = estatGlobal;
  }

  public SalutInfo estatBaseDeDades(@javax.annotation.Nonnull EstatSalut estatBaseDeDades) {
    
    this.estatBaseDeDades = estatBaseDeDades;
    return this;
  }

  /**
   * Get estatBaseDeDades
   * @return estatBaseDeDades
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ESTAT_BASE_DE_DADES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public EstatSalut getEstatBaseDeDades() {
    return estatBaseDeDades;
  }


  @JsonProperty(value = JSON_PROPERTY_ESTAT_BASE_DE_DADES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEstatBaseDeDades(@javax.annotation.Nonnull EstatSalut estatBaseDeDades) {
    this.estatBaseDeDades = estatBaseDeDades;
  }

  public SalutInfo integracions(@javax.annotation.Nullable List<IntegracioSalut> integracions) {
    
    this.integracions = integracions;
    return this;
  }

  public SalutInfo addIntegracionsItem(IntegracioSalut integracionsItem) {
    if (this.integracions == null) {
      this.integracions = new ArrayList<>();
    }
    this.integracions.add(integracionsItem);
    return this;
  }

  /**
   * Integracions amb el seu estat
   * @return integracions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INTEGRACIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IntegracioSalut> getIntegracions() {
    return integracions;
  }


  @JsonProperty(value = JSON_PROPERTY_INTEGRACIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIntegracions(@javax.annotation.Nullable List<IntegracioSalut> integracions) {
    this.integracions = integracions;
  }

  public SalutInfo informacioSistema(@javax.annotation.Nullable InformacioSistema informacioSistema) {
    
    this.informacioSistema = informacioSistema;
    return this;
  }

  /**
   * Get informacioSistema
   * @return informacioSistema
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INFORMACIO_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InformacioSistema getInformacioSistema() {
    return informacioSistema;
  }


  @JsonProperty(value = JSON_PROPERTY_INFORMACIO_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInformacioSistema(@javax.annotation.Nullable InformacioSistema informacioSistema) {
    this.informacioSistema = informacioSistema;
  }

  public SalutInfo missatges(@javax.annotation.Nullable List<MissatgeSalut> missatges) {
    
    this.missatges = missatges;
    return this;
  }

  public SalutInfo addMissatgesItem(MissatgeSalut missatgesItem) {
    if (this.missatges == null) {
      this.missatges = new ArrayList<>();
    }
    this.missatges.add(missatgesItem);
    return this;
  }

  /**
   * Missatges informatius o d&#39;alerta
   * @return missatges
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MISSATGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<MissatgeSalut> getMissatges() {
    return missatges;
  }


  @JsonProperty(value = JSON_PROPERTY_MISSATGES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMissatges(@javax.annotation.Nullable List<MissatgeSalut> missatges) {
    this.missatges = missatges;
  }

  public SalutInfo versio(@javax.annotation.Nullable String versio) {
    
    this.versio = versio;
    return this;
  }

  /**
   * Versió de l&#39;aplicació
   * @return versio
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getVersio() {
    return versio;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersio(@javax.annotation.Nullable String versio) {
    this.versio = versio;
  }

  public SalutInfo subsistemes(@javax.annotation.Nullable List<SubsistemaSalut> subsistemes) {
    
    this.subsistemes = subsistemes;
    return this;
  }

  public SalutInfo addSubsistemesItem(SubsistemaSalut subsistemesItem) {
    if (this.subsistemes == null) {
      this.subsistemes = new ArrayList<>();
    }
    this.subsistemes.add(subsistemesItem);
    return this;
  }

  /**
   * Subsistemes interns amb el seu estat
   * @return subsistemes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBSISTEMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<SubsistemaSalut> getSubsistemes() {
    return subsistemes;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBSISTEMES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubsistemes(@javax.annotation.Nullable List<SubsistemaSalut> subsistemes) {
    this.subsistemes = subsistemes;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalutInfo salutInfo = (SalutInfo) o;
    return Objects.equals(this.codi, salutInfo.codi) &&
        Objects.equals(this.data, salutInfo.data) &&
        Objects.equals(this.estatGlobal, salutInfo.estatGlobal) &&
        Objects.equals(this.estatBaseDeDades, salutInfo.estatBaseDeDades) &&
        Objects.equals(this.integracions, salutInfo.integracions) &&
        Objects.equals(this.informacioSistema, salutInfo.informacioSistema) &&
        Objects.equals(this.missatges, salutInfo.missatges) &&
        Objects.equals(this.versio, salutInfo.versio) &&
        Objects.equals(this.subsistemes, salutInfo.subsistemes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, data, estatGlobal, estatBaseDeDades, integracions, informacioSistema, missatges, versio, subsistemes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalutInfo {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    estatGlobal: ").append(toIndentedString(estatGlobal)).append("\n");
    sb.append("    estatBaseDeDades: ").append(toIndentedString(estatBaseDeDades)).append("\n");
    sb.append("    integracions: ").append(toIndentedString(integracions)).append("\n");
    sb.append("    informacioSistema: ").append(toIndentedString(informacioSistema)).append("\n");
    sb.append("    missatges: ").append(toIndentedString(missatges)).append("\n");
    sb.append("    versio: ").append(toIndentedString(versio)).append("\n");
    sb.append("    subsistemes: ").append(toIndentedString(subsistemes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

