/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.EstatSalutEnum;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Estat de salut i mètriques d&#39;un subsistema intern
 */
@JsonPropertyOrder({
  SubsistemaSalut.JSON_PROPERTY_ESTAT,
  SubsistemaSalut.JSON_PROPERTY_LATENCIA,
  SubsistemaSalut.JSON_PROPERTY_CODI,
  SubsistemaSalut.JSON_PROPERTY_TOTAL_OK,
  SubsistemaSalut.JSON_PROPERTY_TOTAL_ERROR,
  SubsistemaSalut.JSON_PROPERTY_TOTAL_TEMPS_MIG,
  SubsistemaSalut.JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE,
  SubsistemaSalut.JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE,
  SubsistemaSalut.JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SubsistemaSalut {
  public static final String JSON_PROPERTY_ESTAT = "estat";
  @javax.annotation.Nullable
  private EstatSalutEnum estat;

  public static final String JSON_PROPERTY_LATENCIA = "latencia";
  @javax.annotation.Nullable
  private Integer latencia;

  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_TOTAL_OK = "totalOk";
  @javax.annotation.Nonnull
  private Long totalOk;

  public static final String JSON_PROPERTY_TOTAL_ERROR = "totalError";
  @javax.annotation.Nonnull
  private Long totalError;

  public static final String JSON_PROPERTY_TOTAL_TEMPS_MIG = "totalTempsMig";
  @javax.annotation.Nonnull
  private Integer totalTempsMig;

  public static final String JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE = "peticionsOkUltimPeriode";
  @javax.annotation.Nonnull
  private Long peticionsOkUltimPeriode;

  public static final String JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE = "peticionsErrorUltimPeriode";
  @javax.annotation.Nonnull
  private Long peticionsErrorUltimPeriode;

  public static final String JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE = "tempsMigUltimPeriode";
  @javax.annotation.Nonnull
  private Integer tempsMigUltimPeriode;

  public SubsistemaSalut() {
  }

  public SubsistemaSalut estat(@javax.annotation.Nullable EstatSalutEnum estat) {
    
    this.estat = estat;
    return this;
  }

  /**
   * Get estat
   * @return estat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ESTAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EstatSalutEnum getEstat() {
    return estat;
  }


  @JsonProperty(value = JSON_PROPERTY_ESTAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstat(@javax.annotation.Nullable EstatSalutEnum estat) {
    this.estat = estat;
  }

  public SubsistemaSalut latencia(@javax.annotation.Nullable Integer latencia) {
    
    this.latencia = latencia;
    return this;
  }

  /**
   * Get latencia
   * @return latencia
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LATENCIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getLatencia() {
    return latencia;
  }


  @JsonProperty(value = JSON_PROPERTY_LATENCIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatencia(@javax.annotation.Nullable Integer latencia) {
    this.latencia = latencia;
  }

  public SubsistemaSalut codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi del subsistema
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public SubsistemaSalut totalOk(@javax.annotation.Nonnull Long totalOk) {
    
    this.totalOk = totalOk;
    return this;
  }

  /**
   * Total de peticions amb resultat correcte
   * @return totalOk
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_OK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTotalOk() {
    return totalOk;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_OK, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalOk(@javax.annotation.Nonnull Long totalOk) {
    this.totalOk = totalOk;
  }

  public SubsistemaSalut totalError(@javax.annotation.Nonnull Long totalError) {
    
    this.totalError = totalError;
    return this;
  }

  /**
   * Total de peticions amb error
   * @return totalError
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTotalError() {
    return totalError;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_ERROR, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalError(@javax.annotation.Nonnull Long totalError) {
    this.totalError = totalError;
  }

  public SubsistemaSalut totalTempsMig(@javax.annotation.Nonnull Integer totalTempsMig) {
    
    this.totalTempsMig = totalTempsMig;
    return this;
  }

  /**
   * Temps mig total de resposta (ms)
   * @return totalTempsMig
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TOTAL_TEMPS_MIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTotalTempsMig() {
    return totalTempsMig;
  }


  @JsonProperty(value = JSON_PROPERTY_TOTAL_TEMPS_MIG, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTotalTempsMig(@javax.annotation.Nonnull Integer totalTempsMig) {
    this.totalTempsMig = totalTempsMig;
  }

  public SubsistemaSalut peticionsOkUltimPeriode(@javax.annotation.Nonnull Long peticionsOkUltimPeriode) {
    
    this.peticionsOkUltimPeriode = peticionsOkUltimPeriode;
    return this;
  }

  /**
   * Peticions OK en el darrer període
   * @return peticionsOkUltimPeriode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPeticionsOkUltimPeriode() {
    return peticionsOkUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_PETICIONS_OK_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeticionsOkUltimPeriode(@javax.annotation.Nonnull Long peticionsOkUltimPeriode) {
    this.peticionsOkUltimPeriode = peticionsOkUltimPeriode;
  }

  public SubsistemaSalut peticionsErrorUltimPeriode(@javax.annotation.Nonnull Long peticionsErrorUltimPeriode) {
    
    this.peticionsErrorUltimPeriode = peticionsErrorUltimPeriode;
    return this;
  }

  /**
   * Peticions en error en el darrer període
   * @return peticionsErrorUltimPeriode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getPeticionsErrorUltimPeriode() {
    return peticionsErrorUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_PETICIONS_ERROR_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeticionsErrorUltimPeriode(@javax.annotation.Nonnull Long peticionsErrorUltimPeriode) {
    this.peticionsErrorUltimPeriode = peticionsErrorUltimPeriode;
  }

  public SubsistemaSalut tempsMigUltimPeriode(@javax.annotation.Nonnull Integer tempsMigUltimPeriode) {
    
    this.tempsMigUltimPeriode = tempsMigUltimPeriode;
    return this;
  }

  /**
   * Temps mig de resposta en el darrer període (ms)
   * @return tempsMigUltimPeriode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getTempsMigUltimPeriode() {
    return tempsMigUltimPeriode;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPS_MIG_ULTIM_PERIODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTempsMigUltimPeriode(@javax.annotation.Nonnull Integer tempsMigUltimPeriode) {
    this.tempsMigUltimPeriode = tempsMigUltimPeriode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubsistemaSalut subsistemaSalut = (SubsistemaSalut) o;
    return Objects.equals(this.estat, subsistemaSalut.estat) &&
        Objects.equals(this.latencia, subsistemaSalut.latencia) &&
        Objects.equals(this.codi, subsistemaSalut.codi) &&
        Objects.equals(this.totalOk, subsistemaSalut.totalOk) &&
        Objects.equals(this.totalError, subsistemaSalut.totalError) &&
        Objects.equals(this.totalTempsMig, subsistemaSalut.totalTempsMig) &&
        Objects.equals(this.peticionsOkUltimPeriode, subsistemaSalut.peticionsOkUltimPeriode) &&
        Objects.equals(this.peticionsErrorUltimPeriode, subsistemaSalut.peticionsErrorUltimPeriode) &&
        Objects.equals(this.tempsMigUltimPeriode, subsistemaSalut.tempsMigUltimPeriode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(estat, latencia, codi, totalOk, totalError, totalTempsMig, peticionsOkUltimPeriode, peticionsErrorUltimPeriode, tempsMigUltimPeriode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsistemaSalut {\n");
    sb.append("    estat: ").append(toIndentedString(estat)).append("\n");
    sb.append("    latencia: ").append(toIndentedString(latencia)).append("\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    totalOk: ").append(toIndentedString(totalOk)).append("\n");
    sb.append("    totalError: ").append(toIndentedString(totalError)).append("\n");
    sb.append("    totalTempsMig: ").append(toIndentedString(totalTempsMig)).append("\n");
    sb.append("    peticionsOkUltimPeriode: ").append(toIndentedString(peticionsOkUltimPeriode)).append("\n");
    sb.append("    peticionsErrorUltimPeriode: ").append(toIndentedString(peticionsErrorUltimPeriode)).append("\n");
    sb.append("    tempsMigUltimPeriode: ").append(toIndentedString(tempsMigUltimPeriode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

