/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació d&#39;un subsistema intern de l&#39;aplicació
 */
@JsonPropertyOrder({
  SubsistemaInfo.JSON_PROPERTY_CODI,
  SubsistemaInfo.JSON_PROPERTY_NOM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class SubsistemaInfo {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nonnull
  private String nom;

  public SubsistemaInfo() {
  }

  public SubsistemaInfo codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi del subsistema
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public SubsistemaInfo nom(@javax.annotation.Nonnull String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Nom del subsistema
   * @return nom
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNom(@javax.annotation.Nonnull String nom) {
    this.nom = nom;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubsistemaInfo subsistemaInfo = (SubsistemaInfo) o;
    return Objects.equals(this.codi, subsistemaInfo.codi) &&
        Objects.equals(this.nom, subsistemaInfo.nom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubsistemaInfo {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

