/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.monitoring.DiaSetmanaEnum;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Desglossament temporal associat als registres d&#39;estadística
 */
@JsonPropertyOrder({
  Temps.JSON_PROPERTY_DATA,
  Temps.JSON_PROPERTY_ANUALITAT,
  Temps.JSON_PROPERTY_TRIMESTRE,
  Temps.JSON_PROPERTY_MES,
  Temps.JSON_PROPERTY_SETMANA,
  Temps.JSON_PROPERTY_DIA_SETMANA,
  Temps.JSON_PROPERTY_DIA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Temps {
  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nonnull
  private OffsetDateTime data;

  public static final String JSON_PROPERTY_ANUALITAT = "anualitat";
  @javax.annotation.Nullable
  private Integer anualitat;

  public static final String JSON_PROPERTY_TRIMESTRE = "trimestre";
  @javax.annotation.Nullable
  private Integer trimestre;

  public static final String JSON_PROPERTY_MES = "mes";
  @javax.annotation.Nullable
  private Integer mes;

  public static final String JSON_PROPERTY_SETMANA = "setmana";
  @javax.annotation.Nullable
  private Integer setmana;

  public static final String JSON_PROPERTY_DIA_SETMANA = "diaSetmana";
  @javax.annotation.Nullable
  private DiaSetmanaEnum diaSetmana;

  public static final String JSON_PROPERTY_DIA = "dia";
  @javax.annotation.Nullable
  private Integer dia;

  public Temps() {
  }

  public Temps data(@javax.annotation.Nonnull OffsetDateTime data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@javax.annotation.Nonnull OffsetDateTime data) {
    this.data = data;
  }

  public Temps anualitat(@javax.annotation.Nullable Integer anualitat) {
    
    this.anualitat = anualitat;
    return this;
  }

  /**
   * Any corresponent a la data
   * @return anualitat
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ANUALITAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAnualitat() {
    return anualitat;
  }


  @JsonProperty(value = JSON_PROPERTY_ANUALITAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnualitat(@javax.annotation.Nullable Integer anualitat) {
    this.anualitat = anualitat;
  }

  public Temps trimestre(@javax.annotation.Nullable Integer trimestre) {
    
    this.trimestre = trimestre;
    return this;
  }

  /**
   * Trimestre (1-4) derivat de la data
   * @return trimestre
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRIMESTRE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getTrimestre() {
    return trimestre;
  }


  @JsonProperty(value = JSON_PROPERTY_TRIMESTRE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrimestre(@javax.annotation.Nullable Integer trimestre) {
    this.trimestre = trimestre;
  }

  public Temps mes(@javax.annotation.Nullable Integer mes) {
    
    this.mes = mes;
    return this;
  }

  /**
   * Mes (1-12) derivat de la data
   * @return mes
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getMes() {
    return mes;
  }


  @JsonProperty(value = JSON_PROPERTY_MES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMes(@javax.annotation.Nullable Integer mes) {
    this.mes = mes;
  }

  public Temps setmana(@javax.annotation.Nullable Integer setmana) {
    
    this.setmana = setmana;
    return this;
  }

  /**
   * Setmana de l&#39;any derivada de la data
   * @return setmana
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SETMANA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSetmana() {
    return setmana;
  }


  @JsonProperty(value = JSON_PROPERTY_SETMANA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSetmana(@javax.annotation.Nullable Integer setmana) {
    this.setmana = setmana;
  }

  public Temps diaSetmana(@javax.annotation.Nullable DiaSetmanaEnum diaSetmana) {
    
    this.diaSetmana = diaSetmana;
    return this;
  }

  /**
   * Get diaSetmana
   * @return diaSetmana
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIA_SETMANA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DiaSetmanaEnum getDiaSetmana() {
    return diaSetmana;
  }


  @JsonProperty(value = JSON_PROPERTY_DIA_SETMANA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDiaSetmana(@javax.annotation.Nullable DiaSetmanaEnum diaSetmana) {
    this.diaSetmana = diaSetmana;
  }

  public Temps dia(@javax.annotation.Nullable Integer dia) {
    
    this.dia = dia;
    return this;
  }

  /**
   * Dia del mes
   * @return dia
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDia() {
    return dia;
  }


  @JsonProperty(value = JSON_PROPERTY_DIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDia(@javax.annotation.Nullable Integer dia) {
    this.dia = dia;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Temps temps = (Temps) o;
    return Objects.equals(this.data, temps.data) &&
        Objects.equals(this.anualitat, temps.anualitat) &&
        Objects.equals(this.trimestre, temps.trimestre) &&
        Objects.equals(this.mes, temps.mes) &&
        Objects.equals(this.setmana, temps.setmana) &&
        Objects.equals(this.diaSetmana, temps.diaSetmana) &&
        Objects.equals(this.dia, temps.dia);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, anualitat, trimestre, mes, setmana, diaSetmana, dia);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Temps {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    anualitat: ").append(toIndentedString(anualitat)).append("\n");
    sb.append("    trimestre: ").append(toIndentedString(trimestre)).append("\n");
    sb.append("    mes: ").append(toIndentedString(mes)).append("\n");
    sb.append("    setmana: ").append(toIndentedString(setmana)).append("\n");
    sb.append("    diaSetmana: ").append(toIndentedString(diaSetmana)).append("\n");
    sb.append("    dia: ").append(toIndentedString(dia)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

