/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AvisPageLink
 */
@JsonPropertyOrder({
  AvisPageLink.JSON_PROPERTY_REL,
  AvisPageLink.JSON_PROPERTY_HREF
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AvisPageLink {
  public static final String JSON_PROPERTY_REL = "rel";
  @javax.annotation.Nullable
  private String rel;

  public static final String JSON_PROPERTY_HREF = "href";
  @javax.annotation.Nullable
  private String href;

  public AvisPageLink() {
  }

  public AvisPageLink rel(@javax.annotation.Nullable String rel) {
    
    this.rel = rel;
    return this;
  }

  /**
   * Relació de l&#39;enllaç
   * @return rel
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRel() {
    return rel;
  }


  @JsonProperty(value = JSON_PROPERTY_REL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRel(@javax.annotation.Nullable String rel) {
    this.rel = rel;
  }

  public AvisPageLink href(@javax.annotation.Nullable String href) {
    
    this.href = href;
    return this;
  }

  /**
   * URL de l&#39;enllaç
   * @return href
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HREF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHref() {
    return href;
  }


  @JsonProperty(value = JSON_PROPERTY_HREF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHref(@javax.annotation.Nullable String href) {
    this.href = href;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvisPageLink avisPageLink = (AvisPageLink) o;
    return Objects.equals(this.rel, avisPageLink.rel) &&
        Objects.equals(this.href, avisPageLink.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rel, href);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvisPageLink {\n");
    sb.append("    rel: ").append(toIndentedString(rel)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

