/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.management.Avis;
import es.caib.comanda.model.management.AvisPageLink;
import es.caib.comanda.model.management.PageMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AvisPage
 */
@JsonPropertyOrder({
  AvisPage.JSON_PROPERTY_CONTENT,
  AvisPage.JSON_PROPERTY_PAGE,
  AvisPage.JSON_PROPERTY_LINKS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AvisPage {
  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private List<Avis> content = new ArrayList<>();

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private PageMetadata page;

  public static final String JSON_PROPERTY_LINKS = "links";
  @javax.annotation.Nullable
  private List<AvisPageLink> links = new ArrayList<>();

  public AvisPage() {
  }

  public AvisPage content(@javax.annotation.Nullable List<Avis> content) {
    
    this.content = content;
    return this;
  }

  public AvisPage addContentItem(Avis contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

  /**
   * Contingut de la pàgina
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Avis> getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable List<Avis> content) {
    this.content = content;
  }

  public AvisPage page(@javax.annotation.Nullable PageMetadata page) {
    
    this.page = page;
    return this;
  }

  /**
   * Get page
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PageMetadata getPage() {
    return page;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable PageMetadata page) {
    this.page = page;
  }

  public AvisPage links(@javax.annotation.Nullable List<AvisPageLink> links) {
    
    this.links = links;
    return this;
  }

  public AvisPage addLinksItem(AvisPageLink linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

  /**
   * Enllaços HATEOAS
   * @return links
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AvisPageLink> getLinks() {
    return links;
  }


  @JsonProperty(value = JSON_PROPERTY_LINKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinks(@javax.annotation.Nullable List<AvisPageLink> links) {
    this.links = links;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AvisPage avisPage = (AvisPage) o;
    return Objects.equals(this.content, avisPage.content) &&
        Objects.equals(this.page, avisPage.page) &&
        Objects.equals(this.links, avisPage.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, page, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AvisPage {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

