/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.management.InetAddressHolder;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InetAddress
 */
@JsonPropertyOrder({
  InetAddress.JSON_PROPERTY_HOLDER,
  InetAddress.JSON_PROPERTY_CANONICAL_HOST_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class InetAddress {
  public static final String JSON_PROPERTY_HOLDER = "holder";
  @javax.annotation.Nullable
  private InetAddressHolder holder;

  public static final String JSON_PROPERTY_CANONICAL_HOST_NAME = "canonicalHostName";
  @javax.annotation.Nullable
  private String canonicalHostName;

  public InetAddress() {
  }

  public InetAddress holder(@javax.annotation.Nullable InetAddressHolder holder) {
    
    this.holder = holder;
    return this;
  }

  /**
   * Get holder
   * @return holder
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOLDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InetAddressHolder getHolder() {
    return holder;
  }


  @JsonProperty(value = JSON_PROPERTY_HOLDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHolder(@javax.annotation.Nullable InetAddressHolder holder) {
    this.holder = holder;
  }

  public InetAddress canonicalHostName(@javax.annotation.Nullable String canonicalHostName) {
    
    this.canonicalHostName = canonicalHostName;
    return this;
  }

  /**
   * Get canonicalHostName
   * @return canonicalHostName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CANONICAL_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCanonicalHostName() {
    return canonicalHostName;
  }


  @JsonProperty(value = JSON_PROPERTY_CANONICAL_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCanonicalHostName(@javax.annotation.Nullable String canonicalHostName) {
    this.canonicalHostName = canonicalHostName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InetAddress inetAddress = (InetAddress) o;
    return Objects.equals(this.holder, inetAddress.holder) &&
        Objects.equals(this.canonicalHostName, inetAddress.canonicalHostName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(holder, canonicalHostName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InetAddress {\n");
    sb.append("    holder: ").append(toIndentedString(holder)).append("\n");
    sb.append("    canonicalHostName: ").append(toIndentedString(canonicalHostName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

