/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InetAddressHolder
 */
@JsonPropertyOrder({
  InetAddressHolder.JSON_PROPERTY_ORIGINAL_HOST_NAME,
  InetAddressHolder.JSON_PROPERTY_HOST_NAME,
  InetAddressHolder.JSON_PROPERTY_ADDRESS,
  InetAddressHolder.JSON_PROPERTY_FAMILY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class InetAddressHolder {
  public static final String JSON_PROPERTY_ORIGINAL_HOST_NAME = "originalHostName";
  @javax.annotation.Nullable
  private String originalHostName;

  public static final String JSON_PROPERTY_HOST_NAME = "hostName";
  @javax.annotation.Nullable
  private String hostName;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private Integer address;

  public static final String JSON_PROPERTY_FAMILY = "family";
  @javax.annotation.Nullable
  private Integer family;

  public InetAddressHolder() {
  }

  public InetAddressHolder originalHostName(@javax.annotation.Nullable String originalHostName) {
    
    this.originalHostName = originalHostName;
    return this;
  }

  /**
   * Get originalHostName
   * @return originalHostName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOriginalHostName() {
    return originalHostName;
  }


  @JsonProperty(value = JSON_PROPERTY_ORIGINAL_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOriginalHostName(@javax.annotation.Nullable String originalHostName) {
    this.originalHostName = originalHostName;
  }

  public InetAddressHolder hostName(@javax.annotation.Nullable String hostName) {
    
    this.hostName = hostName;
    return this;
  }

  /**
   * Get hostName
   * @return hostName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHostName() {
    return hostName;
  }


  @JsonProperty(value = JSON_PROPERTY_HOST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHostName(@javax.annotation.Nullable String hostName) {
    this.hostName = hostName;
  }

  public InetAddressHolder address(@javax.annotation.Nullable Integer address) {
    
    this.address = address;
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAddress() {
    return address;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable Integer address) {
    this.address = address;
  }

  public InetAddressHolder family(@javax.annotation.Nullable Integer family) {
    
    this.family = family;
    return this;
  }

  /**
   * Get family
   * @return family
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FAMILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFamily() {
    return family;
  }


  @JsonProperty(value = JSON_PROPERTY_FAMILY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFamily(@javax.annotation.Nullable Integer family) {
    this.family = family;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InetAddressHolder inetAddressHolder = (InetAddressHolder) o;
    return Objects.equals(this.originalHostName, inetAddressHolder.originalHostName) &&
        Objects.equals(this.hostName, inetAddressHolder.hostName) &&
        Objects.equals(this.address, inetAddressHolder.address) &&
        Objects.equals(this.family, inetAddressHolder.family);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalHostName, hostName, address, family);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InetAddressHolder {\n");
    sb.append("    originalHostName: ").append(toIndentedString(originalHostName)).append("\n");
    sb.append("    hostName: ").append(toIndentedString(hostName)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    family: ").append(toIndentedString(family)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

