/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.management.Objecte;
import es.caib.comanda.model.management.Usuari;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Sol·licitud de permisos per a un usuari o grup sobre un objecte
 */
@JsonPropertyOrder({
  Permis.JSON_PROPERTY_APP_CODI,
  Permis.JSON_PROPERTY_ENTORN_CODI,
  Permis.JSON_PROPERTY_USUARI,
  Permis.JSON_PROPERTY_GRUP,
  Permis.JSON_PROPERTY_PERMISOS,
  Permis.JSON_PROPERTY_OBJECTE,
  Permis.JSON_PROPERTY_OBJECTES_HEREUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Permis {
  public static final String JSON_PROPERTY_APP_CODI = "appCodi";
  @javax.annotation.Nullable
  private String appCodi;

  public static final String JSON_PROPERTY_ENTORN_CODI = "entornCodi";
  @javax.annotation.Nullable
  private String entornCodi;

  public static final String JSON_PROPERTY_USUARI = "usuari";
  @javax.annotation.Nullable
  private Usuari usuari;

  public static final String JSON_PROPERTY_GRUP = "grup";
  @javax.annotation.Nullable
  private String grup;

  public static final String JSON_PROPERTY_PERMISOS = "permisos";
  @javax.annotation.Nullable
  private List<String> permisos = new ArrayList<>();

  public static final String JSON_PROPERTY_OBJECTE = "objecte";
  @javax.annotation.Nullable
  private Objecte objecte;

  public static final String JSON_PROPERTY_OBJECTES_HEREUS = "objectesHereus";
  @javax.annotation.Nullable
  private List<Objecte> objectesHereus = new ArrayList<>();

  public Permis() {
  }

  public Permis appCodi(@javax.annotation.Nullable String appCodi) {
    
    this.appCodi = appCodi;
    return this;
  }

  /**
   * Codi de l&#39;aplicació que sol·licita el permís
   * @return appCodi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppCodi() {
    return appCodi;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppCodi(@javax.annotation.Nullable String appCodi) {
    this.appCodi = appCodi;
  }

  public Permis entornCodi(@javax.annotation.Nullable String entornCodi) {
    
    this.entornCodi = entornCodi;
    return this;
  }

  /**
   * Codi de l&#39;entorn de l&#39;aplicació
   * @return entornCodi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTORN_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntornCodi() {
    return entornCodi;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTORN_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntornCodi(@javax.annotation.Nullable String entornCodi) {
    this.entornCodi = entornCodi;
  }

  public Permis usuari(@javax.annotation.Nullable Usuari usuari) {
    
    this.usuari = usuari;
    return this;
  }

  /**
   * Get usuari
   * @return usuari
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USUARI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Usuari getUsuari() {
    return usuari;
  }


  @JsonProperty(value = JSON_PROPERTY_USUARI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsuari(@javax.annotation.Nullable Usuari usuari) {
    this.usuari = usuari;
  }

  public Permis grup(@javax.annotation.Nullable String grup) {
    
    this.grup = grup;
    return this;
  }

  /**
   * Grup al qual s&#39;aplica el permís
   * @return grup
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrup() {
    return grup;
  }


  @JsonProperty(value = JSON_PROPERTY_GRUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrup(@javax.annotation.Nullable String grup) {
    this.grup = grup;
  }

  public Permis permisos(@javax.annotation.Nullable List<String> permisos) {
    
    this.permisos = permisos;
    return this;
  }

  public Permis addPermisosItem(String permisosItem) {
    if (this.permisos == null) {
      this.permisos = new ArrayList<>();
    }
    this.permisos.add(permisosItem);
    return this;
  }

  /**
   * Llista de permisos sol·licitats
   * @return permisos
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISOS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getPermisos() {
    return permisos;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISOS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermisos(@javax.annotation.Nullable List<String> permisos) {
    this.permisos = permisos;
  }

  public Permis objecte(@javax.annotation.Nullable Objecte objecte) {
    
    this.objecte = objecte;
    return this;
  }

  /**
   * Get objecte
   * @return objecte
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Objecte getObjecte() {
    return objecte;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECTE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjecte(@javax.annotation.Nullable Objecte objecte) {
    this.objecte = objecte;
  }

  public Permis objectesHereus(@javax.annotation.Nullable List<Objecte> objectesHereus) {
    
    this.objectesHereus = objectesHereus;
    return this;
  }

  public Permis addObjectesHereusItem(Objecte objectesHereusItem) {
    if (this.objectesHereus == null) {
      this.objectesHereus = new ArrayList<>();
    }
    this.objectesHereus.add(objectesHereusItem);
    return this;
  }

  /**
   * Objectes hereus als quals també s&#39;apliquen els permisos
   * @return objectesHereus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OBJECTES_HEREUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Objecte> getObjectesHereus() {
    return objectesHereus;
  }


  @JsonProperty(value = JSON_PROPERTY_OBJECTES_HEREUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setObjectesHereus(@javax.annotation.Nullable List<Objecte> objectesHereus) {
    this.objectesHereus = objectesHereus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Permis permis = (Permis) o;
    return Objects.equals(this.appCodi, permis.appCodi) &&
        Objects.equals(this.entornCodi, permis.entornCodi) &&
        Objects.equals(this.usuari, permis.usuari) &&
        Objects.equals(this.grup, permis.grup) &&
        Objects.equals(this.permisos, permis.permisos) &&
        Objects.equals(this.objecte, permis.objecte) &&
        Objects.equals(this.objectesHereus, permis.objectesHereus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appCodi, entornCodi, usuari, grup, permisos, objecte, objectesHereus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Permis {\n");
    sb.append("    appCodi: ").append(toIndentedString(appCodi)).append("\n");
    sb.append("    entornCodi: ").append(toIndentedString(entornCodi)).append("\n");
    sb.append("    usuari: ").append(toIndentedString(usuari)).append("\n");
    sb.append("    grup: ").append(toIndentedString(grup)).append("\n");
    sb.append("    permisos: ").append(toIndentedString(permisos)).append("\n");
    sb.append("    objecte: ").append(toIndentedString(objecte)).append("\n");
    sb.append("    objectesHereus: ").append(toIndentedString(objectesHereus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

