/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Dades bàsiques d&#39;un usuari
 */
@JsonPropertyOrder({
  Usuari.JSON_PROPERTY_CODI,
  Usuari.JSON_PROPERTY_NOM,
  Usuari.JSON_PROPERTY_NIF,
  Usuari.JSON_PROPERTY_EMAIL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Usuari {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nullable
  private String codi;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nullable
  private String nom;

  public static final String JSON_PROPERTY_NIF = "nif";
  @javax.annotation.Nullable
  private String nif;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private String email;

  public Usuari() {
  }

  public Usuari codi(@javax.annotation.Nullable String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi únic de l&#39;usuari
   * @return codi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodi(@javax.annotation.Nullable String codi) {
    this.codi = codi;
  }

  public Usuari nom(@javax.annotation.Nullable String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Nom complet de l&#39;usuari
   * @return nom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(value = JSON_PROPERTY_NOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(@javax.annotation.Nullable String nom) {
    this.nom = nom;
  }

  public Usuari nif(@javax.annotation.Nullable String nif) {
    
    this.nif = nif;
    return this;
  }

  /**
   * NIF/NIE de l&#39;usuari
   * @return nif
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NIF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNif() {
    return nif;
  }


  @JsonProperty(value = JSON_PROPERTY_NIF, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNif(@javax.annotation.Nullable String nif) {
    this.nif = nif;
  }

  public Usuari email(@javax.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Correu electrònic
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable String email) {
    this.email = email;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Usuari usuari = (Usuari) o;
    return Objects.equals(this.codi, usuari.codi) &&
        Objects.equals(this.nom, usuari.nom) &&
        Objects.equals(this.nif, usuari.nif) &&
        Objects.equals(this.email, usuari.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom, nif, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Usuari {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    nif: ").append(toIndentedString(nif)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

