/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.v1.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Dimensio
 */
@JsonPropertyOrder({
  Dimensio.JSON_PROPERTY_CODI,
  Dimensio.JSON_PROPERTY_VALOR
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Dimensio {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nullable
  private String codi;

  public static final String JSON_PROPERTY_VALOR = "valor";
  @javax.annotation.Nullable
  private String valor;

  public Dimensio() {
  }

  public Dimensio codi(@javax.annotation.Nullable String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Get codi
   * @return codi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodi(@javax.annotation.Nullable String codi) {
    this.codi = codi;
  }

  public Dimensio valor(@javax.annotation.Nullable String valor) {
    
    this.valor = valor;
    return this;
  }

  /**
   * Get valor
   * @return valor
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValor() {
    return valor;
  }


  @JsonProperty(value = JSON_PROPERTY_VALOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValor(@javax.annotation.Nullable String valor) {
    this.valor = valor;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dimensio dimensio = (Dimensio) o;
    return Objects.equals(this.codi, dimensio.codi) &&
        Objects.equals(this.valor, dimensio.valor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, valor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dimensio {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    valor: ").append(toIndentedString(valor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

