/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.v1.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.v1.monitoring.Format;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Descripció d&#39;un indicador/mesura disponible
 */
@JsonPropertyOrder({
  IndicadorDesc.JSON_PROPERTY_CODI,
  IndicadorDesc.JSON_PROPERTY_NOM,
  IndicadorDesc.JSON_PROPERTY_DESCRIPCIO,
  IndicadorDesc.JSON_PROPERTY_FORMAT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class IndicadorDesc {
  public static final String JSON_PROPERTY_CODI = "codi";
  @javax.annotation.Nonnull
  private String codi;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nonnull
  private String nom;

  public static final String JSON_PROPERTY_DESCRIPCIO = "descripcio";
  @javax.annotation.Nullable
  private String descripcio;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nullable
  private Format format;

  public IndicadorDesc() {
  }

  public IndicadorDesc codi(@javax.annotation.Nonnull String codi) {
    
    this.codi = codi;
    return this;
  }

  /**
   * Codi de l&#39;indicador
   * @return codi
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCodi() {
    return codi;
  }


  @JsonProperty(value = JSON_PROPERTY_CODI, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodi(@javax.annotation.Nonnull String codi) {
    this.codi = codi;
  }

  public IndicadorDesc nom(@javax.annotation.Nonnull String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Nom de l&#39;indicador
   * @return nom
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(value = JSON_PROPERTY_NOM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNom(@javax.annotation.Nonnull String nom) {
    this.nom = nom;
  }

  public IndicadorDesc descripcio(@javax.annotation.Nullable String descripcio) {
    
    this.descripcio = descripcio;
    return this;
  }

  /**
   * Descripció funcional de l&#39;indicador
   * @return descripcio
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescripcio() {
    return descripcio;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescripcio(@javax.annotation.Nullable String descripcio) {
    this.descripcio = descripcio;
  }

  public IndicadorDesc format(@javax.annotation.Nullable Format format) {
    
    this.format = format;
    return this;
  }

  /**
   * Get format
   * @return format
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Format getFormat() {
    return format;
  }


  @JsonProperty(value = JSON_PROPERTY_FORMAT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@javax.annotation.Nullable Format format) {
    this.format = format;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndicadorDesc indicadorDesc = (IndicadorDesc) o;
    return Objects.equals(this.codi, indicadorDesc.codi) &&
        Objects.equals(this.nom, indicadorDesc.nom) &&
        Objects.equals(this.descripcio, indicadorDesc.descripcio) &&
        Objects.equals(this.format, indicadorDesc.format);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codi, nom, descripcio, format);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndicadorDesc {\n");
    sb.append("    codi: ").append(toIndentedString(codi)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

