/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.v1.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Informació resum de l&#39;estat del sistema on s&#39;executa l&#39;aplicació
 */
@JsonPropertyOrder({
  InformacioSistema.JSON_PROPERTY_PROCESSADORS,
  InformacioSistema.JSON_PROPERTY_CARREGA_SISTEMA,
  InformacioSistema.JSON_PROPERTY_CPU_SISTEMA,
  InformacioSistema.JSON_PROPERTY_MEMORIA_TOTAL,
  InformacioSistema.JSON_PROPERTY_MEMORIA_DISPONIBLE,
  InformacioSistema.JSON_PROPERTY_ESPAI_DISC_TOTAL,
  InformacioSistema.JSON_PROPERTY_ESPAI_DISC_LLIURE,
  InformacioSistema.JSON_PROPERTY_SISTEMA_OPERATIU,
  InformacioSistema.JSON_PROPERTY_DATA_ARRENCADA,
  InformacioSistema.JSON_PROPERTY_TEMPS_FUNCIONANT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class InformacioSistema {
  public static final String JSON_PROPERTY_PROCESSADORS = "processadors";
  @javax.annotation.Nullable
  private Integer processadors;

  public static final String JSON_PROPERTY_CARREGA_SISTEMA = "carregaSistema";
  @javax.annotation.Nullable
  private String carregaSistema;

  public static final String JSON_PROPERTY_CPU_SISTEMA = "cpuSistema";
  @javax.annotation.Nullable
  private String cpuSistema;

  public static final String JSON_PROPERTY_MEMORIA_TOTAL = "memoriaTotal";
  @javax.annotation.Nullable
  private String memoriaTotal;

  public static final String JSON_PROPERTY_MEMORIA_DISPONIBLE = "memoriaDisponible";
  @javax.annotation.Nullable
  private String memoriaDisponible;

  public static final String JSON_PROPERTY_ESPAI_DISC_TOTAL = "espaiDiscTotal";
  @javax.annotation.Nullable
  private String espaiDiscTotal;

  public static final String JSON_PROPERTY_ESPAI_DISC_LLIURE = "espaiDiscLliure";
  @javax.annotation.Nullable
  private String espaiDiscLliure;

  public static final String JSON_PROPERTY_SISTEMA_OPERATIU = "sistemaOperatiu";
  @javax.annotation.Nullable
  private String sistemaOperatiu;

  public static final String JSON_PROPERTY_DATA_ARRENCADA = "dataArrencada";
  @javax.annotation.Nullable
  private String dataArrencada;

  public static final String JSON_PROPERTY_TEMPS_FUNCIONANT = "tempsFuncionant";
  @javax.annotation.Nullable
  private String tempsFuncionant;

  public InformacioSistema() {
  }

  public InformacioSistema processadors(@javax.annotation.Nullable Integer processadors) {
    
    this.processadors = processadors;
    return this;
  }

  /**
   * Nombre de processadors disponibles
   * @return processadors
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROCESSADORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getProcessadors() {
    return processadors;
  }


  @JsonProperty(value = JSON_PROPERTY_PROCESSADORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProcessadors(@javax.annotation.Nullable Integer processadors) {
    this.processadors = processadors;
  }

  public InformacioSistema carregaSistema(@javax.annotation.Nullable String carregaSistema) {
    
    this.carregaSistema = carregaSistema;
    return this;
  }

  /**
   * Càrrega actual del sistema
   * @return carregaSistema
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CARREGA_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCarregaSistema() {
    return carregaSistema;
  }


  @JsonProperty(value = JSON_PROPERTY_CARREGA_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCarregaSistema(@javax.annotation.Nullable String carregaSistema) {
    this.carregaSistema = carregaSistema;
  }

  public InformacioSistema cpuSistema(@javax.annotation.Nullable String cpuSistema) {
    
    this.cpuSistema = cpuSistema;
    return this;
  }

  /**
   * Percentatge d&#39;ús de CPU del sistema
   * @return cpuSistema
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CPU_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCpuSistema() {
    return cpuSistema;
  }


  @JsonProperty(value = JSON_PROPERTY_CPU_SISTEMA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCpuSistema(@javax.annotation.Nullable String cpuSistema) {
    this.cpuSistema = cpuSistema;
  }

  public InformacioSistema memoriaTotal(@javax.annotation.Nullable String memoriaTotal) {
    
    this.memoriaTotal = memoriaTotal;
    return this;
  }

  /**
   * Memòria total del sistema
   * @return memoriaTotal
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMORIA_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemoriaTotal() {
    return memoriaTotal;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORIA_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemoriaTotal(@javax.annotation.Nullable String memoriaTotal) {
    this.memoriaTotal = memoriaTotal;
  }

  public InformacioSistema memoriaDisponible(@javax.annotation.Nullable String memoriaDisponible) {
    
    this.memoriaDisponible = memoriaDisponible;
    return this;
  }

  /**
   * Memòria disponible del sistema
   * @return memoriaDisponible
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MEMORIA_DISPONIBLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMemoriaDisponible() {
    return memoriaDisponible;
  }


  @JsonProperty(value = JSON_PROPERTY_MEMORIA_DISPONIBLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMemoriaDisponible(@javax.annotation.Nullable String memoriaDisponible) {
    this.memoriaDisponible = memoriaDisponible;
  }

  public InformacioSistema espaiDiscTotal(@javax.annotation.Nullable String espaiDiscTotal) {
    
    this.espaiDiscTotal = espaiDiscTotal;
    return this;
  }

  /**
   * Espai total del disc
   * @return espaiDiscTotal
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ESPAI_DISC_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEspaiDiscTotal() {
    return espaiDiscTotal;
  }


  @JsonProperty(value = JSON_PROPERTY_ESPAI_DISC_TOTAL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEspaiDiscTotal(@javax.annotation.Nullable String espaiDiscTotal) {
    this.espaiDiscTotal = espaiDiscTotal;
  }

  public InformacioSistema espaiDiscLliure(@javax.annotation.Nullable String espaiDiscLliure) {
    
    this.espaiDiscLliure = espaiDiscLliure;
    return this;
  }

  /**
   * Espai lliure del disc
   * @return espaiDiscLliure
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ESPAI_DISC_LLIURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEspaiDiscLliure() {
    return espaiDiscLliure;
  }


  @JsonProperty(value = JSON_PROPERTY_ESPAI_DISC_LLIURE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEspaiDiscLliure(@javax.annotation.Nullable String espaiDiscLliure) {
    this.espaiDiscLliure = espaiDiscLliure;
  }

  public InformacioSistema sistemaOperatiu(@javax.annotation.Nullable String sistemaOperatiu) {
    
    this.sistemaOperatiu = sistemaOperatiu;
    return this;
  }

  /**
   * Sistema operatiu
   * @return sistemaOperatiu
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SISTEMA_OPERATIU, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSistemaOperatiu() {
    return sistemaOperatiu;
  }


  @JsonProperty(value = JSON_PROPERTY_SISTEMA_OPERATIU, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSistemaOperatiu(@javax.annotation.Nullable String sistemaOperatiu) {
    this.sistemaOperatiu = sistemaOperatiu;
  }

  public InformacioSistema dataArrencada(@javax.annotation.Nullable String dataArrencada) {
    
    this.dataArrencada = dataArrencada;
    return this;
  }

  /**
   * Data d&#39;arrencada del sistema
   * @return dataArrencada
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_ARRENCADA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDataArrencada() {
    return dataArrencada;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_ARRENCADA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataArrencada(@javax.annotation.Nullable String dataArrencada) {
    this.dataArrencada = dataArrencada;
  }

  public InformacioSistema tempsFuncionant(@javax.annotation.Nullable String tempsFuncionant) {
    
    this.tempsFuncionant = tempsFuncionant;
    return this;
  }

  /**
   * Temps de funcionament del sistema
   * @return tempsFuncionant
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TEMPS_FUNCIONANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTempsFuncionant() {
    return tempsFuncionant;
  }


  @JsonProperty(value = JSON_PROPERTY_TEMPS_FUNCIONANT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTempsFuncionant(@javax.annotation.Nullable String tempsFuncionant) {
    this.tempsFuncionant = tempsFuncionant;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InformacioSistema informacioSistema = (InformacioSistema) o;
    return Objects.equals(this.processadors, informacioSistema.processadors) &&
        Objects.equals(this.carregaSistema, informacioSistema.carregaSistema) &&
        Objects.equals(this.cpuSistema, informacioSistema.cpuSistema) &&
        Objects.equals(this.memoriaTotal, informacioSistema.memoriaTotal) &&
        Objects.equals(this.memoriaDisponible, informacioSistema.memoriaDisponible) &&
        Objects.equals(this.espaiDiscTotal, informacioSistema.espaiDiscTotal) &&
        Objects.equals(this.espaiDiscLliure, informacioSistema.espaiDiscLliure) &&
        Objects.equals(this.sistemaOperatiu, informacioSistema.sistemaOperatiu) &&
        Objects.equals(this.dataArrencada, informacioSistema.dataArrencada) &&
        Objects.equals(this.tempsFuncionant, informacioSistema.tempsFuncionant);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processadors, carregaSistema, cpuSistema, memoriaTotal, memoriaDisponible, espaiDiscTotal, espaiDiscLliure, sistemaOperatiu, dataArrencada, tempsFuncionant);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InformacioSistema {\n");
    sb.append("    processadors: ").append(toIndentedString(processadors)).append("\n");
    sb.append("    carregaSistema: ").append(toIndentedString(carregaSistema)).append("\n");
    sb.append("    cpuSistema: ").append(toIndentedString(cpuSistema)).append("\n");
    sb.append("    memoriaTotal: ").append(toIndentedString(memoriaTotal)).append("\n");
    sb.append("    memoriaDisponible: ").append(toIndentedString(memoriaDisponible)).append("\n");
    sb.append("    espaiDiscTotal: ").append(toIndentedString(espaiDiscTotal)).append("\n");
    sb.append("    espaiDiscLliure: ").append(toIndentedString(espaiDiscLliure)).append("\n");
    sb.append("    sistemaOperatiu: ").append(toIndentedString(sistemaOperatiu)).append("\n");
    sb.append("    dataArrencada: ").append(toIndentedString(dataArrencada)).append("\n");
    sb.append("    tempsFuncionant: ").append(toIndentedString(tempsFuncionant)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

