/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.v1.monitoring;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.v1.monitoring.Dimensio;
import es.caib.comanda.model.v1.monitoring.Fet;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Registre d&#39;estadística amb dimensions i fets associats
 */
@JsonPropertyOrder({
  RegistreEstadistic.JSON_PROPERTY_DIMENSIONS,
  RegistreEstadistic.JSON_PROPERTY_FETS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class RegistreEstadistic {
  public static final String JSON_PROPERTY_DIMENSIONS = "dimensions";
  @javax.annotation.Nullable
  private List<Dimensio> dimensions = new ArrayList<>();

  public static final String JSON_PROPERTY_FETS = "fets";
  @javax.annotation.Nullable
  private List<Fet> fets = new ArrayList<>();

  public RegistreEstadistic() {
  }

  public RegistreEstadistic dimensions(@javax.annotation.Nullable List<Dimensio> dimensions) {
    
    this.dimensions = dimensions;
    return this;
  }

  public RegistreEstadistic addDimensionsItem(Dimensio dimensionsItem) {
    if (this.dimensions == null) {
      this.dimensions = new ArrayList<>();
    }
    this.dimensions.add(dimensionsItem);
    return this;
  }

  /**
   * Dimensions que qualifiquen el registre (p. ex. àrea, tipus, canal)
   * @return dimensions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIMENSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Dimensio> getDimensions() {
    return dimensions;
  }


  @JsonProperty(value = JSON_PROPERTY_DIMENSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDimensions(@javax.annotation.Nullable List<Dimensio> dimensions) {
    this.dimensions = dimensions;
  }

  public RegistreEstadistic fets(@javax.annotation.Nullable List<Fet> fets) {
    
    this.fets = fets;
    return this;
  }

  public RegistreEstadistic addFetsItem(Fet fetsItem) {
    if (this.fets == null) {
      this.fets = new ArrayList<>();
    }
    this.fets.add(fetsItem);
    return this;
  }

  /**
   * Fets o mesures quantitatives associades al registre
   * @return fets
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Fet> getFets() {
    return fets;
  }


  @JsonProperty(value = JSON_PROPERTY_FETS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFets(@javax.annotation.Nullable List<Fet> fets) {
    this.fets = fets;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistreEstadistic registreEstadistic = (RegistreEstadistic) o;
    return Objects.equals(this.dimensions, registreEstadistic.dimensions) &&
        Objects.equals(this.fets, registreEstadistic.fets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensions, fets);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistreEstadistic {\n");
    sb.append("    dimensions: ").append(toIndentedString(dimensions)).append("\n");
    sb.append("    fets: ").append(toIndentedString(fets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

