/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.api.v1.log;

import es.caib.comanda.service.v1.log.ApiException;
import es.caib.comanda.model.v1.log.FitxerContingut;
import es.caib.comanda.model.v1.log.FitxerInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComandaAppLogsApi
 */
class ComandaAppLogsApiTest {

    private final ComandaAppLogsApi api = new ComandaAppLogsApi();

    /**
     * Obtenir contingut complet d&#39;un fitxer de log
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void getFitxerByNomTest() throws ApiException {
        //
        //String nomFitxer = null;
        //
        //FitxerContingut response = api.getFitxerByNom(nomFitxer);

        // TODO: test validations
    }
    /**
     * Llegir les darreres N línies d&#39;un fitxer de log
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void llegitUltimesLiniesTest() throws ApiException {
        //
        //String nomFitxer = null;
        //
        //Long nLinies = null;
        //
        //List<String> response = api.llegitUltimesLinies(nomFitxer, nLinies);

        // TODO: test validations
    }
    /**
     * Llistat de fitxers de log disponibles
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void llistarFitxersTest() throws ApiException {
        //
        //List<FitxerInfo> response = api.llistarFitxers();

        // TODO: test validations
    }
}
