ALTER TABLE CMD_EST_WIDGET ADD (
    PRESET_PERIODE VARCHAR2(32 CHAR),
    PRESET_COUNT NUMBER(19)
);

-- Camps per mode RELATIVE
ALTER TABLE CMD_EST_WIDGET ADD (
    RELATIU_PUNT_REFERENCIA VARCHAR2(32 CHAR),
    RELATIU_COUNT NUMBER(19),
    RELATIU_UNITAT VARCHAR2(32 CHAR),
    RELATIU_ALINEACIO VARCHAR2(32 CHAR)
);

-- Camps per mode ABSOLUT
ALTER TABLE CMD_EST_WIDGET ADD (
    ABSOLUT_TIPUS VARCHAR2(32 CHAR),
    ABSOLUT_DATA_INICI TIMESTAMP,
    ABSOLUT_DATA_FI TIMESTAMP,
    ABSOLUT_ANY_REFERENCIA VARCHAR2(32 CHAR),
    ABSOLUT_ANY_VALOR NUMBER(19),
    ABSOLUT_PERIODE_UNITAT VARCHAR2(32 CHAR),
    ABSOLUT_PERIODE_INICI NUMBER(19),
    ABSOLUT_PERIODE_FI NUMBER(19)
);

ALTER TABLE CMD_EST_WIDGET DROP (
    INICI_UNITAT,
    INICI,
    DURACIO_UNITAT,
    DURACIO
);