/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.service.management.auth;

import es.caib.comanda.service.management.Pair;

import java.util.List;
import java.util.Map;

public class HttpBearerAuth implements Authentication {
  public interface BearerTokenSupplier {
    String get();
  }

  private final String scheme;
  private BearerTokenSupplier tokenSupplier;

  public HttpBearerAuth(String scheme) {
    this.scheme = upperCaseBearer(scheme);
  }

  /**
   * Gets the token, which together with the scheme, will be sent as the value of the Authorization header.
   *
   * @return The bearer token
   */
  public String getBearerToken() {
    return tokenSupplier.get();
  }

  /**
   * Sets the token, which together with the scheme, will be sent as the value of the Authorization header.
   *
   * @param bearerToken The bearer token to send in the Authorization header
   */
  public void setBearerToken(String bearerToken) {
    final String token = bearerToken;
    this.tokenSupplier = new BearerTokenSupplier() {
      @Override
      public String get() {
        return token;
      }
    };
  }

  /**
   * Sets the supplier of tokens, which together with the scheme, will be sent as the value of the Authorization header.
   *
   * @param tokenSupplier The supplier of bearer tokens to send in the Authorization header
   */
  public void setBearerToken(BearerTokenSupplier tokenSupplier) {
    this.tokenSupplier = tokenSupplier;
  }

  @Override
  public void applyToParams(List<Pair> queryParams, Map<String, String> headerParams, Map<String, String> cookieParams) {
    String bearerToken = tokenSupplier != null ? tokenSupplier.get() : null;
    if (bearerToken == null) {
      return;
    }
    headerParams.put("Authorization", (scheme != null ? scheme + " " : "") + bearerToken);
  }

  private static String upperCaseBearer(String scheme) {
    return "bearer".equalsIgnoreCase(scheme) ? "Bearer" : scheme;
  }
}
