-- Afegir camp data_inici_recuperacio per a gestionar el procés de recuperació de les alarmes
ALTER TABLE com_alarma
    ADD data_inici_recuperacio TIMESTAMP;

-- Afagir les columnas 'inactiu_desde' i 'inactiu_fins' (TIME) a la configuració d'alarmes per definir franjes horaries de inactivitat
ALTER TABLE com_alarma_config
    ADD inactiu_desde DATE;
ALTER TABLE com_alarma_config
    ADD inactiu_fins DATE;

-- Afegir les columnes 'parametre_auth', 'nom_usuari_auth' i 'contrasenya_auth' a l'entorn aplicació per definir l'usuari d'autenticació
ALTER TABLE com_entorn_app
    ADD parametre_auth NUMBER(1) DEFAULT 0 NOT NULL;
ALTER TABLE com_entorn_app
    ADD nom_usuari_auth VARCHAR2(255 CHAR);
ALTER TABLE com_entorn_app
    ADD contrasenya_auth VARCHAR2(255 CHAR);

-- Crear taula d'històric de canvis externs d'entorn d'aplicació
CREATE TABLE com_entorn_app_hist
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    versio        VARCHAR2(10 CHAR) NOT NULL,
    revisio       VARCHAR2(64) NOT NULL,
    canvi_versio  NUMBER(1) NOT NULL,
    data          TIMESTAMP NOT NULL,
    CONSTRAINT com_entornapphist_pk PRIMARY KEY (id)
);

ALTER TABLE com_entorn_app_hist
    ADD CONSTRAINT com_entorn_app_hist_fk FOREIGN KEY (entorn_app_id) REFERENCES com_entorn_app (id) ON DELETE CASCADE;

CREATE INDEX com_entornapphist_dat_i ON com_entorn_app_hist (data);

-- Afegir columna de so d'alarma
ALTER TABLE com_usuari
    ADD alarma VARCHAR2(16 CHAR);

-- Afegir columnes per al seguiment de la darrera sessió de l'usuari
ALTER TABLE com_usuari
    ADD inici_darrer_periode TIMESTAMP;
ALTER TABLE com_usuari
    ADD fi_darrer_periode TIMESTAMP;
ALTER TABLE com_usuari
    ADD inici_periode_actual TIMESTAMP;
ALTER TABLE com_usuari
    ADD darrera_activitat TIMESTAMP;

