
-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_001.yaml::plugin-uo-dir3-1::Limit
CREATE TABLE com_unitat_org (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(64 CHAR) NOT NULL, denominacio_es VARCHAR2(255 CHAR) NOT NULL, denominacio_ca VARCHAR2(255 CHAR) NOT NULL, nif_cif VARCHAR2(16 CHAR) NOT NULL, codi_unitat_superior VARCHAR2(64 CHAR) NOT NULL, codi_unitat_arrel VARCHAR2(64 CHAR) NOT NULL, estat VARCHAR2(1 CHAR) NOT NULL, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_unitat_org_pk PRIMARY KEY (id));

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_001.yaml::plugin-uo-dir3-3::Limit
ALTER TABLE com_est_dimensio ADD tipus VARCHAR2(16 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_001.yaml::plugin-uo-dir3-4::Limit
ALTER TABLE com_unitat_org ADD codi_conselleria VARCHAR2(64 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_002.yaml::est-dashboard-titol-personalitzat-0.1.4-001::limit
-- Afegir camp personalitzat per títols de dashboard
ALTER TABLE com_est_dashboard_titol ADD personalitzat NUMBER(1) DEFAULT 0;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_003.yaml::entitat-1::Limit
CREATE TABLE com_entitat (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(64 CHAR) NOT NULL, nom VARCHAR2(255 CHAR) NOT NULL, codi_dir3 VARCHAR2(64 CHAR) NOT NULL, CONSTRAINT com_entitat_pk PRIMARY KEY (id));

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_004.yaml::est-dashboard-filtre-0.1.4-001::limit
-- Crear taula de filtres de capçalera de dashboard (dimensió o període, aplicats a tots els widgets)
CREATE TABLE com_est_dashboard_filtre (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, dashboard_id NUMBER(38, 0) NOT NULL, tipus VARCHAR2(16 CHAR) NOT NULL, dimensio_codi VARCHAR2(32 CHAR), titol VARCHAR2(64 CHAR), ordre INTEGER NOT NULL, multiple NUMBER(1) DEFAULT 1 NOT NULL, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_dboard_filtre_pk PRIMARY KEY (id));

ALTER TABLE com_est_dashboard_filtre ADD CONSTRAINT com_dboard_filtre_dboard_fk FOREIGN KEY (dashboard_id) REFERENCES com_est_dashboard (id);

CREATE INDEX com_dboard_filtre_dboard_idx ON com_est_dashboard_filtre(dashboard_id);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_005.yaml::est-entitat-valor-tipus-0.1.4-001::limit
-- Indicar, per dimensió de tipus ENTITAT, si el valor és el codi intern o el codiDir3 de l'entitat
ALTER TABLE com_est_dimensio ADD entitat_valor_tipus VARCHAR2(16 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_005.yaml::est-dimensio-valor-entitat-mapejada-0.1.4-001::limit
-- Sobreescriptura manual de l'entitat corresponent a un valor de dimensió (quan no coincideix amb cap codi/codiDir3)
ALTER TABLE com_est_dimensio_valor ADD entitat_mapejada_id NUMBER(38, 0);

ALTER TABLE com_est_dimensio_valor ADD CONSTRAINT com_dim_valor_entitat_fk FOREIGN KEY (entitat_mapejada_id) REFERENCES com_entitat (id);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_006.yaml::est-entitat-camps-opcionals-0.1.4-001::limit
-- Permetre codi/nom/codiDir3 buits a Entitat, ja que ara es pot crear automàticament a partir d'un valor de dimensió desconegut coneixent només el camp corresponent al tipus de relació configurat a la dimensió (codi, codiDir3 o nom); la resta de camps els completa un administrador més tard.
ALTER TABLE com_entitat MODIFY codi NULL;

ALTER TABLE com_entitat MODIFY nom NULL;

ALTER TABLE com_entitat MODIFY codi_dir3 NULL;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_007.yaml::est-entitat-cif-0.1.4-001::limit
-- Afegir el CIF de l'entitat, per poder-lo mostrar/editar i com a nou camp de relació de dimensions ENTITAT
ALTER TABLE com_entitat ADD cif VARCHAR2(16 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_008.yaml::est-unitat-org-arrel-index-0.1.4-001::limit
-- Índex sobre codi_unitat_arrel: la pantalla d'organigrama d'entitats consulta totes les unitats d'un arbre (findByCodiUnitatArrel / filtre codiUnitatArrel) i sense índex feia un full scan de tota la taula.
CREATE INDEX com_unitat_org_arrel_idx ON com_unitat_org(codi_unitat_arrel);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_009.yaml::est-dashboard-titol-vores-costat-0.1.4-001::limit
-- Afegir configuració independent dels 4 costats de la vora (mostrar/color/gruix) i de la posició i separació del subtítol respecte del títol, pels components de tipus títol dels dashboards.
ALTER TABLE com_est_dashboard_titol ADD posicio_subtitol VARCHAR2(32 CHAR) DEFAULT 'SOTA';

ALTER TABLE com_est_dashboard_titol ADD separacio_subtitol INTEGER DEFAULT 0;

ALTER TABLE com_est_dashboard_titol ADD mostrar_vora_top NUMBER(1) DEFAULT 0;

ALTER TABLE com_est_dashboard_titol ADD color_vora_top VARCHAR2(8 CHAR);

ALTER TABLE com_est_dashboard_titol ADD ample_vora_top INTEGER DEFAULT 1;

ALTER TABLE com_est_dashboard_titol ADD mostrar_vora_right NUMBER(1) DEFAULT 0;

ALTER TABLE com_est_dashboard_titol ADD color_vora_right VARCHAR2(8 CHAR);

ALTER TABLE com_est_dashboard_titol ADD ample_vora_right INTEGER DEFAULT 1;

ALTER TABLE com_est_dashboard_titol ADD mostrar_vora_bottom NUMBER(1) DEFAULT 1;

ALTER TABLE com_est_dashboard_titol ADD color_vora_bottom VARCHAR2(8 CHAR);

ALTER TABLE com_est_dashboard_titol ADD ample_vora_bottom INTEGER DEFAULT 1;

ALTER TABLE com_est_dashboard_titol ADD mostrar_vora_left NUMBER(1) DEFAULT 0;

ALTER TABLE com_est_dashboard_titol ADD color_vora_left VARCHAR2(8 CHAR);

ALTER TABLE com_est_dashboard_titol ADD ample_vora_left INTEGER DEFAULT 1;
