
-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_009.yaml::est-dashboard-titol-vores-costat-0.1.4-003::limit
-- Eliminar les columnes de vora única, substituïdes pels 4 costats independents.
ALTER TABLE com_est_dashboard_titol DROP COLUMN mostrar_vora;

ALTER TABLE com_est_dashboard_titol DROP COLUMN color_vora;

ALTER TABLE com_est_dashboard_titol DROP COLUMN ample_vora;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_010.yaml::est-dashboard-color-fons-0.1.4-001::limit
-- Permetre configurar un color de fons pel dashboard, un per tema clar i un per tema fosc
ALTER TABLE com_est_dashboard ADD color_fons_clar VARCHAR2(8 CHAR);

ALTER TABLE com_est_dashboard ADD color_fons_fosc VARCHAR2(8 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_011.yaml::est-indicador-formula-0.1.4-001::limit
-- Afegir el tipus d'indicador (SIMPLE/FORMULA) i la taula de termes de fórmula, per permetre crear indicadors calculats com a suma/resta d'altres indicadors del mateix entornApp.
ALTER TABLE com_est_indicador ADD tipus VARCHAR2(16 CHAR) DEFAULT 'SIMPLE' NOT NULL;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_011.yaml::est-indicador-formula-0.1.4-002::limit
-- Crear la taula de termes de fórmula d'indicadors (suma/resta d'altres indicadors).
CREATE TABLE com_est_indicador_formula_terme (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, indicador_formula_id NUMBER(38, 0) NOT NULL, indicador_component_id NUMBER(38, 0) NOT NULL, operador VARCHAR2(16 CHAR) NOT NULL, ordre INTEGER NOT NULL, CONSTRAINT com_ind_formula_terme_pk PRIMARY KEY (id));

ALTER TABLE com_est_indicador_formula_terme ADD CONSTRAINT com_ind_formula_terme_formula_fk FOREIGN KEY (indicador_formula_id) REFERENCES com_est_indicador (id);

ALTER TABLE com_est_indicador_formula_terme ADD CONSTRAINT com_ind_formula_terme_component_fk FOREIGN KEY (indicador_component_id) REFERENCES com_est_indicador (id);

CREATE INDEX com_ind_formula_terme_formula_idx ON com_est_indicador_formula_terme(indicador_formula_id);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_012.yaml::est-taula-widget-opcions-0.1.4-001::limit
-- Afegir opcions de configuració als widgets de taula: amagar files amb tots els valors a zero, ordenar per una columna concreta i limitar el nombre de resultats retornats.
ALTER TABLE com_est_widget ADD amagar_files_zero NUMBER(1) DEFAULT 0 NOT NULL;

ALTER TABLE com_est_widget ADD columna_ordenacio INTEGER;

ALTER TABLE com_est_widget ADD direccio_ordenacio VARCHAR2(4 CHAR);

ALTER TABLE com_est_widget ADD limit_resultats INTEGER;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_013.yaml::est-gauge-dos-indicadors-rol-0.1.4-001::limit
-- Afegir la columna 'rol' a est_indicador_table per distingir, quan un widget gràfic de tipus GAUGE_CHART utilitza dos indicadors (DOS_INDICADORS), quina fila és l'indicador de valor (VALOR) i quina és l'indicador de màxim (MAXIM). Per a la resta de tipusDades aquesta columna es queda a null.
ALTER TABLE com_est_indicador_table ADD rol VARCHAR2(16 CHAR);

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_014.yaml::est-create-dashboard-preferit-table-0.1.4-001::limit
-- Creació de la taula per gestionar els dashboards preferits dels usuaris (relació codi Keycloak - dashboard)
CREATE TABLE com_est_dashboard_preferit (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, usuari_codi VARCHAR2(64) NOT NULL, est_dashboard_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_est_dashboard_preferit_pk PRIMARY KEY (id));

ALTER TABLE com_est_dashboard_preferit ADD CONSTRAINT com_est_dashboard_preferit_uk UNIQUE (usuari_codi, est_dashboard_id);

CREATE INDEX com_idx_dashboard_preferit_usuari_codi ON com_est_dashboard_preferit(usuari_codi);

ALTER TABLE com_est_dashboard_preferit ADD CONSTRAINT com_est_dashboard_preferit_dashboard_fk FOREIGN KEY (est_dashboard_id) REFERENCES com_est_dashboard (id) ON DELETE CASCADE;

-- Changeset db/changelog/changes/est/0.1.4/0.1.4_est_016.yaml::est-indicador-codi-uk-0.1.4-001::limit
-- Afegir restricció d'unicitat per a codi i entorn_app_id a la taula com_est_indicador
ALTER TABLE com_est_indicador ADD CONSTRAINT com_ind_codi_uk UNIQUE (codi, entorn_app_id);

-- Changeset db/changelog/changes/monitor/0.1.4/0.1.4_monitor_001.yaml::monitor-change-0.1.4-001::limit
-- Afegir app, entorn i indicador d'entornApp esborrat a la taula monitor per poder reintentar la neteja completa d'un entornApp esborrat
ALTER TABLE com_monitor ADD app_id NUMBER(38, 0);

ALTER TABLE com_monitor ADD entorn_id NUMBER(38, 0);

ALTER TABLE com_monitor ADD entorn_app_esborrat NUMBER(1) DEFAULT 0;

COMMENT ON COLUMN com_monitor.app_id IS 'Aplicació de l''entornApp (es conserva per si l''entornApp s''ha esborrat)';

COMMENT ON COLUMN com_monitor.entorn_id IS 'Entorn de l''entornApp (es conserva per si l''entornApp s''ha esborrat)';

COMMENT ON COLUMN com_monitor.entorn_app_esborrat IS 'Indica si l''operació de neteja correspon a un entornApp esborrat';

