-- Grant permissions
GRANT SELECT, UPDATE, INSERT, DELETE ON com_unitat_org TO WWW_COMANDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON com_entitat TO WWW_COMANDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON com_est_dashboard_filtre TO WWW_COMANDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON com_est_indicador_formula_terme TO WWW_COMANDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON com_est_dashboard_preferit TO WWW_COMANDA;
