-- Creació de taula: com_app_context
CREATE TABLE com_app_context (
     id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
     created_by       VARCHAR2(64 CHAR)    NOT NULL,
     created_date     TIMESTAMP            NOT NULL,
     lastmod_by       VARCHAR2(64 CHAR),
     lastmod_date     TIMESTAMP,
     v                NUMBER(19),
     codi             VARCHAR2(64 CHAR)    NOT NULL,
     nom              VARCHAR2(100 CHAR)   NOT NULL,
     path             VARCHAR2(255 CHAR)   NOT NULL,
     api              VARCHAR2(255 CHAR),
     actiu            NUMBER(1)            NOT NULL,
     entorn_app_id    NUMBER(19),
     CONSTRAINT com_app_context_pk PRIMARY KEY (id),
     CONSTRAINT com_app_context_actiu_ck CHECK (actiu IN (0,1))
);

-- Índex opcional per claus externes (millora de rendiment a FK)
CREATE INDEX com_app_context_entorn_fk_i ON com_app_context (entorn_app_id);

-- Única: (entorn_app_id, codi)
ALTER TABLE com_app_context ADD CONSTRAINT com_app_ctx_appcodi_uk UNIQUE (entorn_app_id, codi);

-- FK: com_app_context.entorn_app_id -> com_entorn_app.id
ALTER TABLE com_app_context ADD CONSTRAINT COM_APP_CTX_ENTORN_APP_FK FOREIGN KEY (entorn_app_id) REFERENCES com_entorn_app (id);

-----------------------------------------------------------------------

-- Creació de taula: com_app_ctx_manual
CREATE TABLE com_app_ctx_manual (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nom        VARCHAR2(128 CHAR)   NOT NULL,
    path       VARCHAR2(255 CHAR)   NOT NULL,
    app_ctx_id NUMBER(19)           NOT NULL,
    CONSTRAINT com_app_ctx_manual_pk PRIMARY KEY (id)
);

-- Índex opcional per claus externes (millora de rendiment a FK)
CREATE INDEX com_app_ctx_manual_app_fk_i ON com_app_ctx_manual (app_ctx_id);

-- FK: com_app_ctx_manual.app_ctx_id -> com_app_context.id
ALTER TABLE com_app_ctx_manual ADD CONSTRAINT com_manual_app_ctx_fk FOREIGN KEY (app_ctx_id) REFERENCES com_app_context (id);

-- Única: (app_ctx_id, nom)
ALTER TABLE com_app_ctx_manual ADD CONSTRAINT app_manual_appnom_uk UNIQUE (app_ctx_id, nom);

-----------------------------------------------------------------------

-- Afegir columnes a com_entorn_app
ALTER TABLE com_entorn_app ADD (jdk_version VARCHAR2(10 CHAR));
ALTER TABLE com_entorn_app ADD (revisio     VARCHAR2(64 CHAR));

-- Afegir columnes a la taula d'estadístiques del dashboard
ALTER TABLE com_est_dashboard ADD (app_id    NUMBER(19));
ALTER TABLE com_est_dashboard ADD (entorn_id NUMBER(19));

-----------------------------------------------------------------------

GRANT SELECT, UPDATE, INSERT, DELETE ON com_app_context TO WWW_COMANDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON com_app_ctx_manual TO WWW_COMANDA;
