-- =============================================
-- Module: comanda-ms-avisos
-- =============================================

CREATE TABLE com_avis
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    app_id        NUMBER(38, 0) NOT NULL,
    entorn_id     NUMBER(38, 0) NOT NULL,
    identificador VARCHAR2(64 CHAR) NOT NULL,
    tipus         VARCHAR2(16 CHAR) NOT NULL,
    nom           VARCHAR2(255 CHAR) NOT NULL,
    descripcio    VARCHAR2(1024 CHAR),
    data_inici    date,
    data_fi       date,
    created_by    VARCHAR2(64 CHAR) NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    lastmod_by    VARCHAR2(64 CHAR),
    lastmod_date  TIMESTAMP,
    v             NUMBER(38, 0),
    CONSTRAINT com_avis_pk PRIMARY KEY (id)
);

ALTER TABLE com_avis ADD CONSTRAINT com_avis_ident_uk UNIQUE (entorn_app_id, identificador);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_avis TO WWW_COMANDA;

-- =============================================
-- Module: comanda-ms-tasques
-- =============================================

CREATE TABLE com_tasca
(
    id             NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id  NUMBER(38, 0) NOT NULL,
    app_id         NUMBER(38, 0) NOT NULL,
    entorn_id      NUMBER(38, 0) NOT NULL,
    identificador  VARCHAR2(64 CHAR) NOT NULL,
    tipus          VARCHAR2(64 CHAR) NOT NULL,
    nom            VARCHAR2(255 CHAR) NOT NULL,
    descripcio     VARCHAR2(1024 CHAR),
    estat          VARCHAR2(16 CHAR) NOT NULL,
    estat_desc     VARCHAR2(1024 CHAR),
    prioritat      VARCHAR2(16 CHAR),
    data_inici     date,
    data_fi        date,
    data_caducitat date,
    url            VARCHAR2(255 CHAR) NOT NULL,
    responsable    VARCHAR2(128 CHAR),
    grup           VARCHAR2(128 CHAR),
    created_by     VARCHAR2(64 CHAR) NOT NULL,
    created_date   TIMESTAMP NOT NULL,
    lastmod_by     VARCHAR2(64 CHAR),
    lastmod_date   TIMESTAMP,
    v              NUMBER(38, 0),
    CONSTRAINT com_tasca_pk PRIMARY KEY (id)
);

ALTER TABLE com_tasca ADD CONSTRAINT com_tasca_ident_uk UNIQUE (entorn_app_id, identificador);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_tasca TO WWW_COMANDA;

CREATE TABLE com_tasca_usuari
(
    tasca_id NUMBER(38, 0) NOT NULL,
    usuari   VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT com_tasca_usuari_pk PRIMARY KEY (tasca_id)
);

ALTER TABLE com_tasca_usuari ADD CONSTRAINT com_tascausr_tasca_fk FOREIGN KEY (tasca_id) REFERENCES com_tasca (id);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_tasca_usuari TO WWW_COMANDA;

CREATE TABLE com_tasca_grup
(
    tasca_id NUMBER(38, 0) NOT NULL,
    grup     VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT com_tasca_grup_pk PRIMARY KEY (tasca_id)
);

ALTER TABLE com_tasca_grup ADD CONSTRAINT com_tascagrp_tasca_fk FOREIGN KEY (tasca_id) REFERENCES com_tasca (id);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_tasca_grup TO WWW_COMANDA;


-- =============================================
-- Module: comanda-ms-ususaris
-- =============================================

-- Changeset db/changelog/init/00_usuaris_init_table.yaml::usuaris-init-table-1::limit
CREATE TABLE com_usuari
(
    id           NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi         VARCHAR2(64 CHAR) NOT NULL,
    nom          VARCHAR2(255 CHAR) NOT NULL,
    nif          VARCHAR2(10 CHAR),
    email        VARCHAR2(255 CHAR),
    created_by   VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by   VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v            NUMBER(38, 0),
    CONSTRAINT com_usuari_pk PRIMARY KEY (id)
);

ALTER TABLE com_usuari ADD CONSTRAINT com_usuari_codi_uk UNIQUE (codi);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_usuari TO WWW_COMANDA;


-- =============================================
-- Module: comanda-ms-configuracio
-- =============================================

CREATE TABLE com_parametre
(
    id             NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    grup           VARCHAR2(128) NOT NULL,
    subgrup        VARCHAR2(128) NOT NULL,
    tipus          VARCHAR2(16) NOT NULL,
    codi           VARCHAR2(128) NOT NULL,
    nom            VARCHAR2(128) NOT NULL,
    nom_key        VARCHAR2(128),
    descripcio     VARCHAR2(1024),
    descripcio_key VARCHAR2(128),
    valor          VARCHAR2(255),
    editable       BOOLEAN,
    grup_key       VARCHAR2(128),
    subgrup_key    VARCHAR2(128),
    CONSTRAINT com_parametre_pk PRIMARY KEY (id)
);

ALTER TABLE com_parametre ADD CONSTRAINT com_parametre_codi_uk UNIQUE (codi);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_parametre TO WWW_COMANDA;

ALTER TABLE com_entorn_app DROP COLUMN info_interval;
ALTER TABLE com_entorn_app DROP COLUMN salut_interval;
ALTER TABLE com_entorn_app ADD compactable BOOLEAN DEFAULT 0 NOT NULL;
ALTER TABLE com_entorn_app ADD compactacio_setmanal INTEGER;
ALTER TABLE com_entorn_app ADD compactacio_mensual INTEGER;
ALTER TABLE com_entorn_app ADD eliminacio INTEGER;


-- =============================================
-- Module: comanda-ms-permisos
-- =============================================

CREATE TABLE com_objecte
(
    id            NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipus         VARCHAR2(64 CHAR) NOT NULL,
    nom           VARCHAR2(255 CHAR) NOT NULL,
    identificador VARCHAR2(64 CHAR) NOT NULL,
    CONSTRAINT com_objecte_pk PRIMARY KEY (id)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_objecte TO WWW_COMANDA;


CREATE TABLE com_acces
(
    id    NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    acces VARCHAR2(64 CHAR),
    CONSTRAINT com_acces_pk PRIMARY KEY (id)
);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_acces TO WWW_COMANDA;

CREATE TABLE com_permis
(
    id            NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    usuari        VARCHAR2(64 CHAR),
    grup          VARCHAR2(64 CHAR),
    objecte_id    NUMBER(38, 0) NOT NULL,
    created_by    VARCHAR2(64 CHAR) NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    lastmod_by    VARCHAR2(64 CHAR),
    lastmod_date  TIMESTAMP,
    v             NUMBER(38, 0),
    CONSTRAINT com_permis_pk PRIMARY KEY (id)
);

ALTER TABLE com_permis ADD CONSTRAINT com_permis_objecte_fk FOREIGN KEY (objecte_id) REFERENCES com_objecte (id);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_permis TO WWW_COMANDA;

CREATE TABLE com_permis_acces
(
    permis_id NUMBER(38, 0) NOT NULL,
    acces_id  NUMBER(38, 0) NOT NULL,
    CONSTRAINT com_permis_acces_pk PRIMARY KEY (permis_id, acces_id)
);

ALTER TABLE com_permis_acces ADD CONSTRAINT com_permisacces_permis_fk FOREIGN KEY (permis_id) REFERENCES com_permis (id);
ALTER TABLE com_permis_acces ADD CONSTRAINT com_permisacces_acces_fk FOREIGN KEY (acces_id) REFERENCES com_acces (id);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_permis_acces TO WWW_COMANDA;

CREATE TABLE com_permis_hereus
(
    permis_id NUMBER(38, 0) NOT NULL,
    hereu_id  NUMBER(38, 0) NOT NULL,
    CONSTRAINT com_permis_hereus_pk PRIMARY KEY (permis_id, hereu_id)
);

ALTER TABLE com_permis_hereus ADD CONSTRAINT com_permishereus_permis_fk FOREIGN KEY (permis_id) REFERENCES com_permis (id);
ALTER TABLE com_permis_hereus ADD CONSTRAINT com_permishereus_objecte_fk FOREIGN KEY (hereu_id) REFERENCES com_objecte (id);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_permis_hereus TO WWW_COMANDA;



-- =============================================
-- Module: comanda-ms-salut
-- =============================================

-- Changeset db/changelog/changes/0.1.0/30.yaml::salut-change-30-1::Limit
ALTER TABLE com_salut ADD tipus_registre VARCHAR2(10 CHAR) DEFAULT 'MINUT' NOT NULL;
ALTER TABLE com_salut ADD app_count_up INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_warn INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_degraded INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_down INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_error INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_maintenance INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_count_unknown INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_up INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_warn INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_degraded INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_down INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_error INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_maintenance INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD bd_count_unknown INTEGER DEFAULT 0;
ALTER TABLE com_salut ADD app_latencia_mitjana INTEGER;
ALTER TABLE com_salut ADD app_latencia_num_elements INTEGER;
ALTER TABLE com_salut ADD bd_latencia_mitjana INTEGER;
ALTER TABLE com_salut ADD bd_latencia_num_elements INTEGER;
ALTER TABLE com_salut ADD data_app TIMESTAMP;
ALTER TABLE com_salut ADD num_elements INTEGER;

ALTER TABLE com_salut_integracio ADD count_up INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_warn INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_degraded INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_down INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_error INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_maintenance INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD count_unknown INTEGER DEFAULT 0;
ALTER TABLE com_salut_integracio ADD estat_num_elements INTEGER;
ALTER TABLE com_salut_integracio ADD latencia_mitjana INTEGER;
ALTER TABLE com_salut_integracio ADD latencia_num_elements INTEGER;

ALTER TABLE com_salut_subsistema ADD count_up INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_warn INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_degraded INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_down INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_error INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_maintenance INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD count_unknown INTEGER DEFAULT 0;
ALTER TABLE com_salut_subsistema ADD estat_num_elements INTEGER;
ALTER TABLE com_salut_subsistema ADD latencia_mitjana INTEGER;
ALTER TABLE com_salut_subsistema ADD latencia_num_elements INTEGER;

CREATE INDEX com_salut_tipus_registre_id ON com_salut(tipus_registre);
CREATE INDEX com_salut_entorn_data_id ON com_salut(entorn_app_id, data);


-- =============================================
-- Module: comanda-ms-estadistica
-- =============================================

ALTER TABLE com_est_dimensio_valor ADD agrupable BOOLEAN DEFAULT 0 NOT NULL;
ALTER TABLE com_est_dimensio_valor ADD valor_agrupacio VARCHAR2(255 CHAR);

ALTER TABLE com_est_indicador ADD compactable BOOLEAN DEFAULT 1 NOT NULL;
ALTER TABLE com_est_indicador ADD tipus_compactacio VARCHAR2(64 CHAR) DEFAULT 'SUMA';
ALTER TABLE com_est_indicador ADD compactacio_indicador_id NUMBER(38, 0);
ALTER TABLE com_est_indicador ADD CONSTRAINT com_ind_compactacio_fk FOREIGN KEY (compactacio_indicador_id) REFERENCES com_est_indicador (id);

ALTER TABLE com_est_fet ADD tipus VARCHAR2(64 CHAR) DEFAULT 'DIARI' NOT NULL;
ALTER TABLE com_est_fet ADD num_dies INTEGER DEFAULT 1 NOT NULL;

ALTER TABLE com_est_temps ADD CONSTRAINT com_est_data_unq UNIQUE (data);

CREATE INDEX com_est_dim_valor_dim_agr_idx ON com_est_dimensio_valor(dimensio_id, agrupable);
CREATE INDEX com_est_dim_entorn_idx ON com_est_dimensio(entorn_app_id);
