import * as React from 'react';
import { useTranslation } from 'react-i18next';
import { useParams } from 'react-router-dom';
import Grid from '@mui/material/Grid';
import Card from '@mui/material/Card';
import CardHeader from '@mui/material/CardHeader';
import CardContent from '@mui/material/CardContent';
import Checkbox from '@mui/material/Checkbox';
import Skeleton from '@mui/material/Skeleton';
import FormControlLabel from '@mui/material/FormControlLabel';
import TextField from '@mui/material/TextField';
import MenuItem from '@mui/material/MenuItem';
import Divider from '@mui/material/Divider';
import {
    GridPage,
    MuiDataGrid,
    MuiForm,
    MuiFilter,
    FormField,
    useFormApiRef,
    useResourceApiService,
    useBaseAppContext,
    useConfirmDialogButtons,
    useMuiDataGridApiRef,
    springFilterBuilder,
    MuiDataGridColDef,
    useCloseDialogButtons,
    MuiDialog,
    Toolbar,
    MuiFormProps,
    useFilterApiRef,
    MuiDataGridProps,
} from 'reactlib';
import { Box, Button, Icon, IconButton } from '@mui/material';
import { useIsUserAdmin, useUserContext } from '../components/UserContext';
import CenteredCircularProgress from '../components/CenteredCircularProgress.tsx';
import notNull from '../util/arrayUtils';
import { toToolbarIcon } from '../../lib/components/mui/ToolbarIcon';
import { useTreeDataWithoutSwitch } from '../hooks/treeData.tsx';
import {
    useGridApiRef,
    isAutogeneratedRow,
    gridRowSelector,
} from '@mui/x-data-grid-pro';
import useReordering from '../hooks/reordering.tsx';

type RuleScope = 'APLICACIO' | 'SUBSISTEMA' | 'INTEGRACIO' | 'SISTEMA';
type RuleMetric = 'ESTAT' | 'LATENCIA' | 'CARREGA_MITJANA_SISTEMA' | 'MEMORIA_DISPONIBLE' | 'ESPAI_DISC_LLIURE';
type RuleComparator = 'MAJOR' | 'MAJOR_IGUAL' | 'MENOR' | 'MENOR_IGUAL' | 'IGUAL' | 'DIFERENT' | 'EN';
type RuleOperator = 'AND' | 'OR';

type RuleCondition = {
    ambit: RuleScope;
    codiObjecte?: string;
    metrica: RuleMetric;
    comparador: RuleComparator;
    valorNumeric?: string;
    valorsText?: string[];
};

const STATUS_OPTIONS = ['UP', 'WARN', 'DEGRADED', 'DOWN', 'MAINTENANCE', 'UNKNOWN', 'ERROR'];

const defaultCondition = (): RuleCondition => ({
    ambit: 'APLICACIO',
    metrica: 'ESTAT',
    comparador: 'EN',
    valorsText: ['DOWN'],
});

const scopeMetricOptions = (scope: RuleScope): RuleMetric[] => {
    switch (scope) {
        case 'SISTEMA':
            return ['LATENCIA', 'CARREGA_MITJANA_SISTEMA', 'MEMORIA_DISPONIBLE', 'ESPAI_DISC_LLIURE'];
        case 'SUBSISTEMA':
        case 'INTEGRACIO':
        case 'APLICACIO':
        default:
            return ['ESTAT'];
    }
};

const comparatorOptions = (metric: RuleMetric): RuleComparator[] =>
    metric === 'ESTAT'
        ? ['EN', 'IGUAL', 'DIFERENT']
        : ['MAJOR', 'MAJOR_IGUAL', 'MENOR', 'MENOR_IGUAL', 'IGUAL', 'DIFERENT'];

const buildRulePayload = (operator: RuleOperator, conditions: RuleCondition[]) => ({
    tipusNode: 'GRUP',
    operador: operator,
    fills: conditions.map(condition => ({
        tipusNode: 'CONDICIO',
        ambit: condition.ambit,
        codiObjecte: condition.codiObjecte || undefined,
        metrica: condition.metrica,
        comparador: condition.comparador,
        valorNumeric: condition.metrica === 'ESTAT' || !condition.valorNumeric ? undefined : Number(condition.valorNumeric),
        valorsText: condition.metrica === 'ESTAT' ? (condition.valorsText ?? []) : [],
    })),
});

const parseRulePayload = (regla: any): { operator: RuleOperator; conditions: RuleCondition[] } => {
    if (!regla?.fills?.length) {
        return { operator: 'AND', conditions: [defaultCondition()] };
    }
    return {
        operator: regla.operador === 'OR' ? 'OR' : 'AND',
        conditions: regla.fills.map((fill: any) => ({
            ambit: fill.ambit ?? 'APLICACIO',
            codiObjecte: fill.codiObjecte,
            metrica: fill.metrica ?? 'ESTAT',
            comparador: fill.comparador ?? (fill.metrica === 'ESTAT' ? 'EN' : 'MAJOR'),
            valorNumeric: fill.valorNumeric != null ? String(fill.valorNumeric) : '',
            valorsText: Array.isArray(fill.valorsText) && fill.valorsText.length > 0 ? fill.valorsText : ['DOWN'],
        })),
    };
};

export const EntornAppSelector : React.FC<any> = (props) => {
    const { id, onEntornAppChange, validationErrors } = props;
    const formApiRef = useFormApiRef();
    const { isReady: apiIsReady, getOne: apiGetOne } = useResourceApiService('entornApp');
    const [entornApp, setEntornApp] = React.useState<any>();
    React.useEffect(() => {
        if (apiIsReady && id != null) {
            apiGetOne(id).then(value => {
                const entornApp = { id: value.id, description: value.entornAppDescription };
                setEntornApp(entornApp)
                formApiRef.current.setFieldValue('entornApp', entornApp);
            });
        }
    }, [apiIsReady, id]);
    return (!id || entornApp != null) ? <MuiFilter
        resourceName="entornApp"
        code="optional_entornApp_filter"
        commonFieldComponentProps={{ size: 'small' }}
        componentProps={{ sx: { mt: 0 } }}
        validationErrors={validationErrors}
        initialData={{ entornApp: entornApp }}
        springFilterBuilder={() => ''}
        onDataChange={data => onEntornAppChange(data?.entornApp)}
        formApiRef={formApiRef}>
            <FormField
            name="entornApp"
            filter={springFilterBuilder.and(
                springFilterBuilder.eq('activa', true),
                springFilterBuilder.eq('app.activa', true),
            )}
            advancedSearchColumns={[{
                field: 'entornAppDescription',
                flex: 1,
            }]} />
    </MuiFilter> : <Skeleton height={'100%'}/>;
}

export const AlarmaConfigForm: React.FC<{
    entornAppId?: number | string;
    dialogMode?: boolean;
    dialogModeOnGoBack?: () => void;
    id?: number | string,
}> = ({ id: idProp, entornAppId: entornAppIdProp, dialogMode, dialogModeOnGoBack }) => {
    const { t } = useTranslation();
    const { t: tLib } = useBaseAppContext();
    const { id: idFromPath } = useParams();
    const id = idProp ?? idFromPath;
    const formApiRef = useFormApiRef();
    const { isReady: entornAppApiReady, getOne: getEntornApp } = useResourceApiService('entornApp');
    const [entornAppId, setEntornAppId] = React.useState<any>();
    const [validationErrors, setValidationErrors] = React.useState<any>();
    const [periodeShow, setPeriodeShow] = React.useState<boolean>();
    const [ruleOperator, setRuleOperator] = React.useState<RuleOperator>('AND');
    const [conditions, setConditions] = React.useState<RuleCondition[]>([defaultCondition()]);
    const [ruleEditorInitialized, setRuleEditorInitialized] = React.useState(false);
    const [entornAppDetail, setEntornAppDetail] = React.useState<any>();
    const isCurrentUserAdmin = useIsUserAdmin();
    const handleDataChange = (data: any) => {
        setEntornAppId(data?.entornAppId);
        if (periodeShow === undefined) {
            const ps = data?.periodeValor != null || data?.periodeUnitat != null;
            setPeriodeShow(ps);
        }
        if (!ruleEditorInitialized) {
            const parsed = parseRulePayload(data?.regla);
            setRuleOperator(parsed.operator);
            setConditions(parsed.conditions);
            setRuleEditorInitialized(true);
        }
    }
    const handleValidationErrorsChange = (_id: any, validationErrors?: any[]) => {
        const entornAppValidationError = validationErrors?.find(e => e.field === 'entornAppId');
        setValidationErrors(entornAppValidationError ? [{
            field: 'entornApp',
            code: entornAppValidationError.code,
            message: entornAppValidationError.message,
        }] : null);
    }
    const handleEntornAppChange = (entornApp: any) => {
        formApiRef.current.setFieldValue('entornAppId', entornApp?.id);
    }
    const handlePeriodeShowChange = (event: any) => {
        const newValue = event.target.checked;
        setPeriodeShow(newValue);
        if (!newValue) {
            formApiRef.current?.setFieldValue('periodeValor', null);
            formApiRef.current?.setFieldValue('periodeUnitat', null);
        }
    }
    const syncRuleToForm = React.useCallback((nextOperator: RuleOperator, nextConditions: RuleCondition[]) => {
        formApiRef.current?.setFieldValue('regla', buildRulePayload(nextOperator, nextConditions));
        // formApiRef.current?.setFieldValue('tipus', null);
        formApiRef.current?.setFieldValue('condicio', null);
        formApiRef.current?.setFieldValue('valor', null);
    }, []);

    React.useEffect(() => {
        syncRuleToForm(ruleOperator, conditions);
    }, [conditions, ruleOperator, syncRuleToForm]);

    React.useEffect(() => {
        if (!entornAppApiReady || !entornAppId) {
            setEntornAppDetail(undefined);
            return;
        }
        getEntornApp(entornAppId).then(setEntornAppDetail);
    }, [entornAppApiReady, entornAppId, getEntornApp]);

    const subsystemOptions = React.useMemo(
        () => (entornAppDetail?.subsistemes ?? []).map((item: any) => item?.subsistema?.codi ?? item?.codi).filter(Boolean),
        [entornAppDetail]
    );
    const integrationOptions = React.useMemo(
        () => (entornAppDetail?.integracions ?? []).map((item: any) => item?.integracio?.codi ?? item?.codi).filter(Boolean),
        [entornAppDetail]
    );

    const updateCondition = (index: number, patch: Partial<RuleCondition>) => {
        setConditions(prev => prev.map((condition, currentIndex) => {
            if (currentIndex !== index) return condition;
            const next = { ...condition, ...patch };
            if (patch.ambit && patch.ambit !== condition.ambit) {
                const nextMetric = scopeMetricOptions(patch.ambit)[0];
                next.metrica = nextMetric;
                next.comparador = comparatorOptions(nextMetric)[0];
                next.codiObjecte = undefined;
                if (nextMetric === 'ESTAT') {
                    next.valorsText = next.valorsText?.length ? next.valorsText : ['DOWN'];
                    next.valorNumeric = '';
                } else {
                    next.valorsText = [];
                }
            }
            if (patch.metrica && patch.metrica !== condition.metrica) {
                next.comparador = comparatorOptions(patch.metrica)[0];
                if (patch.metrica === 'ESTAT') {
                    next.valorsText = next.valorsText?.length ? next.valorsText : ['DOWN'];
                    next.valorNumeric = '';
                } else {
                    next.valorsText = [];
                }
            }
            return next;
        }));
    };

    const addCondition = () => setConditions(prev => [...prev, defaultCondition()]);
    const removeCondition = (index: number) => setConditions(prev => prev.filter((_, currentIndex) => currentIndex !== index));

    // const {goBack} = useBaseAppContext();
    // const afterDelete = () => {
    //     goBack("/alarma")
    // }

    // const {apiIsReady, apiDelete, tLib} = useAlarmaConfigAction(afterDelete)
    // // const elementsWithPositions = React.useMemo(() => [
    // //     {
    // //         position: 3,
    // //         element: toToolbarIcon('delete', {
    // //             title: tLib('form.delete.title'),
    // //             onClick: () => apiDelete(id),
    // //         }),
    // //     }
    // // ], [apiIsReady, tLib]);

    const dialogModeProps: Partial<MuiFormProps> = dialogMode
        ? {
              hiddenToolbar: true,
              // Si estamos haciendo un update, no debemos setear initialData nunca.
              // Si lo hacemos, base-react no hará la petición getOne inicial
              initialData: id ? undefined : {
                  entornAppId: entornAppIdProp,
              },
              goBackLink: undefined,
              createLink: undefined,
              onCreateSuccess: dialogModeOnGoBack,
          }
        : {};

    return (
        <>
            {dialogMode && (
                <Toolbar
                    title={id ? t($ => $.page.alarmaConfig.update) : t($ => $.page.alarmaConfig.create)}
                    elementsWithPositions={[
                        {
                            position: 0,
                            element: toToolbarIcon('arrow_back', {
                                title: tLib('form.goBack.title'),
                                onClick: dialogModeOnGoBack,
                                sx: { mr: 1 },
                            }),
                        },
                        {
                            position: 2,
                            element: toToolbarIcon('save', {
                                title: tLib('form.create.title'),
                                onClick: () => {
                                    formApiRef.current?.save();
                                },
                            }),
                        },
                    ]}
                    upperToolbar
                    sx={{
                        mb: 2,
                    }}
                />
            )}
            <MuiForm
                id={id}
                title={id ? t($ => $.page.alarmaConfig.update) : t($ => $.page.alarmaConfig.create)}
                resourceName="alarmaConfig"
                goBackLink="/alarma"
                createLink="form/{{id}}"
                apiRef={formApiRef}
                onDataChange={handleDataChange}
                hiddenDeleteButton
                // toolbarElementsWithPositions={elementsWithPositions}
                onValidationErrorsChange={handleValidationErrorsChange}
                {...dialogModeProps}
            >
                <Grid container spacing={2}>
                    {!dialogMode &&
                        <Grid size={3}>
                            <EntornAppSelector
                                id={entornAppId}
                                onEntornAppChange={handleEntornAppChange}
                                validationErrors={validationErrors}
                            />
                        </Grid>
                    }
                    <Grid size={dialogMode ? 12 : 9}>
                        <FormField
                            name="nom"
                            componentProps={{ title: t($ => $.page.alarmaConfig.nomHelperText) }}
                        />
                    </Grid>
                    <Grid size={12}>
                        <Card variant="outlined">
                            <CardHeader
                                title={t($ => $.page.alarmaConfig.condicio.title)}
                                subheader={t($ => $.page.alarmaConfig.condicio.subtitle)}
                                slotProps={{
                                    title: { variant: 'h6' },
                                    subheader: { variant: 'subtitle2', sx: { color: 'text.secondary' } }
                                }}
                                sx={{ mb: -2 }} />
                            <CardContent>
                                <Grid container spacing={1}>
                                    <Grid size={12}>
                                        <TextField
                                            select
                                            fullWidth
                                            size="small"
                                            label="Lògica entre condicions"
                                            value={ruleOperator}
                                            onChange={event => setRuleOperator(event.target.value as RuleOperator)}
                                        >
                                            <MenuItem value="AND">AND</MenuItem>
                                            <MenuItem value="OR">OR</MenuItem>
                                        </TextField>
                                    </Grid>
                                    {conditions.map((condition, index) => {
                                        const metrics = scopeMetricOptions(condition.ambit);
                                        const comparators = comparatorOptions(condition.metrica);
                                        const codeOptions = condition.ambit === 'SUBSISTEMA' ? subsystemOptions : integrationOptions;
                                        const useCodeSelect = (condition.ambit === 'SUBSISTEMA' || condition.ambit === 'INTEGRACIO') && codeOptions.length > 0;
                                        return (
                                            <React.Fragment key={index}>
                                                {index > 0 && <Grid size={12}><Divider /></Grid>}
                                                <Grid size={{ xs: 12, md: 3 }}>
                                                    <TextField
                                                        select
                                                        fullWidth
                                                        size="small"
                                                        label="Tipus"
                                                        value={condition.ambit}
                                                        onChange={event => updateCondition(index, { ambit: event.target.value as RuleScope })}
                                                    >
                                                        <MenuItem value="APLICACIO">Aplicació</MenuItem>
                                                        <MenuItem value="SUBSISTEMA">Subsistema</MenuItem>
                                                        <MenuItem value="INTEGRACIO">Integració</MenuItem>
                                                        <MenuItem value="SISTEMA">Sistema</MenuItem>
                                                    </TextField>
                                                </Grid>
                                                {(condition.ambit === 'SUBSISTEMA' || condition.ambit === 'INTEGRACIO') && (
                                                    <Grid size={{ xs: 12, md: 3 }}>
                                                        <TextField
                                                            select={useCodeSelect}
                                                            fullWidth
                                                            size="small"
                                                            label="Codi"
                                                            value={condition.codiObjecte ?? ''}
                                                            onChange={event => updateCondition(index, { codiObjecte: event.target.value })}
                                                        >
                                                            {useCodeSelect && codeOptions.map((option: string) => (
                                                                <MenuItem key={option} value={option}>{option}</MenuItem>
                                                            ))}
                                                        </TextField>
                                                    </Grid>
                                                )}
                                                <Grid size={{ xs: 12, md: 3 }}>
                                                    <TextField
                                                        select
                                                        fullWidth
                                                        size="small"
                                                        label="Mètrica"
                                                        value={condition.metrica}
                                                        onChange={event => updateCondition(index, { metrica: event.target.value as RuleMetric })}
                                                    >
                                                        {metrics.map(metric => (
                                                            <MenuItem key={metric} value={metric}>
                                                                {metric === 'ESTAT' ? 'Estat' :
                                                                    metric === 'LATENCIA' ? 'Latència' :
                                                                    metric === 'CARREGA_MITJANA_SISTEMA' ? 'Càrrega mitjana del sistema' :
                                                                    metric === 'MEMORIA_DISPONIBLE' ? 'Memòria disponible (MB)' :
                                                                    'Espai de disc lliure (MB)'}
                                                            </MenuItem>
                                                        ))}
                                                    </TextField>
                                                </Grid>
                                                <Grid size={{ xs: 12, md: 3 }}>
                                                    <TextField
                                                        select
                                                        fullWidth
                                                        size="small"
                                                        label="Comparador"
                                                        value={condition.comparador}
                                                        onChange={event => updateCondition(index, { comparador: event.target.value as RuleComparator })}
                                                    >
                                                        {comparators.map(comparator => (
                                                            <MenuItem key={comparator} value={comparator}>{comparator}</MenuItem>
                                                        ))}
                                                    </TextField>
                                                </Grid>
                                                <Grid size={{ xs: 12, md: condition.metrica === 'ESTAT' ? 10 : 11 }}>
                                                    {condition.metrica === 'ESTAT' ? (
                                                        <TextField
                                                            select
                                                            fullWidth
                                                            size="small"
                                                            SelectProps={{ multiple: true }}
                                                            label="Estat"
                                                            value={condition.valorsText ?? []}
                                                            onChange={event => updateCondition(index, { valorsText: event.target.value as unknown as string[] })}
                                                        >
                                                            {STATUS_OPTIONS.map(status => (
                                                                <MenuItem key={status} value={status}>{status}</MenuItem>
                                                            ))}
                                                        </TextField>
                                                    ) : (
                                                        <TextField
                                                            fullWidth
                                                            size="small"
                                                            type="number"
                                                            label={condition.metrica === 'LATENCIA' ? 'Valor (ms)' : 'Valor'}
                                                            value={condition.valorNumeric ?? ''}
                                                            onChange={event => updateCondition(index, { valorNumeric: event.target.value })}
                                                        />
                                                    )}
                                                </Grid>
                                                <Grid size={{ xs: 12, md: 1 }}>
                                                    <Button
                                                        color="error"
                                                        onClick={() => removeCondition(index)}
                                                        disabled={conditions.length === 1}
                                                        fullWidth
                                                        sx={{ height: '100%' }}
                                                    >
                                                        <Icon>delete</Icon>
                                                    </Button>
                                                </Grid>
                                            </React.Fragment>
                                        );
                                    })}
                                    <Grid size={12}>
                                        <Button startIcon={<Icon>add</Icon>} onClick={addCondition}>
                                            Afegir condició
                                        </Button>
                                    </Grid>
                                </Grid>
                            </CardContent>
                        </Card>
                    </Grid>
                    <Grid size={12}>
                        <FormField name="missatge" />
                    </Grid>
                    <Grid size={6}>
                        <FormField name="notificacioFinalitzada" />
                    </Grid>
                    {isCurrentUserAdmin && (
                        <>
                            <Grid size={6}>
                                <FormField name="correuGeneric" />
                            </Grid>
                            <Grid size={6}>
                                <FormField name="admin" />
                            </Grid>
                        </>
                    )}
                    <Grid size={6}>
                        <FormControlLabel
                            control={<Checkbox size="small" checked={periodeShow ?? false} onChange={handlePeriodeShowChange}/>}
                            label={t($ => $.page.alarmaConfig.periode.switch)}
                            sx={{ ml: 1 }} />
                    </Grid>
                    {periodeShow && <Grid size={12}>
                        <Card variant="outlined">
                            <CardHeader
                                title={t($ => $.page.alarmaConfig.periode.title)}
                                subheader={t($ => $.page.alarmaConfig.periode.subtitle)}
                                slotProps={{
                                    title: { variant: 'h6' },
                                    subheader: { variant: 'subtitle2', sx: { color: 'text.secondary' } }
                                }}
                                sx={{ mb: -2 }} />
                            <CardContent>
                                <Grid container spacing={1}>
                                    <Grid size={3}>
                                        <FormField name="periodeValor" />
                                    </Grid>
                                    <Grid size={9}>
                                        <FormField name="periodeUnitat" />
                                    </Grid>
                                </Grid>
                            </CardContent>
                        </Card>
                    </Grid>}
                </Grid>
            </MuiForm>
        </>
    );
}

const useAlarmaConfigAction = (refresh?: () => void) => {
    const {
        isReady: apiIsReady,
        artifactAction,
    } = useResourceApiService("alarmaConfig")
    const {messageDialogShow, temporalMessageShow, t: tLib} = useBaseAppContext();
    const confirmDialogButtons = useConfirmDialogButtons();
    const confirmDialogComponentProps = {maxWidth: 'sm', fullWidth: true};

    const apiDelete = (id:any) => {
        messageDialogShow(
            tLib('datacommon.delete.single.label'),
            tLib('datacommon.delete.single.confirm'),
            confirmDialogButtons,
            confirmDialogComponentProps)
            .then((value: any) => {
                if (value) {
                    artifactAction(id, { code: 'delete_alarmaConfig' })
                        .then(() => {
                            refresh?.()
                            temporalMessageShow(null, tLib('datacommon.delete.single.success'), 'success');
                        })
                        .catch((error) => {
                            temporalMessageShow(tLib('datacommon.delete.single.error'), error?.message, 'error');
                        })
                }
            })
    }

    return {
        tLib,
        apiIsReady,
        apiDelete,
    }
}

type AlarmaConfigFilterProps = {
    onSpringFilterChange: (springFilter?: string) => void,
    entornApps?: any[],
    hideEntornAppField?: boolean,
};
const AlarmaConfigFilter = (props: AlarmaConfigFilterProps) => {
    const { onSpringFilterChange, entornApps, hideEntornAppField } = props;
    const { t } = useTranslation();
    const { user } = useUserContext();
    const isCurrentUserAdmin = useIsUserAdmin();
    const [moreFields, setMoreFields] = React.useState<boolean>(false);
    const filterApiRef = useFilterApiRef();
    const formApiRef = useFormApiRef();
    const netejar = () => {
        filterApiRef.current?.clear();
    };

    if (!user) {
        return null;
    }

    return (
        <MuiFilter
            apiRef={filterApiRef}
            resourceName="alarmaConfig"
            code="alarmaConfig_filter"
            detached
            formApiRef={formApiRef}
            commonFieldComponentProps={{ size: 'small' }}
            onSpringFilterChange={onSpringFilterChange}
            springFilterBuilder={data => {
                return springFilterBuilder.and(
                    data?.entornApp && springFilterBuilder.eq('entornAppId', data?.entornApp?.id ?? data?.entornApp),
                    data?.nom && springFilterBuilder.like('nom', data?.nom),
                    data?.correuGeneric && springFilterBuilder.eq('correuGeneric', data?.correuGeneric),
                ) || '';
            }}>
            <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                <Grid container spacing={1} sx={{ flexGrow: 1, mr: 1 }}>
                    {!hideEntornAppField && (
                        <Grid size={{ xs: 12, sm: 6 }}>
                            <FormField
                                name={'entornApp'}
                                type={'reference'}
                                label={t($ => $.page.alarmaConfig.filter.entornApp)}
                                required={false}
                                optionsRequest={(q: string) => {
                                    const opts = (entornApps ?? []).map((ea: any) => ({
                                        id: ea?.id,
                                        description: ea.entornAppDescription,
                                    }));
                                    const filtered = q
                                        ? opts.filter(o =>
                                            o.description?.toLowerCase().includes(q.toLowerCase())
                                        )
                                        : opts;
                                    return Promise.resolve({ options: filtered });
                                }}
                                componentProps={{ disabled: (entornApps ?? []).length === 0 }}
                            />
                        </Grid>
                    )}
                    <Grid size={{xs: 12, sm: hideEntornAppField ? 12 : 6}}><FormField name={'nom'} /></Grid>
                    {moreFields && <>
                        {isCurrentUserAdmin &&
                            (<Grid size={{xs: 6, sm:3}}><FormField name={'correuGeneric'} /></Grid>)}
                    </>}
                </Grid>
                <Box sx={{ display: 'flex', flexDirection: 'row' }}>
                    <IconButton onClick={netejar} title={t($ => $.components.clear)}>
                        <Icon>filter_alt_off</Icon>
                    </IconButton>
                    <IconButton
                        onClick={() => setMoreFields(mf => !mf)}
                        title={t($ => $.page.alarmaConfig.filter.more)}
                        color={moreFields ? 'primary' : 'default'}>
                        <Icon>filter_list</Icon>
                    </IconButton>
                </Box>
            </Box>
        </MuiFilter>
    );
};

export const AlarmaConfigDialog: React.FC<{
    open: boolean;
    setOpen: (open: boolean) => void;
    filterBy?: { entornAppId?: number | string };
}> = ({ open, setOpen, filterBy }) => {
    const [currentEditMode, setCurrentEditMode] = React.useState<false | "CREATE" | number>(false);
    const buttons = useCloseDialogButtons();

    const getDialogContent = () => {
        if (currentEditMode === false) {
            return (
                <AlarmaConfig
                    dialogMode
                    onAdd={() => setCurrentEditMode('CREATE')}
                    onEdit={id => setCurrentEditMode(id)}
                    filterBy={filterBy}
                />
            );
        }
        if (currentEditMode === "CREATE") {
            return (
                <AlarmaConfigForm
                    dialogMode
                    dialogModeOnGoBack={() => setCurrentEditMode(false)}
                    entornAppId={filterBy?.entornAppId}
                />
            );
        }
        return (
            <AlarmaConfigForm
                id={currentEditMode}
                dialogMode
                dialogModeOnGoBack={() => setCurrentEditMode(false)}
                entornAppId={filterBy?.entornAppId}
            />
        );
    }

    return (
        <MuiDialog
            open={open}
            buttonCallback={() => setOpen(false)}
            closeCallback={() => setOpen(false)}
            buttons={buttons}
            componentProps={{
                maxWidth: 'lg',
                fullWidth: true,
            }}
        >
            <Box
                sx={{
                    mt: 3,
                    height: '500px',
                }}
            >
                {getDialogContent()}
            </Box>
        </MuiDialog>
    );

};

const getTreeDataPath = (row: any) => ([row.entornAppId, row.id]);

const AlarmaConfig: React.FC<{
    filterBy?: { entornAppId?: number | string };
    dialogMode?: boolean;
    onEdit?: (id: any) => void;
    onAdd?: () => void;
}> = ({ filterBy, dialogMode, onEdit, onAdd }) => {
    const { t } = useTranslation();
    const apiRef = useMuiDataGridApiRef();
    const gridApiRef = useGridApiRef();
    const [userFilter, setUserFilter] = React.useState<string | undefined>();
    const reorderDisabledWarning = React.useMemo(
        () =>
            userFilter ? (
                <Icon
                    sx={{ ml: 1 }}
                    color="warning"
                    title={t($ => $.page.alarmaConfig.filterWarning)}
                >
                    warning
                </Icon>
            ) : (
                <></>
            ),
        [t, userFilter]
    );
    const disableTreeData = filterBy?.entornAppId != null || userFilter;
    const { dataGridProps: treeDataGridProps } = useTreeDataWithoutSwitch(
        getTreeDataPath,
        gridApiRef,
        undefined,
        1,
        undefined,
        !disableTreeData,
        {
            valueFormatter: (value, row) => {
                if (!isAutogeneratedRow(row)) return row.nom ?? "";
                if (value == null) return '';
                const entornApp = entornApps?.find(ea => ea.id === value);
                return entornApp?.entornAppDescription ?? '';
            },
        }
    );
    const { dataGridProps: baseReorderingDataGridProps, loadingElement } = useReordering("alarmaConfig");
    const reorderingDataGridProps: Partial<MuiDataGridProps> = !disableTreeData
        ? {
              ...baseReorderingDataGridProps,
              isRowReorderable: params => {
                  return params.rowNode.type === 'leaf';
              },
              isValidRowReorder: ({ apiRef, sourceNode, targetNode }) => {
                  if (targetNode.type !== 'leaf') return false;
                  const sourceRow = gridRowSelector(apiRef, sourceNode.id);
                  const targetRow = gridRowSelector(apiRef, targetNode.id);
                  return sourceRow.entornAppId === targetRow.entornAppId;
              },
          }
        : {};
    const [adminView, setAdminView] = React.useState<boolean>(false);
    const { user } = useUserContext();
    const isCurrentUserAdmin = useIsUserAdmin();
    const { isReady: apiIsReadyEntornApp, find: apiFindEntornApp } = useResourceApiService('entornApp');
    const [entornApps, setEntornApps] = React.useState<any[]>();
    const refresh = () => {
        apiRef.current?.refresh?.();
    }
    const {apiIsReady, apiDelete, tLib} = useAlarmaConfigAction(refresh);

    React.useEffect(() => {
        if (adminView && !isCurrentUserAdmin)
            setAdminView(false);
    }, [isCurrentUserAdmin, adminView])

    React.useEffect(() => {
        if (apiIsReadyEntornApp) {
            apiFindEntornApp({ unpaged: true }).then(response => {
                setEntornApps(response.rows);
            });
        }
    }, [apiIsReadyEntornApp]);

    const columns = React.useMemo(() => {
        if (!entornApps) return [];
        const baseColumns: (MuiDataGridColDef | null)[] = [
            disableTreeData
                ? {
                      field: 'entornAppId',
                      valueFormatter: (value?: number) => {
                          if (value == null) return '';
                          const entornApp = entornApps.find(ea => ea.id === value);
                          return entornApp?.entornAppDescription ?? '';
                      },
                      flex: 1,
                      headerAlign: 'left',
                      align: 'left',
                  }
                : null,
            disableTreeData
                ? {
                      field: 'nom',
                      flex: 1,
                  }
                : null,
            {
                field: 'resumRegla',
                flex: 3,
            },
        ];

        if (adminView) {
            baseColumns.push({
                field: 'tipusUsuariAlarma',
                flex: 1,
                sortable: false,
            });
        }

        return baseColumns.filter(notNull);
    }, [entornApps, disableTreeData, adminView]);

    const toolbarElementsWithPositions = React.useMemo(() => {
        return [
            {
                position: 1,
                element: reorderDisabledWarning
            },
            {
                position: 1,
                element: loadingElement,
            },
            isCurrentUserAdmin
                ? {
                      position: 2,
                      element: (
                          <Button
                              onClick={() => setAdminView(!adminView)}
                              variant={adminView ? 'contained' : 'outlined'}
                              title={
                                  adminView
                                      ? t($ => $.page.alarmaConfig.filter.showOnlyOwnDisabled)
                                      : t($ => $.page.alarmaConfig.filter.showOnlyOwnEnabled)
                              }
                              sx={{ mr: 2 }}
                          >
                              <Icon>{adminView ? 'admin_panel_settings' : 'account_circle'}</Icon>
                          </Button>
                      ),
                  }
                : null,
            dialogMode
                ? {
                      position: 2,
                      element: (
                          <IconButton
                              title={tLib('datacommon.create.label')}
                              onClick={onAdd}
                              size="small"
                          >
                              <Icon>add</Icon>
                          </IconButton>
                      ),
                  }
                : null,
        ].filter(notNull);
    }, [reorderDisabledWarning, loadingElement, isCurrentUserAdmin, adminView, t, dialogMode, tLib, onAdd]);
    const hideDeleteForRow = React.useCallback((row: any) => {
        if (isAutogeneratedRow(row)) return true;
        return !isCurrentUserAdmin && (row?.admin || row?.correuGeneric);
    }, [isCurrentUserAdmin]);

    const actions = React.useMemo(() => [
        dialogMode ? {
            label: tLib('datacommon.update.label'),
            icon: 'edit',
            onClick: (id: string | number) => {
                onEdit?.(id);
            },
            hidden: (row: any) => isAutogeneratedRow(row),
        } : null,
        {
            label: tLib('datacommon.delete.label'),
            icon: 'delete',
            showInMenu: true,
            onClick: apiDelete,
            hidden: hideDeleteForRow,
        }
    ].filter(notNull), [dialogMode, apiIsReady, tLib, hideDeleteForRow]);
    const filterElement = React.useMemo(() => (
        <AlarmaConfigFilter
            onSpringFilterChange={setUserFilter}
            entornApps={entornApps}
            hideEntornAppField={filterBy?.entornAppId != null}
        />
    ), [entornApps, filterBy?.entornAppId]);

    if (!entornApps || user == null) return <CenteredCircularProgress />;

    const currentFilter = springFilterBuilder.and(
        userFilter,
        filterBy?.entornAppId ? `entornAppId:${filterBy.entornAppId}` : springFilterBuilder.inn('entornAppId', entornApps.map(e => e?.id)),
        !isCurrentUserAdmin || !adminView ? springFilterBuilder.and(
            springFilterBuilder.eq('createdBy', `'${user.codi}'`),
            springFilterBuilder.eq('admin', false),
        ) : springFilterBuilder.eq('admin', true),
    );

    return (
        <GridPage>
            <MuiDataGrid
                apiRef={apiRef}
                datagridApiRef={gridApiRef}
                title={t($ => $.page.alarmaConfig.title)}
                resourceName="alarmaConfig"
                columns={columns}
                toolbarType="upper"
                rowAdditionalActions={actions}
                toolbarAdditionalRow={filterElement}
                toolbarElementsWithPositions={toolbarElementsWithPositions}
                filter={currentFilter}
                toolbarCreateLink="form"
                rowUpdateLink="form/{{id}}"
                disableColumnSorting
                rowHideDeleteButton
                rowHideUpdateButton={row => dialogMode || hideDeleteForRow(row)}
                toolbarHideCreate={dialogMode || undefined}
                toolbarHideQuickFilter
                {...treeDataGridProps}
                {...reorderingDataGridProps}
            />
        </GridPage>
    );
}

export default AlarmaConfig;
