/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.api.v1.avis;

import es.caib.comanda.service.v1.avis.ApiException;
import es.caib.comanda.model.v1.avis.Avis;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppComandaAvisosApi
 */
class AppComandaAvisosApiTest {

    private final AppComandaAvisosApi api = new AppComandaAvisosApi();

    /**
     * Consulta un avís per identificador, app i entorn
     *
     * Retorna les dades d&#39;un avís a partir de l&#39;identificador funcional, appCodi i entornCodi.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void consultarAvisTest() throws ApiException {
        //
        //String identificador = null;
        //
        //String appCodi = null;
        //
        //String entornCodi = null;
        //
        //Avis response = api.consultarAvis(identificador, appCodi, entornCodi);

        // TODO: test validations
    }
    /**
     * Crea un avís (enviament a la cua d&#39;avisos)
     *
     * Afegeix un missatge d&#39;avís a la cua JMS &#39;CUA_AVISOS&#39;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void crearAvisTest() throws ApiException {
        //
        //Avis avis = null;
        //
        //String response = api.crearAvis(avis);

        // TODO: test validations
    }
    /**
     * Crea múltiples avisos
     *
     * Envia múltiples avisos a la cua JMS &#39;CUA_AVISOS&#39; una a una.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void crearMultiplesAvisosTest() throws ApiException {
        //
        //List<Avis> avis = null;
        //
        //String response = api.crearMultiplesAvisos(avis);

        // TODO: test validations
    }
    /**
     * Modifica un avís existent
     *
     * Envia un missatge de modificació d&#39;avís a la cua JMS &#39;CUA_AVISOS&#39;. No es crea si no existeix.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void modificarAvisTest() throws ApiException {
        //
        //String identificador = null;
        //
        //Avis avis = null;
        //
        //String response = api.modificarAvis(identificador, avis);

        // TODO: test validations
    }
    /**
     * Modifica múltiples avisos existents
     *
     * Envia múltiples missatges de modificació d&#39;avisos a la cua JMS &#39;CUA_AVISOS&#39;. No es creen si no existeixen.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void modificarMultiplesAvisosTest() throws ApiException {
        //
        //List<Avis> avis = null;
        //
        //String response = api.modificarMultiplesAvisos(avis);

        // TODO: test validations
    }
}
