spring:
  application:
    name: comanda-gateway
#  cloud:
#    gateway:
#      default-filters:
#        - RemoveRequestHeader=Access-Control-Request-Method
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        add-to-simple-url-handler-mapping: true
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-headers: "*"
#            allowed-methods: "*"
#            allow-credentials: true
