/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.api.v1.salut;

import es.caib.comanda.service.v1.salut.ApiException;
import es.caib.comanda.model.v1.salut.AppInfo;
import es.caib.comanda.model.v1.salut.SalutInfo;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ComandaAppSalutApi
 */
class ComandaAppSalutApiTest {

    private final ComandaAppSalutApi api = new ComandaAppSalutApi();

    /**
     * Estat de salut funcional
     *
     * Retorna l&#39;estat de salut funcional i integracions, amb metadades de versió.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void salutTest() throws ApiException {
        //
        //SalutInfo response = api.salut();

        // TODO: test validations
    }
    /**
     * Informació de l&#39;aplicació
     *
     * Retorna dades bàsiques de l&#39;aplicació (codi, nom, versió, data de build, etc.) i contextos exposats.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void salutInfoTest() throws ApiException {
        //
        //AppInfo response = api.salutInfo();

        // TODO: test validations
    }
}
