-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: db/changelog/db.changelog-master.yaml
-- Ran at: 10/10/25 19:39
-- Against: null@offline:oracle?changeLogFile=liquibase/databasechangelog.csv
-- Liquibase version: 4.29.2
-- *********************************************************************

-- Changeset db/changelog/init/00_avis_init_table.yaml::avis-init-table-1::limit
CREATE TABLE com_avis (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_app_id NUMBER(38, 0) NOT NULL, app_id NUMBER(38, 0) NOT NULL, entorn_id NUMBER(38, 0) NOT NULL, identificador VARCHAR2(64 CHAR) NOT NULL, tipus VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(255 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), data_inici date, data_fi date, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_avis_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-1::limit
CREATE TABLE com_entorn (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(255 CHAR), CONSTRAINT com_entorn_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-2::limit
CREATE TABLE com_app (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(100 CHAR) NOT NULL, descripcio VARCHAR2(1000 CHAR), activa BOOLEAN, LOGO BLOB, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_app_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-3::limit
CREATE TABLE com_entorn_app (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_id NUMBER(38, 0) NOT NULL, app_id NUMBER(38, 0) NOT NULL, info_url VARCHAR2(200 CHAR) NOT NULL, info_interval INTEGER NOT NULL, info_data TIMESTAMP, salut_url VARCHAR2(200 CHAR) NOT NULL, salut_interval INTEGER NOT NULL, estadistica_info_url VARCHAR2(200 CHAR), estadistica_url VARCHAR2(200 CHAR), estadistica_cron VARCHAR2(40 CHAR), versio VARCHAR2(10 CHAR), activa BOOLEAN, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_entorn_app_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-6::limit
CREATE TABLE com_integracio (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(100 CHAR) NOT NULL, logo BLOB, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_integracio_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-4::limit
CREATE TABLE com_app_integracio (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, integracio_id NUMBER(38, 0) NOT NULL, entorn_app_id NUMBER(38, 0) NOT NULL, activa BOOLEAN, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_app_integracio_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_conf_init_table.yaml::conf-init-table-5::limit
CREATE TABLE com_app_subsistema (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(100 CHAR) NOT NULL, actiu BOOLEAN, entorn_app_id NUMBER(38, 0) NOT NULL, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_app_subsistema_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-1::limit
CREATE TABLE com_est_dimensio (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(64 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), entorn_app_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_est_dimensio_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-2::limit
CREATE TABLE com_est_dimensio_valor (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, valor VARCHAR2(255 CHAR), dimensio_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_est_dimensio_valor_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-3::limit
CREATE TABLE com_est_indicador (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, nom VARCHAR2(64 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), entorn_app_id NUMBER(38, 0) NOT NULL, format VARCHAR2(64 CHAR), CONSTRAINT com_est_indicador_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-4::limit
CREATE TABLE com_est_temps (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, data date NOT NULL, anualitat INTEGER NOT NULL, trimestre INTEGER NOT NULL, mes INTEGER NOT NULL, setmana INTEGER NOT NULL, dia INTEGER NOT NULL, dia_setmana VARCHAR2(2 CHAR) NOT NULL, CONSTRAINT com_est_temps_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-5::limit
CREATE TABLE com_est_fet (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, temps_id NUMBER(38, 0) NOT NULL, dimensions_json VARCHAR2(4000 CHAR), indicadors_json VARCHAR2(4000 CHAR), entorn_app_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_est_fet_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-7::limit
CREATE TABLE com_est_widget (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, widget_type VARCHAR2(16 CHAR) NOT NULL, titol VARCHAR2(64 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), app_id NUMBER(38, 0) NOT NULL, periode_mode VARCHAR2(32 CHAR), preset_periode VARCHAR2(32 CHAR), preset_count NUMBER, relatiu_punt_referencia VARCHAR2(32 CHAR), relatiu_count NUMBER, relatiu_unitat VARCHAR2(32 CHAR), relatiu_alineacio VARCHAR2(32 CHAR), absolut_tipus VARCHAR2(32 CHAR), absolut_data_inici date, absolut_data_fi date, absolut_any_referencia VARCHAR2(32 CHAR), absolut_any_valor NUMBER, absolut_periode_unitat VARCHAR2(32 CHAR), absolut_periode_inici NUMBER, absolut_periode_fi NUMBER, indicador_id NUMBER(38, 0), tipus_grafic VARCHAR2(16 CHAR), tipus_dades VARCHAR2(32 CHAR), tipus_valors VARCHAR2(16 CHAR), temps_agrupacio VARCHAR2(16 CHAR), descomposicio_dimensio_id NUMBER(38, 0), agrupar_dimensio_descomposicio BOOLEAN, llegenda_x VARCHAR2(64 CHAR), llegenda_y VARCHAR2(64 CHAR), unitat VARCHAR2(64 CHAR), agrupament_dimensio_id NUMBER(38, 0), agrupament_dimensio_titol VARCHAR2(64 CHAR), comparar_periode_anterior BOOLEAN DEFAULT 0, atributs_visuals VARCHAR2(4000 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_widget_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-8::limit
CREATE TABLE com_est_widget_dim_valor (widget_id NUMBER(38, 0) NOT NULL, dimensio_valor_id NUMBER(38, 0) NOT NULL);

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-9::limit
CREATE TABLE com_est_indicador_table (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, indicador_id NUMBER(38, 0) NOT NULL, widget_id NUMBER(38, 0) NOT NULL, agregacio VARCHAR2(16 CHAR), unitat_agregacio VARCHAR2(16 CHAR), titol VARCHAR2(64 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_indicador_table_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-10::limit
CREATE TABLE com_est_dashboard (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, titol VARCHAR2(64 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_dashboard_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-11::limit
CREATE TABLE com_est_dashboard_item (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, pos_x INTEGER NOT NULL, pos_y INTEGER NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, dashboard_id NUMBER(38, 0) NOT NULL, widget_id NUMBER(38, 0) NOT NULL, entorn_id NUMBER(38, 0) NOT NULL, atributs_visuals VARCHAR2(4000 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_dashboard_item_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_est_init_table.yaml::est-init-table-12::limit
CREATE TABLE com_est_dashboard_titol (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, dashboard_id NUMBER(38, 0) NOT NULL, titol VARCHAR2(255 CHAR) NOT NULL, subtitol VARCHAR2(255 CHAR), pos_x INTEGER NOT NULL, pos_y INTEGER NOT NULL, width INTEGER NOT NULL, height INTEGER NOT NULL, color_titol VARCHAR2(8 CHAR), mida_font_titol INTEGER, color_subtitol VARCHAR2(8 CHAR), mida_font_subtitol INTEGER, color_fons VARCHAR2(8 CHAR), mostrar_vora BOOLEAN, color_vora VARCHAR2(8 CHAR), ample_vora INTEGER, created_by VARCHAR2(50 CHAR), created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(50 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_est_dashboard_titol_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_monitor_init_table.yaml::monitor-init-table-1::limit
CREATE TABLE com_monitor (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_app_id NUMBER(38, 0), codi VARCHAR2(16 CHAR) NOT NULL, tipus VARCHAR2(255 CHAR) NOT NULL, data TIMESTAMP NOT NULL, url VARCHAR2(255 CHAR), operacio VARCHAR2(255 CHAR) NOT NULL, temps_resposta NUMBER(38, 0), estat VARCHAR2(255 CHAR) NOT NULL, codi_usuari VARCHAR2(64 CHAR), error_descripcio VARCHAR2(1024 CHAR), excepcio_msg VARCHAR2(1024 CHAR), excepcio_stacktrace VARCHAR2(4000 CHAR), CONSTRAINT com_monitor_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_permis_init_table.yaml::permis-init-table-1::limit
CREATE TABLE com_objecte (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipus VARCHAR2(64 CHAR) NOT NULL, nom VARCHAR2(255 CHAR) NOT NULL, identificador VARCHAR2(64 CHAR) NOT NULL, CONSTRAINT com_objecte_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_permis_init_table.yaml::permis-init-table-2::limit
CREATE TABLE com_acces (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, acces VARCHAR2(64 CHAR), CONSTRAINT com_acces_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_permis_init_table.yaml::permis-init-table-3::limit
CREATE TABLE com_permis (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_app_id NUMBER(38, 0) NOT NULL, usuari VARCHAR2(64 CHAR), grup VARCHAR2(64 CHAR), objecte_id NUMBER(38, 0) NOT NULL, created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_permis_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_permis_init_table.yaml::permis-init-table-4::limit
CREATE TABLE com_permis_acces (permis_id NUMBER(38, 0) NOT NULL, acces_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_permis_acces_pk PRIMARY KEY (permis_id, acces_id));

-- Changeset db/changelog/init/00_permis_init_table.yaml::permis-init-table-5::limit
CREATE TABLE com_permis_hereus (permis_id NUMBER(38, 0) NOT NULL, hereu_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_permis_hereus_pk PRIMARY KEY (permis_id, hereu_id));

-- Changeset db/changelog/init/00_salut_init_table.yaml::salut-init-table-1::limit
CREATE TABLE com_salut (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_app_id NUMBER(38, 0) NOT NULL, data TIMESTAMP NOT NULL, app_estat VARCHAR2(20 CHAR) NOT NULL, app_latencia INTEGER, bd_estat VARCHAR2(20 CHAR), bd_latencia INTEGER, CONSTRAINT com_salut_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_salut_init_table.yaml::salut-init-table-2::limit
CREATE TABLE com_salut_integracio (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, estat VARCHAR2(20 CHAR) NOT NULL, latencia INTEGER, total_ok INTEGER NOT NULL, total_error INTEGER NOT NULL, salut_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_salut_integracio_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_salut_init_table.yaml::salut-init-table-3::limit
CREATE TABLE com_salut_subsistema (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(16 CHAR) NOT NULL, estat VARCHAR2(20 CHAR) NOT NULL, latencia INTEGER, total_ok INTEGER NOT NULL, total_error INTEGER NOT NULL, salut_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_salut_subsistema_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_salut_init_table.yaml::salut-init-table-4::limit
CREATE TABLE com_salut_missatge (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, data TIMESTAMP NOT NULL, nivell VARCHAR2(10 CHAR) NOT NULL, missatge VARCHAR2(2048 CHAR), salut_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_salut_missatge_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_salut_init_table.yaml::salut-init-table-5::limit
CREATE TABLE com_salut_detall (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(10 CHAR) NOT NULL, nom VARCHAR2(100 CHAR) NOT NULL, valor VARCHAR2(1024 CHAR), salut_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_salut_detall_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_tasca_init_table.yaml::tasca-init-table-1::limit
CREATE TABLE com_tasca (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, entorn_app_id NUMBER(38, 0) NOT NULL, app_id NUMBER(38, 0) NOT NULL, entorn_id NUMBER(38, 0) NOT NULL, identificador VARCHAR2(64 CHAR) NOT NULL, tipus VARCHAR2(64 CHAR) NOT NULL, nom VARCHAR2(255 CHAR) NOT NULL, descripcio VARCHAR2(1024 CHAR), estat VARCHAR2(16 CHAR) NOT NULL, estat_desc VARCHAR2(1024 CHAR), prioritat VARCHAR2(16 CHAR), data_inici date, data_fi date, data_caducitat date, url VARCHAR2(255 CHAR) NOT NULL, responsable VARCHAR2(128 CHAR), grup VARCHAR2(128 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_tasca_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/00_tasca_init_table.yaml::tasca-init-table-2::limit
CREATE TABLE com_tasca_usuari (tasca_id NUMBER(38, 0) NOT NULL, usuari VARCHAR2(255 CHAR) NOT NULL, CONSTRAINT com_tasca_usuari_pk PRIMARY KEY (tasca_id));

-- Changeset db/changelog/init/00_tasca_init_table.yaml::tasca-init-table-3::limit
CREATE TABLE com_tasca_grup (tasca_id NUMBER(38, 0) NOT NULL, grup VARCHAR2(255 CHAR) NOT NULL, CONSTRAINT com_tasca_grup_pk PRIMARY KEY (tasca_id));

-- Changeset db/changelog/init/00_usuaris_init_table.yaml::usuaris-init-table-1::limit
CREATE TABLE com_usuari (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, codi VARCHAR2(64 CHAR) NOT NULL, nom VARCHAR2(255 CHAR) NOT NULL, nif VARCHAR2(10 CHAR), email VARCHAR2(255 CHAR), created_by VARCHAR2(64 CHAR) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64 CHAR), lastmod_date TIMESTAMP, v NUMBER(38, 0), CONSTRAINT com_usuari_pk PRIMARY KEY (id));

-- Changeset db/changelog/init/01_avis_init_constraint.yaml::avis-init-constraint-1::limit
ALTER TABLE com_avis ADD CONSTRAINT com_avis_ident_uk UNIQUE (entorn_app_id, identificador);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-1::limit
ALTER TABLE com_entorn_app ADD CONSTRAINT com_entorn_app_entorn_fk FOREIGN KEY (entorn_id) REFERENCES com_entorn (id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-2::limit
ALTER TABLE com_entorn_app ADD CONSTRAINT com_entorn_app_app_fk FOREIGN KEY (app_id) REFERENCES com_app (id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-3::limit
ALTER TABLE com_app_integracio ADD CONSTRAINT com_app_integ_entorn_app_fk FOREIGN KEY (entorn_app_id) REFERENCES com_entorn_app (id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-11::limit
ALTER TABLE com_app_integracio ADD CONSTRAINT com_app_integ_integracio_fk FOREIGN KEY (integracio_id) REFERENCES com_integracio (id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-4::limit
ALTER TABLE com_app_subsistema ADD CONSTRAINT com_app_subs_entorn_app_fk FOREIGN KEY (entorn_app_id) REFERENCES com_entorn_app (id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-5::limit
ALTER TABLE com_entorn ADD CONSTRAINT com_entorn_codi_uk UNIQUE (codi);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-6::limit
ALTER TABLE com_entorn_app ADD CONSTRAINT com_entorn_app_entapp_uk UNIQUE (entorn_id, app_id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-7::limit
ALTER TABLE com_app ADD CONSTRAINT com_app_codi_uk UNIQUE (codi);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-8::limit
ALTER TABLE com_app_integracio ADD CONSTRAINT com_app_integracio_app_int_uk UNIQUE (entorn_app_id, integracio_id);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-9::limit
ALTER TABLE com_app_subsistema ADD CONSTRAINT com_app_subsistema_appcodi_uk UNIQUE (entorn_app_id, codi);

-- Changeset db/changelog/init/01_conf_init_constraint.yaml::conf-init-constraint-10::limit
ALTER TABLE com_integracio ADD CONSTRAINT com_integracio_codi_uk UNIQUE (codi);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-1::limit
ALTER TABLE com_est_dimensio ADD CONSTRAINT com_dim_nom_uk UNIQUE (nom, entorn_app_id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-2::limit
ALTER TABLE com_est_dimensio_valor ADD CONSTRAINT com_dim_valor_dim_fk FOREIGN KEY (dimensio_id) REFERENCES com_est_dimensio (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-3::limit
ALTER TABLE com_est_indicador ADD CONSTRAINT com_ind_nom_uk UNIQUE (nom, entorn_app_id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-5::limit
ALTER TABLE com_est_fet ADD CONSTRAINT com_fet_temps_fk FOREIGN KEY (temps_id) REFERENCES com_est_temps (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-8::limit
ALTER TABLE com_est_widget ADD CONSTRAINT com_widget_indicador_fk FOREIGN KEY (indicador_id) REFERENCES com_est_indicador (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-9::limit
ALTER TABLE com_est_widget ADD CONSTRAINT com_widget_taula_dimensio_fk FOREIGN KEY (agrupament_dimensio_id) REFERENCES com_est_dimensio (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-10::limit
ALTER TABLE com_est_widget ADD CONSTRAINT com_widget_descomposicio_fk FOREIGN KEY (descomposicio_dimensio_id) REFERENCES com_est_dimensio (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-11::limit
ALTER TABLE com_est_widget ADD CONSTRAINT com_widget_titol_uk UNIQUE (titol, app_id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-12::limit
ALTER TABLE com_est_widget_dim_valor ADD CONSTRAINT com_widget_dvalor_widget_fk FOREIGN KEY (widget_id) REFERENCES com_est_widget (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-13::limit
ALTER TABLE com_est_widget_dim_valor ADD CONSTRAINT com_widget_dvalor_dvalor_fk FOREIGN KEY (dimensio_valor_id) REFERENCES com_est_dimensio_valor (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-14::limit
ALTER TABLE com_est_indicador_table ADD CONSTRAINT com_indtab_indicador_fk FOREIGN KEY (indicador_id) REFERENCES com_est_indicador (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-15::limit
ALTER TABLE com_est_indicador_table ADD CONSTRAINT com_indtab_widget_fk FOREIGN KEY (widget_id) REFERENCES com_est_widget (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-16::limit
ALTER TABLE com_est_dashboard_item ADD CONSTRAINT com_dboard_item_dboard_fk FOREIGN KEY (dashboard_id) REFERENCES com_est_dashboard (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-17::limit
ALTER TABLE com_est_dashboard_item ADD CONSTRAINT com_dboard_item_widget_fk FOREIGN KEY (widget_id) REFERENCES com_est_widget (id);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-18::limit
ALTER TABLE com_est_dashboard ADD CONSTRAINT com_dashboard_titol_uk UNIQUE (titol);

-- Changeset db/changelog/init/01_est_init_constraint.yaml::est-init-constraint-19::limit
ALTER TABLE com_est_dashboard_titol ADD CONSTRAINT com_dboard_titol_dboard_fk FOREIGN KEY (dashboard_id) REFERENCES com_est_dashboard (id);

-- Changeset db/changelog/init/01_monitor_init_constraint.yaml::monitor-init-constraint-1::limit
-- Changeset db/changelog/init/01_permis_init_constraint.yaml::permis-init-constraint-1::limit
ALTER TABLE com_permis_acces ADD CONSTRAINT com_permisacces_permis_fk FOREIGN KEY (permis_id) REFERENCES com_permis (id);

-- Changeset db/changelog/init/01_permis_init_constraint.yaml::permis-init-constraint-2::limit
ALTER TABLE com_permis_acces ADD CONSTRAINT com_permisacces_acces_fk FOREIGN KEY (acces_id) REFERENCES com_acces (id);

-- Changeset db/changelog/init/01_permis_init_constraint.yaml::permis-init-constraint-3::limit
ALTER TABLE com_permis ADD CONSTRAINT com_permis_objecte_fk FOREIGN KEY (objecte_id) REFERENCES com_objecte (id);

-- Changeset db/changelog/init/01_permis_init_constraint.yaml::permis-init-constraint-4::limit
ALTER TABLE com_permis_hereus ADD CONSTRAINT com_permishereus_permis_fk FOREIGN KEY (permis_id) REFERENCES com_permis (id);

-- Changeset db/changelog/init/01_permis_init_constraint.yaml::permis-init-constraint-5::limit
ALTER TABLE com_permis_hereus ADD CONSTRAINT com_permishereus_objecte_fk FOREIGN KEY (hereu_id) REFERENCES com_objecte (id);

-- Changeset db/changelog/init/01_salut_init_constraint.yaml::salut-init-constraint-1::limit
ALTER TABLE com_salut_integracio ADD CONSTRAINT com_salutint_salut_fk FOREIGN KEY (salut_id) REFERENCES com_salut (id);

-- Changeset db/changelog/init/01_salut_init_constraint.yaml::salut-init-constraint-salut-2::limit
ALTER TABLE com_salut_subsistema ADD CONSTRAINT com_salutsub_salut_fk FOREIGN KEY (salut_id) REFERENCES com_salut (id);

-- Changeset db/changelog/init/01_salut_init_constraint.yaml::salut-init-constraint-3::limit
ALTER TABLE com_salut_missatge ADD CONSTRAINT com_salutmsg_salut_fk FOREIGN KEY (salut_id) REFERENCES com_salut (id);

-- Changeset db/changelog/init/01_salut_init_constraint.yaml::salut-init-constraint-4::limit
ALTER TABLE com_salut_detall ADD CONSTRAINT com_salutdet_salut_fk FOREIGN KEY (salut_id) REFERENCES com_salut (id);

-- Changeset db/changelog/init/01_tasca_init_constraint.yaml::tasca-init-constraint-1::limit
ALTER TABLE com_tasca_usuari ADD CONSTRAINT com_tascausr_tasca_fk FOREIGN KEY (tasca_id) REFERENCES com_tasca (id);

-- Changeset db/changelog/init/01_tasca_init_constraint.yaml::tasca-init-constraint-2::limit
ALTER TABLE com_tasca_grup ADD CONSTRAINT com_tascagrp_tasca_fk FOREIGN KEY (tasca_id) REFERENCES com_tasca (id);

-- Changeset db/changelog/init/01_tasca_init_constraint.yaml::tasca-init-constraint-3::limit
ALTER TABLE com_tasca ADD CONSTRAINT com_tasca_ident_uk UNIQUE (entorn_app_id, identificador);

-- Changeset db/changelog/init/01_usuaris_init_constraint.yaml::usuaris-init-constraint-1::limit
ALTER TABLE com_usuari ADD CONSTRAINT com_usuari_codi_uk UNIQUE (codi);

-- Changeset db/changelog/init/02_avis_init_sequence.yaml::avis-init-sequence-1::limit
-- Changeset db/changelog/init/02_conf_init_sequence.yaml::conf-init-sequence-1::limit
-- Changeset db/changelog/init/02_est_init_sequence.yaml::est-init-sequence-1::limit
-- Changeset db/changelog/init/02_monitor_init_sequence.yaml::monitor-init-sequence-1::limit
-- Changeset db/changelog/init/02_permis_init_sequence.yaml::permis-init-sequence-1::limit
-- Changeset db/changelog/init/02_salut_init_sequence.yaml::salut-init-sequence-1::limit
-- Changeset db/changelog/init/02_tasca_init_sequence.yaml::tasca-init-sequence-1::limit
-- Changeset db/changelog/init/02_usuaris_init_sequence.yaml::usuaris-init-sequence-1::limit
-- Changeset db/changelog/init/03_avis_init_trigger.yaml::avis-init-trigger-1::limit
-- Changeset db/changelog/init/03_conf_init_trigger.yaml::conf-init-trigger-1::limit
-- Changeset db/changelog/init/03_est_init_trigger.yaml::create_generar_consulta_procedure_oracle::limit
CREATE OR REPLACE PROCEDURE GENERAR_CONSULTA_ENTORN_APP (
    p_entorn_app_id IN NUMBER,
    p_dimension_filters IN VARCHAR2, 
    p_data IN DATE,                  
    p_resultat OUT SYS_REFCURSOR
) AS
    sql_query CLOB;
    dynamic_dimension_columns CLOB := '';
    dynamic_indicator_columns CLOB := '';
    static_dimension_columns CLOB := '';
    static_indicator_columns CLOB := '';
    dimension_condition CLOB := '';
    data_condition CLOB := '';
BEGIN
    
    FOR dim IN (SELECT LOWER(codi) AS codi, REPLACE(LOWER(codi), '''', '''''') AS escaped_clau
                FROM COMANDA.COM_EST_DIMENSIO
                WHERE entorn_app_id = p_entorn_app_id
                ORDER BY LOWER(codi)) LOOP
        
        dynamic_dimension_columns := dynamic_dimension_columns || '"' || dim.escaped_clau || '" VARCHAR2(1000 CHAR) PATH ''$."' || dim.escaped_clau || '"'', ';
        
        static_dimension_columns := static_dimension_columns || '"' || dim.escaped_clau || '", ';
    END LOOP;
    
    
    FOR ind IN (SELECT LOWER(codi) AS codi, REPLACE(LOWER(codi), '''', '''''') AS escaped_clau
                FROM COMANDA.COM_EST_INDICADOR
                WHERE entorn_app_id = p_entorn_app_id
                ORDER BY LOWER(codi)) LOOP
        
        dynamic_indicator_columns := dynamic_indicator_columns || '"' || ind.escaped_clau || '" NUMBER PATH ''$."' || ind.escaped_clau || '"'', ';
        
        static_indicator_columns := static_indicator_columns || '"' || ind.escaped_clau || '", ';
    END LOOP;
    
    
    dynamic_dimension_columns := RTRIM(dynamic_dimension_columns, ', ');
    dynamic_indicator_columns := RTRIM(dynamic_indicator_columns, ', ');
    static_dimension_columns := RTRIM(static_dimension_columns, ', ');
    static_indicator_columns := RTRIM(static_indicator_columns, ', ');

    
    IF p_dimension_filters IS NOT NULL AND LENGTH(p_dimension_filters) > 0 THEN
        dimension_condition := ' AND (' || p_dimension_filters || ') ';
    END IF;
    
    
    IF p_data IS NOT NULL THEN
        data_condition := ' AND f.temps.data = TO_DATE(''' || TO_CHAR(p_data, 'YYYY-MM-DD') || ''', ''YYYY-MM-DD'') ';
    END IF;
    
    
    sql_query := '
        SELECT
            ' || static_dimension_columns || ',
            ' || static_indicator_columns || '
        FROM (
            SELECT
                d.*,
                i.*
            FROM COMANDA.COM_EST_FET f
            -- Extraiem les dimensions del JSON
            CROSS JOIN JSON_TABLE(
                f.dimensions_json,
                ''$'' COLUMNS (
                    ' || dynamic_dimension_columns || '
                )
            ) d
            -- Extraiem els indicadors del JSON
            CROSS JOIN JSON_TABLE(
                f.indicadors_json,
                ''$'' COLUMNS (
                    ' || dynamic_indicator_columns || '
                )
            ) i
            WHERE f.entorn_app_id = ' || p_entorn_app_id || '
                ' || data_condition || '
                ' || dimension_condition || '
        )
        ORDER BY 1 ASC'; 
        
    
    OPEN p_resultat FOR sql_query;
END;

-- Changeset db/changelog/init/03_est_init_trigger.yaml::est-init-trigger-1::limit
-- Changeset db/changelog/init/03_monitor_init_trigger.yaml::monitor-init-trigger-1::limit
-- Changeset db/changelog/init/03_permis_init_trigger.yaml::permis-init-trigger-1::limit
-- Changeset db/changelog/init/03_permis_init_trigger.yaml::permis-init-trigger-2::limit
-- Changeset db/changelog/init/03_permis_init_trigger.yaml::permis-init-trigger-3::limit
-- Changeset db/changelog/init/03_salut_init_trigger.yaml::salut-init-trigger-1::limit
-- Changeset db/changelog/init/03_tasca_init_trigger.yaml::tasca-init-trigger-1::limit
-- Changeset db/changelog/init/03_usuaris_init_trigger.yaml::usuaris-init-trigger-1::limit
-- Changeset db/changelog/init/04_avis_init_data.yaml::avis-init-data-1::limit
-- Changeset db/changelog/init/04_conf_init_data.yaml::conf-init-data-1::limit
INSERT INTO com_entorn (codi, nom) VALUES ('DEV', 'Entorn de desenvolupament');

INSERT INTO com_entorn (codi, nom) VALUES ('PRE', 'Entorn de proves');

INSERT INTO com_entorn (codi, nom) VALUES ('PRO', 'Entorn de producció');

INSERT INTO com_entorn (codi, nom) VALUES ('SE', 'Entorn de serveis estables');

-- Changeset db/changelog/init/04_est_init_data.yaml::est-init-data-1::limit
-- Changeset db/changelog/init/04_monitor_init_data.yaml::monitor-init-data-1::limit
-- Changeset db/changelog/init/04_permis_init_data.yaml::permis-init-data-1::limit
-- Changeset db/changelog/init/04_salut_init_data.yaml::salut-init-data-1::limit
-- Changeset db/changelog/init/04_tasca_init_data.yaml::tasca-init-data-1::limit
-- Changeset db/changelog/init/04_usuaris_init_data.yaml::usuaris-init-data-1::limit
-- Changeset db/changelog/init/05_est_init_index.yaml::est-init-data-1::limit
CREATE INDEX com_est_fet_temps_i ON com_est_fet(temps_id);

CREATE INDEX com_est_fet_entornapp_i ON com_est_fet(entorn_app_id);

CREATE INDEX com_est_temps_data_i ON com_est_temps(data);

CREATE INDEX com_est_temps_anualitat_i ON com_est_temps(anualitat);

CREATE INDEX com_est_temps_trimestre_i ON com_est_temps(anualitat, trimestre);

CREATE INDEX com_est_temps_mes_i ON com_est_temps(anualitat, mes);

CREATE INDEX com_est_temps_setmana_i ON com_est_temps(anualitat, setmana);

CREATE INDEX com_est_temps_dia_i ON com_est_temps(anualitat, mes, dia);

CREATE INDEX com_est_dimensio_valor_dim_i ON com_est_dimensio_valor(dimensio_id);

-- Changeset db/changelog/init/05_monitor_init_index.yaml::monitor-init-index-1::limit
CREATE INDEX com_mon_codi_i ON com_monitor(codi);

CREATE INDEX com_mon_usuari_i ON com_monitor(codi_usuari);

CREATE INDEX com_mon_data_i ON com_monitor(data);

CREATE INDEX com_mon_estat_i ON com_monitor(estat);

-- Changeset db/changelog/changes/11.yaml::con-change-11-01::limit
ALTER TABLE com_entorn_app ADD jdk_version VARCHAR2(10);

ALTER TABLE com_entorn_app ADD revisio VARCHAR2(64);

-- Changeset db/changelog/changes/1608.yaml::est-change-1608-01::limit
ALTER TABLE com_est_dashboard ADD app_id NUMBER(38, 0);

ALTER TABLE com_est_dashboard ADD entorn_id NUMBER(38, 0);

-- Changeset db/changelog/changes/30.yaml::salut-change-30-1::Limit
ALTER TABLE com_salut ADD tipus_registre VARCHAR2(10 CHAR) DEFAULT 'MINUT' NOT NULL;

CREATE INDEX com_salut_tipus_registre_id ON com_salut(tipus_registre);

CREATE INDEX com_salut_entorn_data_id ON com_salut(entorn_app_id, data);

-- Changeset db/changelog/changes/30.yaml::salut-change-30-2::Limit
ALTER TABLE com_salut ADD app_count_up INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_warn INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_degraded INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_down INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_error INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_maintenance INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_count_unknown INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_up INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_warn INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_degraded INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_down INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_error INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_maintenance INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD bd_count_unknown INTEGER DEFAULT 0;

ALTER TABLE com_salut ADD app_latencia_mitjana INTEGER;

ALTER TABLE com_salut ADD app_latencia_num_elements INTEGER;

ALTER TABLE com_salut ADD bd_latencia_mitjana INTEGER;

ALTER TABLE com_salut ADD bd_latencia_num_elements INTEGER;

ALTER TABLE com_salut ADD data_app TIMESTAMP;

ALTER TABLE com_salut ADD num_elements INTEGER;

-- Changeset db/changelog/changes/30.yaml::salut-change-30-3::Limit
ALTER TABLE com_salut_integracio ADD count_up INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_warn INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_degraded INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_down INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_error INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_maintenance INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD count_unknown INTEGER DEFAULT 0;

ALTER TABLE com_salut_integracio ADD estat_num_elements INTEGER;

ALTER TABLE com_salut_integracio ADD latencia_mitjana INTEGER;

ALTER TABLE com_salut_integracio ADD latencia_num_elements INTEGER;

-- Changeset db/changelog/changes/30.yaml::salut-change-30-4::Limit
ALTER TABLE com_salut_subsistema ADD count_up INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_warn INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_degraded INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_down INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_error INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_maintenance INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD count_unknown INTEGER DEFAULT 0;

ALTER TABLE com_salut_subsistema ADD estat_num_elements INTEGER;

ALTER TABLE com_salut_subsistema ADD latencia_mitjana INTEGER;

ALTER TABLE com_salut_subsistema ADD latencia_num_elements INTEGER;

-- Changeset db/changelog/changes/30.yaml::salut-change-30-5::Limit
truncate table com_salut_missatge reuse storage;

truncate table com_salut_detall reuse storage;

truncate table com_salut_subsistema reuse storage;

truncate table com_salut_integracio reuse storage;

truncate table com_salut reuse storage;

-- Changeset db/changelog/changes/33.yaml::con-change-33-01::limit
CREATE TABLE com_parametre (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, grup VARCHAR2(128) NOT NULL, subgrup VARCHAR2(128) NOT NULL, tipus VARCHAR2(16) NOT NULL, codi VARCHAR2(128) NOT NULL, nom VARCHAR2(128) NOT NULL, nom_key VARCHAR2(128), descripcio VARCHAR2(1024), descripcio_key VARCHAR2(128), valor VARCHAR2(255), editable BOOLEAN, grup_key VARCHAR2(128), subgrup_key VARCHAR2(128), CONSTRAINT com_parametre_pk PRIMARY KEY (id));

-- Changeset db/changelog/changes/33.yaml::con-change-33-02::limit
ALTER TABLE com_parametre ADD CONSTRAINT com_parametre_codi_uk UNIQUE (codi);

-- Changeset db/changelog/changes/54.yaml::salut-change-54-1::Limit
ALTER TABLE com_salut_subsistema ADD total_tempsmig INTEGER;

ALTER TABLE com_salut_subsistema ADD pet_ok_ultperiode INTEGER;

ALTER TABLE com_salut_subsistema ADD pet_error_ultperiode INTEGER;

ALTER TABLE com_salut_subsistema ADD temps_mig_ultperiode INTEGER;

UPDATE com_salut_subsistema SET pet_error_ultperiode = 0, pet_ok_ultperiode = 0, temps_mig_ultperiode = 0, total_tempsmig = 0;

ALTER TABLE com_salut_subsistema MODIFY total_tempsmig NOT NULL;

ALTER TABLE com_salut_subsistema MODIFY pet_ok_ultperiode NOT NULL;

ALTER TABLE com_salut_subsistema MODIFY pet_error_ultperiode NOT NULL;

ALTER TABLE com_salut_subsistema MODIFY temps_mig_ultperiode NOT NULL;

-- Changeset db/changelog/changes/54.yaml::salut-change-54-2::Limit
ALTER TABLE com_salut_integracio ADD total_tempsmig INTEGER;

ALTER TABLE com_salut_integracio ADD pet_ok_ultperiode INTEGER;

ALTER TABLE com_salut_integracio ADD pet_error_ultperiode INTEGER;

ALTER TABLE com_salut_integracio ADD temps_mig_ultperiode INTEGER;

ALTER TABLE com_salut_integracio ADD endpoint VARCHAR2(255 CHAR);

UPDATE com_salut_integracio SET pet_error_ultperiode = 0, pet_ok_ultperiode = 0, temps_mig_ultperiode = 0, total_tempsmig = 0;

ALTER TABLE com_salut_integracio MODIFY total_tempsmig NOT NULL;

ALTER TABLE com_salut_integracio MODIFY pet_ok_ultperiode NOT NULL;

ALTER TABLE com_salut_integracio MODIFY pet_error_ultperiode NOT NULL;

ALTER TABLE com_salut_integracio MODIFY temps_mig_ultperiode NOT NULL;

-- Changeset db/changelog/changes/54.yaml::salut-change-54-3::Limit
ALTER TABLE com_salut_integracio ADD pare_id NUMBER(38, 0);

ALTER TABLE com_salut_integracio ADD CONSTRAINT com_salutint_pare_fk FOREIGN KEY (pare_id) REFERENCES com_salut_integracio (id);

-- Changeset db/changelog/changes/54.yaml::salut-change-54-4::Limit
ALTER TABLE com_salut ADD peticio_error BOOLEAN;

UPDATE com_salut SET peticio_error = 0;

ALTER TABLE com_salut MODIFY peticio_error NOT NULL;

-- Changeset db/changelog/changes/8.yaml::con-change-08-01::limit
CREATE TABLE com_app_context (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_by VARCHAR2(64) NOT NULL, created_date TIMESTAMP NOT NULL, lastmod_by VARCHAR2(64), lastmod_date TIMESTAMP, v NUMBER(38, 0), codi VARCHAR2(64) NOT NULL, nom VARCHAR2(100) NOT NULL, path VARCHAR2(255) NOT NULL, api VARCHAR2(255), actiu BOOLEAN NOT NULL, entorn_app_id NUMBER(38, 0), CONSTRAINT com_app_context_pk PRIMARY KEY (id));

-- Changeset db/changelog/changes/8.yaml::con-change-08-02::limit
CREATE TABLE com_app_ctx_manual (id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR2(128) NOT NULL, path VARCHAR2(255) NOT NULL, app_ctx_id NUMBER(38, 0) NOT NULL, CONSTRAINT com_app_ctx_manual_pk PRIMARY KEY (id));

-- Changeset db/changelog/changes/8.yaml::con-change-08-03::limit
ALTER TABLE com_app_context ADD CONSTRAINT com_app_ctx_appcodi_uk UNIQUE (entorn_app_id, codi);

-- Changeset db/changelog/changes/8.yaml::con-change-08-04::limit
ALTER TABLE com_app_context ADD CONSTRAINT COM_APP_CTX_ENTORN_APP_FK FOREIGN KEY (entorn_app_id) REFERENCES com_entorn_app (id);

-- Changeset db/changelog/changes/8.yaml::con-change-08-05::limit
ALTER TABLE com_app_ctx_manual ADD CONSTRAINT com_manual_app_ctx_fk FOREIGN KEY (app_ctx_id) REFERENCES com_app_context (id);

-- Changeset db/changelog/changes/8.yaml::ccon-change-08-06::limit
ALTER TABLE com_app_ctx_manual ADD CONSTRAINT app_manual_appnom_uk UNIQUE (app_ctx_id, nom);

-- Changeset db/changelog/changes/con_30.yaml::con-change-30-01::limit
ALTER TABLE com_entorn_app DROP COLUMN info_interval;

ALTER TABLE com_entorn_app DROP COLUMN salut_interval;

-- Changeset db/changelog/changes/con_32.yaml::con-change-32-01::limit
ALTER TABLE com_entorn_app ADD compactable BOOLEAN DEFAULT 0 NOT NULL;

ALTER TABLE com_entorn_app ADD compactacio_setmanal INTEGER;

ALTER TABLE com_entorn_app ADD compactacio_mensual INTEGER;

ALTER TABLE com_entorn_app ADD eliminacio INTEGER;

-- Changeset db/changelog/changes/est_32.yaml::est-change-32-1::limit
ALTER TABLE com_est_dimensio_valor ADD agrupable BOOLEAN DEFAULT 0 NOT NULL;

ALTER TABLE com_est_dimensio_valor ADD valor_agrupacio VARCHAR2(255 CHAR);

ALTER TABLE com_est_indicador ADD compactable BOOLEAN DEFAULT 1 NOT NULL;

ALTER TABLE com_est_indicador ADD tipus_compactacio VARCHAR2(64 CHAR) DEFAULT 'SUMA';

ALTER TABLE com_est_indicador ADD compactacio_indicador_id NUMBER(38, 0);

ALTER TABLE com_est_indicador ADD CONSTRAINT com_ind_compactacio_fk FOREIGN KEY (compactacio_indicador_id) REFERENCES com_est_indicador (id);

-- Changeset db/changelog/changes/est_32.yaml::est-change-32-2::limit
ALTER TABLE com_est_fet ADD tipus VARCHAR2(64 CHAR) DEFAULT 'DIARI' NOT NULL;

ALTER TABLE com_est_fet ADD num_dies INTEGER DEFAULT 1 NOT NULL;

-- Changeset db/changelog/changes/est_32.yaml::est-change-32-3::limit
CREATE INDEX com_est_dim_valor_dim_agr_idx ON com_est_dimensio_valor(dimensio_id, agrupable);

CREATE INDEX com_est_dim_entorn_idx ON com_est_dimensio(entorn_app_id);

-- Changeset db/changelog/changes/est_32.yaml::est-change-32-4::limit
ALTER TABLE com_est_temps ADD CONSTRAINT com_est_data_unq UNIQUE (data);

-- Changeset db/changelog/changes/modify_tasca_primary_keys.yaml::tasca-change-01::limit
ALTER TABLE com_tasca_usuari DROP PRIMARY KEY DROP INDEX;

ALTER TABLE com_tasca_usuari ADD CONSTRAINT com_tasca_usuari_pk PRIMARY KEY (tasca_id, usuari);

-- Changeset db/changelog/changes/modify_tasca_primary_keys.yaml::tasca-change-02::limit
ALTER TABLE com_tasca_grup DROP PRIMARY KEY DROP INDEX;

ALTER TABLE com_tasca_grup ADD CONSTRAINT com_tasca_grup_pk PRIMARY KEY (tasca_id, grup);

-- Changeset db/changelog/changes/params.yaml::con-change-params-01::limit
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Estadístiques', 'Borrat', 'BOOLEAN', 'es.caib.comanda.stats.compactar.actiu', 'Activar compactat periòdic de dades estadístiques', NULL, NULL, NULL, 'true', 1, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Estadístiques', 'Borrat', 'CRON', 'es.caib.comanda.stats.compactar.cron', 'Quan executar el procés de compactat de dades estadístiques (CRON)', NULL, NULL, NULL, '0 0 3 * * *', 1, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'BOOLEAN', 'es.caib.comanda.monitor.buidat.actiu', 'Activar buidat periòdic de dades del monitor', NULL, NULL, NULL, 'true', 1, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'NUMERIC', 'es.caib.comanda.monitor.buidat.retencio.dies', 'Quants dies s''han de mantenir les dades del monitor en BBDD', NULL, NULL, NULL, '3', 1, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'NUMERIC', 'es.caib.comanda.monitor.buidat.periode.minuts', 'Cada quants minuts executar el procés de buidat de dades del monitor', NULL, NULL, NULL, '60', 1, NULL, NULL);

-- Changeset db/changelog/changes/params_scheduler.yaml::con-change-params-02::limit
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.scheduler.pool.size', 'Mida del pool de fils del planificador de tasques en segon pla', NULL, 'Defineix el nombre de fils disponibles al planificador de tasques en segon pla. Aquest component no executa la càrrega pesada, sinó que s’encarrega d’orquestrar i programar quan s’han de llançar les tasques cap al pool de executadors. Un valor massa baix pot provocar retards en la planificació si hi ha molts esdeveniments a la vegada, mentre que un valor massa alt pot consumir recursos innecessaris', NULL, '100', 0, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.worker.pool.size', 'Nombre de fils del pool de executors de tasques en segon pla', NULL, 'Indica quants fils poden executar tasques en paral·lel dins el pool d''executors. Cada fil pot processar una tasca alhora, de manera que aquest paràmetre determina la capacitat de processament simultani de l’aplicació. Si el valor és massa baix, les tasques quedaran en cua esperant torn; si és massa alt, es poden crear massa fils i saturar els recursos del servidor. Cal ajustar-lo segons la potència de la màquina i la càrrega de treball prevista, per aconseguir un equilibri entre rendiment i ús eficient dels recursos', NULL, '4', 0, NULL, NULL);

INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.worker.queue.size', 'Capacitat de la cua de tasques pendents', NULL, 'Estableix quantes tasques poden quedar en cua quan tots els fils del pool de executors estan ocupats. Aquesta cua actua com a coixí entre la càrrega d’entrada i la capacitat real de processament. Si la cua és massa petita i arriben moltes peticions, es poden rebutjar tasques amb errors de saturació. Si és massa gran, es poden acumular moltes tasques pendents i augmentar la latència de processament. El valor òptim depèn del volum de feina i del temps mitjà d’execució de cada tasca, i s’ha d’ajustar per evitar tant la pèrdua de peticions com l’acumulació excessiva', NULL, '200', 0, NULL, NULL);

