/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.model.v1.management;

import java.util.Objects;
import java.util.Arrays;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.caib.comanda.model.v1.management.AvisTipus;
import es.caib.comanda.model.v1.management.URL;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Representa un avís o notificació publicada a COMANDA
 */
@JsonPropertyOrder({
  Avis.JSON_PROPERTY_APP_CODI,
  Avis.JSON_PROPERTY_ENTORN_CODI,
  Avis.JSON_PROPERTY_IDENTIFICADOR,
  Avis.JSON_PROPERTY_TIPUS,
  Avis.JSON_PROPERTY_NOM,
  Avis.JSON_PROPERTY_DESCRIPCIO,
  Avis.JSON_PROPERTY_DATA_INICI,
  Avis.JSON_PROPERTY_DATA_FI,
  Avis.JSON_PROPERTY_REDIRECCIO,
  Avis.JSON_PROPERTY_RESPONSABLE,
  Avis.JSON_PROPERTY_GRUP,
  Avis.JSON_PROPERTY_USUARIS_AMB_PERMIS,
  Avis.JSON_PROPERTY_GRUPS_AMB_PERMIS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class Avis {
  public static final String JSON_PROPERTY_APP_CODI = "appCodi";
  @javax.annotation.Nullable
  private String appCodi;

  public static final String JSON_PROPERTY_ENTORN_CODI = "entornCodi";
  @javax.annotation.Nullable
  private String entornCodi;

  public static final String JSON_PROPERTY_IDENTIFICADOR = "identificador";
  @javax.annotation.Nullable
  private String identificador;

  public static final String JSON_PROPERTY_TIPUS = "tipus";
  @javax.annotation.Nullable
  private AvisTipus tipus;

  public static final String JSON_PROPERTY_NOM = "nom";
  @javax.annotation.Nullable
  private String nom;

  public static final String JSON_PROPERTY_DESCRIPCIO = "descripcio";
  @javax.annotation.Nullable
  private String descripcio;

  public static final String JSON_PROPERTY_DATA_INICI = "dataInici";
  @javax.annotation.Nullable
  private OffsetDateTime dataInici;

  public static final String JSON_PROPERTY_DATA_FI = "dataFi";
  @javax.annotation.Nullable
  private OffsetDateTime dataFi;

  public static final String JSON_PROPERTY_REDIRECCIO = "redireccio";
  @javax.annotation.Nullable
  private URL redireccio;

  public static final String JSON_PROPERTY_RESPONSABLE = "responsable";
  @javax.annotation.Nullable
  private String responsable;

  public static final String JSON_PROPERTY_GRUP = "grup";
  @javax.annotation.Nullable
  private String grup;

  public static final String JSON_PROPERTY_USUARIS_AMB_PERMIS = "usuarisAmbPermis";
  @javax.annotation.Nullable
  private List<String> usuarisAmbPermis = new ArrayList<>();

  public static final String JSON_PROPERTY_GRUPS_AMB_PERMIS = "grupsAmbPermis";
  @javax.annotation.Nullable
  private List<String> grupsAmbPermis = new ArrayList<>();

  public Avis() {
  }

  public Avis appCodi(@javax.annotation.Nullable String appCodi) {
    
    this.appCodi = appCodi;
    return this;
  }

  /**
   * Codi de l&#39;aplicació que publica l&#39;avís
   * @return appCodi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAppCodi() {
    return appCodi;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppCodi(@javax.annotation.Nullable String appCodi) {
    this.appCodi = appCodi;
  }

  public Avis entornCodi(@javax.annotation.Nullable String entornCodi) {
    
    this.entornCodi = entornCodi;
    return this;
  }

  /**
   * Codi de l&#39;entorn de l&#39;aplicació
   * @return entornCodi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENTORN_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEntornCodi() {
    return entornCodi;
  }


  @JsonProperty(value = JSON_PROPERTY_ENTORN_CODI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntornCodi(@javax.annotation.Nullable String entornCodi) {
    this.entornCodi = entornCodi;
  }

  public Avis identificador(@javax.annotation.Nullable String identificador) {
    
    this.identificador = identificador;
    return this;
  }

  /**
   * Identificador únic de l&#39;avís
   * @return identificador
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IDENTIFICADOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIdentificador() {
    return identificador;
  }


  @JsonProperty(value = JSON_PROPERTY_IDENTIFICADOR, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIdentificador(@javax.annotation.Nullable String identificador) {
    this.identificador = identificador;
  }

  public Avis tipus(@javax.annotation.Nullable AvisTipus tipus) {
    
    this.tipus = tipus;
    return this;
  }

  /**
   * Get tipus
   * @return tipus
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TIPUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AvisTipus getTipus() {
    return tipus;
  }


  @JsonProperty(value = JSON_PROPERTY_TIPUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTipus(@javax.annotation.Nullable AvisTipus tipus) {
    this.tipus = tipus;
  }

  public Avis nom(@javax.annotation.Nullable String nom) {
    
    this.nom = nom;
    return this;
  }

  /**
   * Títol de l&#39;avís
   * @return nom
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNom() {
    return nom;
  }


  @JsonProperty(value = JSON_PROPERTY_NOM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNom(@javax.annotation.Nullable String nom) {
    this.nom = nom;
  }

  public Avis descripcio(@javax.annotation.Nullable String descripcio) {
    
    this.descripcio = descripcio;
    return this;
  }

  /**
   * Descripció de l&#39;avís
   * @return descripcio
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescripcio() {
    return descripcio;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescripcio(@javax.annotation.Nullable String descripcio) {
    this.descripcio = descripcio;
  }

  public Avis dataInici(@javax.annotation.Nullable OffsetDateTime dataInici) {
    
    this.dataInici = dataInici;
    return this;
  }

  /**
   * Get dataInici
   * @return dataInici
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_INICI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDataInici() {
    return dataInici;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_INICI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataInici(@javax.annotation.Nullable OffsetDateTime dataInici) {
    this.dataInici = dataInici;
  }

  public Avis dataFi(@javax.annotation.Nullable OffsetDateTime dataFi) {
    
    this.dataFi = dataFi;
    return this;
  }

  /**
   * Get dataFi
   * @return dataFi
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DATA_FI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDataFi() {
    return dataFi;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA_FI, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataFi(@javax.annotation.Nullable OffsetDateTime dataFi) {
    this.dataFi = dataFi;
  }

  public Avis redireccio(@javax.annotation.Nullable URL redireccio) {
    
    this.redireccio = redireccio;
    return this;
  }

  /**
   * Get redireccio
   * @return redireccio
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REDIRECCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public URL getRedireccio() {
    return redireccio;
  }


  @JsonProperty(value = JSON_PROPERTY_REDIRECCIO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedireccio(@javax.annotation.Nullable URL redireccio) {
    this.redireccio = redireccio;
  }

  public Avis responsable(@javax.annotation.Nullable String responsable) {
    
    this.responsable = responsable;
    return this;
  }

  /**
   * Usuari responsable
   * @return responsable
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESPONSABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResponsable() {
    return responsable;
  }


  @JsonProperty(value = JSON_PROPERTY_RESPONSABLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResponsable(@javax.annotation.Nullable String responsable) {
    this.responsable = responsable;
  }

  public Avis grup(@javax.annotation.Nullable String grup) {
    
    this.grup = grup;
    return this;
  }

  /**
   * Grup responsable
   * @return grup
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGrup() {
    return grup;
  }


  @JsonProperty(value = JSON_PROPERTY_GRUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrup(@javax.annotation.Nullable String grup) {
    this.grup = grup;
  }

  public Avis usuarisAmbPermis(@javax.annotation.Nullable List<String> usuarisAmbPermis) {
    
    this.usuarisAmbPermis = usuarisAmbPermis;
    return this;
  }

  public Avis addUsuarisAmbPermisItem(String usuarisAmbPermisItem) {
    if (this.usuarisAmbPermis == null) {
      this.usuarisAmbPermis = new ArrayList<>();
    }
    this.usuarisAmbPermis.add(usuarisAmbPermisItem);
    return this;
  }

  /**
   * Usuaris amb permís de visualització
   * @return usuarisAmbPermis
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USUARIS_AMB_PERMIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getUsuarisAmbPermis() {
    return usuarisAmbPermis;
  }


  @JsonProperty(value = JSON_PROPERTY_USUARIS_AMB_PERMIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsuarisAmbPermis(@javax.annotation.Nullable List<String> usuarisAmbPermis) {
    this.usuarisAmbPermis = usuarisAmbPermis;
  }

  public Avis grupsAmbPermis(@javax.annotation.Nullable List<String> grupsAmbPermis) {
    
    this.grupsAmbPermis = grupsAmbPermis;
    return this;
  }

  public Avis addGrupsAmbPermisItem(String grupsAmbPermisItem) {
    if (this.grupsAmbPermis == null) {
      this.grupsAmbPermis = new ArrayList<>();
    }
    this.grupsAmbPermis.add(grupsAmbPermisItem);
    return this;
  }

  /**
   * Grups amb permís de visualització
   * @return grupsAmbPermis
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GRUPS_AMB_PERMIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getGrupsAmbPermis() {
    return grupsAmbPermis;
  }


  @JsonProperty(value = JSON_PROPERTY_GRUPS_AMB_PERMIS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrupsAmbPermis(@javax.annotation.Nullable List<String> grupsAmbPermis) {
    this.grupsAmbPermis = grupsAmbPermis;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Avis avis = (Avis) o;
    return Objects.equals(this.appCodi, avis.appCodi) &&
        Objects.equals(this.entornCodi, avis.entornCodi) &&
        Objects.equals(this.identificador, avis.identificador) &&
        Objects.equals(this.tipus, avis.tipus) &&
        Objects.equals(this.nom, avis.nom) &&
        Objects.equals(this.descripcio, avis.descripcio) &&
        Objects.equals(this.dataInici, avis.dataInici) &&
        Objects.equals(this.dataFi, avis.dataFi) &&
        Objects.equals(this.redireccio, avis.redireccio) &&
        Objects.equals(this.responsable, avis.responsable) &&
        Objects.equals(this.grup, avis.grup) &&
        Objects.equals(this.usuarisAmbPermis, avis.usuarisAmbPermis) &&
        Objects.equals(this.grupsAmbPermis, avis.grupsAmbPermis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appCodi, entornCodi, identificador, tipus, nom, descripcio, dataInici, dataFi, redireccio, responsable, grup, usuarisAmbPermis, grupsAmbPermis);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Avis {\n");
    sb.append("    appCodi: ").append(toIndentedString(appCodi)).append("\n");
    sb.append("    entornCodi: ").append(toIndentedString(entornCodi)).append("\n");
    sb.append("    identificador: ").append(toIndentedString(identificador)).append("\n");
    sb.append("    tipus: ").append(toIndentedString(tipus)).append("\n");
    sb.append("    nom: ").append(toIndentedString(nom)).append("\n");
    sb.append("    descripcio: ").append(toIndentedString(descripcio)).append("\n");
    sb.append("    dataInici: ").append(toIndentedString(dataInici)).append("\n");
    sb.append("    dataFi: ").append(toIndentedString(dataFi)).append("\n");
    sb.append("    redireccio: ").append(toIndentedString(redireccio)).append("\n");
    sb.append("    responsable: ").append(toIndentedString(responsable)).append("\n");
    sb.append("    grup: ").append(toIndentedString(grup)).append("\n");
    sb.append("    usuarisAmbPermis: ").append(toIndentedString(usuarisAmbPermis)).append("\n");
    sb.append("    grupsAmbPermis: ").append(toIndentedString(grupsAmbPermis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

