spring:
  application:
    name: comanda-gateway
  main:
    web-application-type: reactive
#  cloud:
#    gateway:
#      globalcors:
#        default-filters:
#          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
#        cors-configurations:
#          '[/**]':
#            allowed-origins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
#            allow-credentials: true
