eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://comanda:C0m4ndaEurek4@comanda-eureka:8761/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
    routes:
      - id: comanda-configuracio-service
        uri: lb://comanda-configuracio-service
        predicates:
          - Path=/api/v1/configuracio/**
          -
      - id: comanda-salut-service
        uri: lb://comanda-salut-service
        predicates:
          - Path=/api/v1/salut/**

      - id: comanda-recoleccio-service
        uri: lb://comanda-recoleccio-service
        predicates:
          - Path=/api/v1/recoleccio/**

      - id: comanda-alarmes-service
        uri: lb://comanda-alarmes-service
        predicates:
          - Path=/api/v1/alarmes/**

      - id: comanda-visualitzacio-service
        uri: lb://comanda-visualitzacio-service
        predicates:
          -Path=/api/v1/visualitzacio/**
