/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.api.v1.tasca;

import es.caib.comanda.service.v1.tasca.ApiException;
import es.caib.comanda.model.v1.tasca.Tasca;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AppComandaTasquesApi
 */
class AppComandaTasquesApiTest {

    private final AppComandaTasquesApi api = new AppComandaTasquesApi();

    /**
     * Consulta una tasca per identificador
     *
     * Retorna les dades d&#39;una tasca específica.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void consultarTascaTest() throws ApiException {
        //
        //String identificador = null;
        //
        //String appCodi = null;
        //
        //String entornCodi = null;
        //
        //Tasca response = api.consultarTasca(identificador, appCodi, entornCodi);

        // TODO: test validations
    }
    /**
     * Crea múltiples tasques
     *
     * Envia múltiples missatges de tipus Tasca a la cua JMS &#39;CUA_TASQUES&#39; una a una.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void crearMultiplesTasquesTest() throws ApiException {
        //
        //List<Tasca> tasca = null;
        //
        //String response = api.crearMultiplesTasques(tasca);

        // TODO: test validations
    }
    /**
     * Crea una tasca (enviament a la cua de tasques)
     *
     * Afegeix un missatge de tipus Tasca a la cua JMS &#39;CUA_TASQUES&#39;.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void crearTascaTest() throws ApiException {
        //
        //Tasca tasca = null;
        //
        //String response = api.crearTasca(tasca);

        // TODO: test validations
    }
    /**
     * Modifica múltiples tasques existents
     *
     * Envia múltiples missatges de modificació de tasques a la cua JMS &#39;CUA_TASQUES&#39; una a una. No es creen si no existeixen.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void modificarMultiplesTasquesTest() throws ApiException {
        //
        //List<Tasca> tasca = null;
        //
        //String response = api.modificarMultiplesTasques(tasca);

        // TODO: test validations
    }
    /**
     * Modifica una tasca existent
     *
     * Envia un missatge de modificació de tasca a la cua JMS &#39;CUA_TASQUES&#39;. No es crea si no existeix.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void modificarTascaTest() throws ApiException {
        //
        //String identificador = null;
        //
        //Tasca tasca = null;
        //
        //String response = api.modificarTasca(identificador, tasca);

        // TODO: test validations
    }
}
