/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package es.caib.comanda.service.management;

import java.util.concurrent.atomic.AtomicReference;

public class Configuration {
  public interface ApiClientFactory {
    ApiClient create();
  }

  public static final String VERSION = "1.0.0";

  private static final AtomicReference<ApiClient> defaultApiClient = new AtomicReference<ApiClient>();
  private static volatile ApiClientFactory apiClientFactory = new ApiClientFactory() {
    @Override
    public ApiClient create() {
      return new ApiClient();
    }
  };

  /**
   * Get the default API client, which would be used when creating API instances without providing an API client.
   *
   * @return Default API client
   */
  public static ApiClient getDefaultApiClient() {
    ApiClient client = defaultApiClient.get();
    if (client == null) {
      synchronized (defaultApiClient) {
        client = defaultApiClient.get();
        if (client == null) {
          client = apiClientFactory.create();
          defaultApiClient.set(client);
        }
      }
    }
    return client;
  }

  /**
   * Set the default API client, which would be used when creating API instances without providing an API client.
   *
   * @param apiClient API client
   */
  public static void setDefaultApiClient(ApiClient apiClient) {
    defaultApiClient.set(apiClient);
  }

  /**
   * set the callback used to create new ApiClient objects
   */
  public static void setApiClientFactory(ApiClientFactory factory) {
    if (factory == null) {
      throw new NullPointerException("factory");
    }
    apiClientFactory = factory;
  }

  private Configuration() {
  }
}
