/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.caib.comanda.service.management;

import java.text.DateFormat;
import java.util.Date;

public class JavaTimeFormatter {
  private DateFormat dateFormat = new RFC3339DateFormat();

  public DateFormat getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(DateFormat dateFormat) {
    this.dateFormat = dateFormat;
  }

  public Date parseOffsetDateTime(String str) {
    try {
      return dateFormat.parse(str);
    } catch (java.text.ParseException e) {
      throw new RuntimeException(e);
    }
  }

  public String formatOffsetDateTime(Date date) {
    return dateFormat.format(date);
  }
}
