/*
 * comanda-api-interna
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.1
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.caib.comanda.service.management;

import java.text.DateFormat;
import java.text.FieldPosition;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;

public class RFC3339DateFormat extends DateFormat {
  private static final long serialVersionUID = 1L;
  private static final TimeZone TIMEZONE_Z = TimeZone.getTimeZone("UTC");
  private static final String[] PARSE_PATTERNS = new String[] {
          "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
          "yyyy-MM-dd'T'HH:mm:ssZ",
          "yyyy-MM-dd'T'HH:mm:ss.SSS",
          "yyyy-MM-dd'T'HH:mm:ss"
  };

  public RFC3339DateFormat() {
    this.calendar = new GregorianCalendar(TIMEZONE_Z);
    this.numberFormat = new java.text.DecimalFormat();
  }

  @Override
  public Date parse(String source) {
    return parse(source, new ParsePosition(0));
  }

  @Override
  public Date parse(String source, ParsePosition pos) {
    if (source == null) {
      return null;
    }

    String normalized = normalizeOffset(source);
    int initialIndex = pos.getIndex();
    for (int i = 0; i < PARSE_PATTERNS.length; i++) {
      ParsePosition candidate = new ParsePosition(initialIndex);
      Date parsed = buildFormat(PARSE_PATTERNS[i]).parse(normalized, candidate);
      if (parsed != null && candidate.getIndex() == normalized.length()) {
        pos.setIndex(candidate.getIndex());
        pos.setErrorIndex(-1);
        return parsed;
      }
    }

    pos.setErrorIndex(initialIndex);
    return null;
  }

  @Override
  public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
    StringBuffer buffer = buildFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ").format(date, new StringBuffer(), fieldPosition);
    int length = buffer.length();
    if (length >= 5) {
      buffer.insert(length - 2, ':');
    }
    toAppendTo.append(buffer);
    return toAppendTo;
  }

  @Override
  public Object clone() {
    return new RFC3339DateFormat();
  }

  private DateFormat buildFormat(String pattern) {
    SimpleDateFormat sdf = new SimpleDateFormat(pattern);
    sdf.setLenient(false);
    sdf.setTimeZone(TIMEZONE_Z);
    return sdf;
  }

  private String normalizeOffset(String source) {
    if (source.endsWith("Z")) {
      return source.substring(0, source.length() - 1) + "+0000";
    }
    if (source.length() > 5) {
      char sign = source.charAt(source.length() - 6);
      if ((sign == '+' || sign == '-') && source.charAt(source.length() - 3) == ':') {
        return source.substring(0, source.length() - 3) + source.substring(source.length() - 2);
      }
    }
    return source;
  }
}
