import Skeleton from '@mui/material/Skeleton';
import Box from '@mui/material/Box';
import estils from '../estadistiques/WidgetEstils.ts';
import Typography from '@mui/material/Typography';
import * as React from 'react';
import Grid from '@mui/material/Grid';
import { useTranslation } from 'react-i18next';
import {
    dateFormatLocale,
    MuiDataGridColDef,
    useBaseAppContext,
} from 'reactlib';
import { Button, Paper, styled } from '@mui/material';
import { SalutField } from './SalutChipTooltip.tsx';
import {
    ENUM_APP_ESTAT_PREFIX,
    useGetColorByStatEnum,
    SalutEstatEnum,
    SalutModel,
    TITLE,
} from '../../types/salut.model.tsx';
import { ItemStateChip } from './SalutItemStateChip.tsx';
import {
    DataGridPro,
    GridRowId,
    GridSlots,
    GridTreeDataGroupingCell,
    isAutogeneratedRow,
    useGridApiRef,
} from '@mui/x-data-grid-pro';
import { PieChart, useDrawingArea } from '@mui/x-charts';
import DataGridNoRowsOverlay from '../../../lib/components/mui/datagrid/DataGridNoRowsOverlay.tsx';
import UpdownBarChart from './UpdownBarChart';
import { SalutData } from '../../pages/salut/Salut.tsx';
import { ErrorBoundary } from 'react-error-boundary';
import IconButton from '@mui/material/IconButton';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import KeyboardArrowUpIcon from '@mui/icons-material/KeyboardArrowUp';
import useSizeTracker from '../../hooks/useSizeTracker';
import {AppModel, EntornAppModel} from "../../types/app.model.tsx";
import {EntornModel} from "../../types/entorn.model.tsx";
import useTranslationStringKey from '../../hooks/useTranslationStringKey';
import { SalutErrorBoundaryFallback } from './SalutErrorBoundaryFallback';
import SalutIntegracionsChips from './SalutIntegracionsChips.tsx';
import SalutSubsistemesChips from './SalutSubsistemesChips.tsx';
import SalutMissatgesChips from './SalutMissatgesChips';
import { useTreeDataWithoutSwitch } from '../../hooks/treeData';

const StyledText = styled('text')(({ theme }) => ({
    fill: theme.palette.text.primary,
    textAnchor: 'middle',
    dominantBaseline: 'central',
    fontSize: 50,
    fontWeight: 'bold',
}));

function PieCenterLabel({ children }: { children: React.ReactNode }) {
    const { width, height, left, top } = useDrawingArea();
    return (
        <StyledText x={left + width / 2} y={top + height / 2}>
            {children}
        </StyledText>
    );
}

const UpdownPieChart: React.FC<{ salutLastItems: SalutModel[] }> = React.memo((props) => {
    const { salutLastItems } = props;
    const { t } = useTranslationStringKey();
    const getColorByStatEnum = useGetColorByStatEnum();

    const upValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.UP
    ).length;
    const warnValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.WARN
    ).length;
    const errorValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.ERROR
    ).length;
    const downValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.DOWN
    ).length;
    const degradedValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.DEGRADED
    ).length;
    const maintenanceValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.MAINTENANCE
    ).length;
    const unknownValue = salutLastItems.filter(
        (salutItem) => salutItem.appEstat === SalutEstatEnum.UNKNOWN
    ).length;

    return (
        <PieChart
            slotProps={{
                legend: {
                    sx: {
                        gap: 1,
                    },
                },
            }}
            series={[
                {
                    innerRadius: 50,
                    // outerRadius: 100,
                    // paddingAngle: 1,
                    highlightScope: { fade: 'global', highlight: 'item' },
                    highlighted: {
                        additionalRadius: 1,
                    },
                    // cornerRadius: 5,
                    data: [
                        {
                            id: SalutEstatEnum.UP,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.UP + TITLE)} (${upValue})`,
                            value: upValue,
                            color: getColorByStatEnum(SalutEstatEnum.UP),
                        },
                        {
                            id: SalutEstatEnum.WARN,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.WARN + TITLE)} (${warnValue})`,
                            value: warnValue,
                            color: getColorByStatEnum(SalutEstatEnum.WARN),
                        },
                        {
                            id: SalutEstatEnum.DEGRADED,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.DEGRADED + TITLE)} (${degradedValue})`,
                            value: degradedValue,
                            color: getColorByStatEnum(SalutEstatEnum.DEGRADED),
                        },
                        {
                            id: SalutEstatEnum.ERROR,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.ERROR + TITLE)} (${errorValue})`,
                            value: errorValue,
                            color: getColorByStatEnum(SalutEstatEnum.ERROR),
                        },
                        {
                            id: SalutEstatEnum.DOWN,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.DOWN + TITLE)} (${downValue})`,
                            value: downValue,
                            color: getColorByStatEnum(SalutEstatEnum.DOWN),
                        },
                        {
                            id: SalutEstatEnum.MAINTENANCE,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.MAINTENANCE + TITLE)} (${maintenanceValue})`,
                            value: maintenanceValue,
                            color: getColorByStatEnum(SalutEstatEnum.MAINTENANCE),
                        },
                        {
                            id: SalutEstatEnum.UNKNOWN,
                            label: `${t(ENUM_APP_ESTAT_PREFIX + SalutEstatEnum.UNKNOWN + TITLE)} (${unknownValue})`,
                            value: unknownValue,
                            color: getColorByStatEnum(SalutEstatEnum.UNKNOWN),
                        },
                    ],
                },
            ]}
        >
            <PieCenterLabel> {salutLastItems.length}</PieCenterLabel>
        </PieChart>
    );
});

const useTreeDataEntornAppRenderCell = (apps?: AppModel[]) => {
    return React.useCallback((params: any) => {
        const app = apps?.find((app) => app.id === parseInt(params.formattedValue));
        if (typeof params.id === 'number' || app == null) {
            return <GridTreeDataGroupingCell {...params} />;
        }
        return <GridTreeDataGroupingCell
            {...params}
            formattedValue={
                <Box
                    sx={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '8px',
                    }}>
                    {app.logo && <img
                        src={'data:image/png;base64,' + app.logo}
                        alt="Logo"
                        style={{ height: '48px' }}/>}
                    {app.nom}
                </Box>
            }
        />;
    }, [apps]);
}

const AppDataTable: React.FC<{
    salutLastItems: SalutModel[];
    apps?: AppModel[];
    entorns?: EntornModel[];
    entornApps: EntornAppModel[];
    groupedApp?: AppModel;
    groupedEntorn?: EntornModel;
    isGroupingDisabled: boolean;
}> = React.memo((props) => {
    const { salutLastItems, apps, entorns, entornApps, groupedEntorn, isGroupingDisabled } = props;
    const { t } = useTranslation();
    const { getLinkComponent } = useBaseAppContext();
    const gridApiRef = useGridApiRef();

    const treeDataRenderCell =  useTreeDataEntornAppRenderCell(apps);
    const getTreeDataPath = React.useCallback(
        (row: any) => [row.app.id, row.entorn.description],
        []
    );
    const groupingColDefAdditionalProps = React.useMemo(
        () => ({ renderCell: treeDataRenderCell }),
        [treeDataRenderCell]
    );
    const { dataGridProps: treeDataGridProps } = useTreeDataWithoutSwitch(
        getTreeDataPath,
        gridApiRef,
        t($ => $.page.salut.apps.column.group),
        0.7,
        true,
        isGroupingDisabled,
        groupingColDefAdditionalProps);

    const findSalutItem: (id: GridRowId) => SalutModel | null = React.useCallback(
        (id: GridRowId) => {
            return salutLastItems?.find((entry: SalutModel) => entry.entornAppId === id) ?? null;
        },
        [salutLastItems]
    );

    const renderItemStateChip = React.useCallback(
        (id: GridRowId, salutField: SalutField.APP_ESTAT | SalutField.BD_ESTAT) => {
            const salutItem: SalutModel | null = findSalutItem(id);
            if (salutItem == null) {
                return undefined;
            }
            return (
                <ItemStateChip
                    sx={{ mr: 1 }}
                    salutField={salutField}
                    salutStatEnum={salutItem[salutField] as SalutEstatEnum}
                />
            );
        },
        [findSalutItem]
    );

    const columns = React.useMemo(() => {
        const rawColumns: (MuiDataGridColDef | null)[] = [
            !isGroupingDisabled
                ? {
                      flex: 0.5,
                      field: 'nomLogo',
                      headerName: t($ => $.page.salut.apps.column.group),
                      minWidth: 150,
                      valueGetter: (_value, row) => {
                          if (isAutogeneratedRow(row)) return;
                          const entorn =
                              entorns != null &&
                              entorns.find(entorn => entorn.id === row.entorn.id);
                          const app = apps != null && apps.find(app => app.id === row.app.id);
                          if (!entorn || !app) return;

                          const isGroupedByEntorn = groupedEntorn != null;
                          if (isGroupedByEntorn) return app.nom;
                          return entorn.nom ?? entorn.codi;
                      },
                      renderCell: params => {
                          if (isAutogeneratedRow(params.row)) return;
                          const isGroupedByEntorn = groupedEntorn != null;

                          const app =
                              apps != null && apps.find(app => app.id === params.row.app.id);
                          if (isGroupedByEntorn && app)
                              return (
                                  <Box
                                      sx={{
                                          display: 'flex',
                                          alignItems: 'center',
                                          gap: '8px',
                                      }}
                                  >
                                      {app.logo && (
                                          <img
                                              src={'data:image/png;base64,' + app.logo}
                                              alt="Logo"
                                              style={{ height: '48px' }}
                                          />
                                      )}
                                      {params.value}
                                  </Box>
                              );
                      },
                  }
                : null,
            {
                flex: 0.3,
                field: 'estat',
                headerName: t($ => $.page.salut.apps.column.estat),
                minWidth: 100,
                renderCell: ({ id }) => renderItemStateChip(id, SalutField.APP_ESTAT),
            },
            {
                flex: 0.3,
                field: 'infoData',
                headerName: t($ => $.page.salut.apps.column.infoData),
                description: t($ => $.page.salut.apps.column.infoDataDescription),
                minWidth: 160,
                renderCell: ({ id }) => {
                    const salutItem: SalutModel | null = findSalutItem(id);
                    if (salutItem == null) {
                        return '';
                    }
                    return salutItem?.data
                        ? dateFormatLocale(salutItem?.data, true)
                        : t($ => $.page.salut.nd);
                },
            },
            {
                flex: 0.1,
                field: 'versio',
                headerName: t($ => $.page.salut.apps.column.versio),
                minWidth: 90,
            },
            {
                flex: 0.3,
                field: 'revisioSimplificat',
                headerName: t($ => $.page.salut.apps.column.revisio),
                minWidth: 100,
            },
            {
                flex: 0.3,
                field: 'bd',
                headerName: t($ => $.page.salut.apps.column.bd),
                minWidth: 128,
                renderCell: ({ id }) => renderItemStateChip(id, SalutField.BD_ESTAT),
            },
            {
                flex: 0.3,
                field: 'latencia',
                headerName: t($ => $.page.salut.apps.column.latencia),
                minWidth: 100,
                valueGetter: (_value, row) => {
                    const salutItem: SalutModel | null = findSalutItem(row.id);
                    if (salutItem == null) {
                        return '';
                    }
                    return salutItem?.appLatencia != null
                        ? salutItem.appLatencia + ' ms'
                        : t($ => $.page.salut.nd);
                },
            },
            {
                flex: 0.1,
                field: SalutModel.INTEGRACIONS,
                headerName: t($ => $.page.salut.apps.column.integ),
                minWidth: 160,
                renderCell: ({ id }) => {
                    const salutItem: SalutModel | null = findSalutItem(id);

                    if (!salutItem) {
                        return null;
                    }

                    return <SalutIntegracionsChips salutItem={salutItem} />;
                },
            },
            {
                flex: 0.2,
                field: SalutModel.SUBSISTEMES,
                headerName: t($ => $.page.salut.apps.column.subsis),
                minWidth: 160,
                renderCell: ({ id }) => {
                    const salutItem: SalutModel | null = findSalutItem(id);

                    if (!salutItem) {
                        return null;
                    }
                    return <SalutSubsistemesChips salutItem={salutItem} />;
                },
            },
            {
                flex: 0.1,
                field: 'msgs',
                headerName: t($ => $.page.salut.apps.column.msgs),
                minWidth: 130,
                renderCell: ({ id }) => {
                    const salutItem: SalutModel | null = findSalutItem(id);

                    if (!salutItem) {
                        return null;
                    }
                    return <SalutMissatgesChips salutItem={salutItem} />;
                },
            },
            {
                field: 'detalls',
                headerName: '',
                minWidth: 100,
                renderCell: params =>
                    params.rowNode.type !== 'group' && (
                        <Button
                            variant="contained"
                            size="small"
                            component={getLinkComponent()}
                            to={'appinfo/' + params.id}
                        >
                            {t($ => $.page.salut.apps.detalls)}
                        </Button>
                    ),
            },
        ];
        return rawColumns.filter(column => column !== null);
    }, [
        apps,
        entorns,
        findSalutItem,
        getLinkComponent,
        groupedEntorn,
        isGroupingDisabled,
        renderItemStateChip,
        t,
    ]);

    return (
        <DataGridPro
            apiRef={gridApiRef}
            columns={columns}
            rows={entornApps}
            hideFooter
            slots={{
                noRowsOverlay: DataGridNoRowsOverlay as GridSlots['noRowsOverlay'],
            }}
            {...treeDataGridProps}
        />
    );
});

export const SalutWidgetTitle: React.FC<{
    app?: AppModel;
    entorn?: EntornModel;
    loading?: boolean;
    midaFontTitol?: number;
}> = ({ app, entorn, loading, midaFontTitol }) => {
    const { t } = useTranslation();
    const titleEstils = {
        ...estils.titleText,
        fontSize: midaFontTitol ? `${midaFontTitol}px` : estils.titleText.fontSize,
    };

    const titleText = app?.nom || entorn?.nom || t($ => $.page.salut.groupingSelect.titleNoGrouping);

    return (
        <Box>
            {loading ? (
                <>
                    <Skeleton width="70%" height={32} />
                    <Box sx={estils.iconContainer}>
                        <Skeleton width={40} height={24} />
                    </Box>
                </>
            ) : (
                <>
                    {
                        <Box
                            sx={{
                                display: 'flex',
                                alignItems: 'center',
                                gap: '8px',
                                height: '38px',
                            }}
                        >
                            {app?.logo && (
                                <img
                                    src={'data:image/png;base64,' + app.logo}
                                    alt={'Logo ' + app.nom}
                                    style={{ height: '100%' }}
                                />
                            )}
                            <Typography sx={titleEstils}>{titleText}</Typography>
                        </Box>
                    }
                </>
            )}
        </Box>
    );
};

export const SalutWidgetContent: React.FC<{
    expanded: boolean;
    setExpanded: (expanded: boolean) => void;
    isGroupingDisabled: boolean;
    salutLastItems: SalutModel[];
    agrupacio: string;
    estats: SalutData['estats'];
    loading?: boolean;
    groupedApp?: AppModel;
    groupedEntorn?: EntornModel;
    apps?: AppModel[];
    entorns?: EntornModel[];
    entornApps: EntornAppModel[];
    grupsDates: string[];
}> = ({
    expanded: expandedProp,
    setExpanded,
    isGroupingDisabled,
    salutLastItems,
    agrupacio,
    estats,
    loading,
    groupedApp,
    groupedEntorn,
    entornApps,
    apps,
    entorns,
    grupsDates,
}) => {
    const { size: trackedGridSize, refCallback: trackedGridRef } = useSizeTracker(100);
    const expanded = !isGroupingDisabled ? expandedProp : true;

    if (loading)
        return (
            <>
                <Box sx={{ ...estils.contentText(true), width: '10em' }}>
                    <Skeleton width="100%" height={80} />
                </Box>
                <Box sx={{ ...estils.contentText(true), width: '4em' }}>
                    <Skeleton width="100%" height={20} />
                </Box>
            </>
        );

    return (
        <Box
            sx={{
                height: !expanded ? '220px' : trackedGridSize?.height + 'px',
                transition: 'height 0.3s ease-in-out',
                overflow: 'hidden',
                position: 'relative',
            }}
        >
            <Grid ref={trackedGridRef} container spacing={2}>
                <Grid
                    size={{ xs: 12, sm: 11, md: 11, lg: 3 }}
                    sx={{ display: 'flex', flexDirection: 'column', height: '200px' }}
                >
                    <SalutWidgetTitle app={groupedApp} entorn={groupedEntorn} />
                    <Box
                        sx={{
                            height: '100%',
                            minHeight: 0,
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                        }}
                    >
                        <ErrorBoundary fallback={<SalutErrorBoundaryFallback />}>
                            <UpdownPieChart salutLastItems={salutLastItems} />
                        </ErrorBoundary>
                    </Box>
                </Grid>
                <Grid size={{ xs: 12, sm: 12, md: 12, lg: 9 }} sx={{ height: '200px' }}>
                    <ErrorBoundary fallback={<SalutErrorBoundaryFallback />}>
                        <UpdownBarChart
                            agrupacio={agrupacio}
                            estats={estats}
                            grupsDates={grupsDates}
                        />
                    </ErrorBoundary>
                </Grid>
                {expanded && (
                    <Grid size={12}>
                        <AppDataTable
                            groupedApp={groupedApp}
                            groupedEntorn={groupedEntorn}
                            isGroupingDisabled={isGroupingDisabled}
                            apps={apps}
                            entorns={entorns}
                            entornApps={entornApps}
                            salutLastItems={salutLastItems}
                        />
                    </Grid>
                )}
                {!isGroupingDisabled && (
                    <Grid
                        size={12}
                        sx={{
                            display: 'flex',
                            justifyContent: 'center',
                            position: 'absolute',
                            bottom: '0px',
                            width: '100%',
                        }}
                    >
                        <IconButton onClick={() => setExpanded(!expanded)}>
                            {expanded ? <KeyboardArrowUpIcon /> : <KeyboardArrowDownIcon />}
                        </IconButton>
                    </Grid>
                )}
                {/* Botón de expansión duplicado para ocupar la altura del botón original con position: absolute */}
                <Grid size={12}>
                    <IconButton>
                        <KeyboardArrowUpIcon
                            sx={{
                                visibility: 'hidden',
                            }}
                        />
                    </IconButton>
                </Grid>
            </Grid>
        </Box>
    );
};

export const SalutLlistat = ({
    salutGroups,
    grupsDates,
    agrupacio,
    apps,
    entorns,
    setExpanded,
    isExpanded,
}: {
    apps?: AppModel[];
    entorns?: EntornModel[];
    salutGroups: SalutData[];
    grupsDates?: string[];
    agrupacio?: string;
    springFilter?: string;
    setExpanded: (expand: boolean, context: SalutData) => void;
    isExpanded: (salutGroup: SalutData) => boolean;
}) => {
    if (!salutGroups.length || grupsDates == null || agrupacio == null) return;

    return (
        <>
            {salutGroups.map((salutGroup, index) => {
                // Si no se ha agrupado por app ni entorn, la agrupación debe estar desactivada
                const isGroupingDisabled = salutGroup.groupedApp == null && salutGroup.groupedEntorn == null;
                return (
                    <Paper key={index} elevation={1} sx={{ px: 2, pt: 1, marginBottom: 1 }}>
                        <SalutWidgetContent
                            expanded={isExpanded(salutGroup)}
                            setExpanded={(expand) => setExpanded(expand, salutGroup)}
                            isGroupingDisabled={isGroupingDisabled}
                            salutLastItems={salutGroup.salutLastItems}
                            agrupacio={agrupacio}
                            estats={salutGroup.estats}
                            groupedApp={salutGroup.groupedApp}
                            groupedEntorn={salutGroup.groupedEntorn}
                            apps={apps}
                            entorns={entorns}
                            entornApps={salutGroup.entornApps}
                            grupsDates={grupsDates}
                        />
                    </Paper>
                );
            })}
        </>
    );
};
