import { fireEvent, render, screen } from '@testing-library/react';
import React from 'react';
import { describe, expect, it, vi } from 'vitest';
import {
    SalutLlistat,
    SalutWidgetContent,
    SalutWidgetTitle,
} from './SalutPrincipalWidgets';

const baseSalutWidgetContentProps = {
    expanded: false,
    setExpanded: () => undefined,
    parentContainerFullWidth: 1024,
    isGroupingDisabled: false,
    salutLastItems: [] as any[],
    agrupacio: 'HORA',
    estats: {} as any,
    entornApps: [] as any[],
    grupsDates: ['2026-03-13'],
};

vi.mock('react-i18next', () => ({
    useTranslation: () => ({
        t: (selector: any) =>
            selector({
                page: {
                    salut: {
                        groupingSelect: { titleNoGrouping: 'Sense agrupació' },
                        apps: {
                            column: {
                                group: 'Grup',
                                estat: 'Estat',
                                infoData: 'Data',
                                infoDataDescription: 'Info data',
                                versio: 'Versió',
                                revisio: 'Revisió',
                                bd: 'BD',
                                latencia: 'Latència',
                                integ: 'Integracions',
                                subsis: 'Subsistemes',
                                msgs: 'Missatges',
                            },
                            detalls: 'Detalls',
                        },
                        nd: 'N/D',
                    },
                },
            }),
    }),
}));

vi.mock('../../hooks/useTranslationStringKey', () => ({
    default: () => ({
        t: (key: string) => `tr:${key}`,
    }),
}));

vi.mock('react-error-boundary', () => ({
    ErrorBoundary: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

vi.mock('./UpdownBarChart', () => ({
    default: ({ agrupacio }: { agrupacio: string }) => <div>{`BarChart:${agrupacio}`}</div>,
}));

vi.mock('./SalutErrorBoundaryFallback', () => ({
    SalutErrorBoundaryFallback: () => <div>Error fallback</div>,
}));

vi.mock('../../hooks/useSizeTracker', () => ({
    default: () => ({
        size: { height: 240 },
        refCallback: () => undefined,
    }),
}));

vi.mock('@mui/x-charts', () => ({
    PieChart: ({ children }: { children?: React.ReactNode }) => <svg>{children}</svg>,
    useDrawingArea: () => ({ width: 100, height: 100, left: 0, top: 0 }),
}));

vi.mock('@mui/x-data-grid-pro', () => ({
    DataGridPro: () => <div>DataGrid</div>,
    GridTreeDataGroupingCell: () => <div>GroupingCell</div>,
    isAutogeneratedRow: () => false,
    useGridApiRef: () => ({ current: {} }),
    GridSlots: {},
}));

vi.mock('./SalutItemStateChip.tsx', () => ({
    ItemStateChip: () => <div>ItemStateChip</div>,
}));

vi.mock('./SalutIntegracionsChips.tsx', () => ({
    default: () => <div>Integracions</div>,
}));

vi.mock('./SalutSubsistemesChips.tsx', () => ({
    default: () => <div>Subsistemes</div>,
}));

vi.mock('./SalutMissatgesChips', () => ({
    default: () => <div>Missatges</div>,
}));

vi.mock('../../hooks/treeData', () => ({
    useTreeDataWithoutSwitch: () => ({ dataGridProps: {} }),
}));

vi.mock('../../hooks/useDataGridLocale', () => ({
    default: () => ({}),
}));

vi.mock('reactlib', () => ({
    dateFormatLocale: () => '13/03/2026',
    useBaseAppContext: () => ({
        getLinkComponent: () => 'a',
    }),
    useCloseDialogButtons: () => [
        {
            label: 'Close',
            onClick: vi.fn(),
            variant: 'outlined',
            color: 'primary',
        },
    ],
    MuiDialog: ({ children, open }: { children: React.ReactNode, open: boolean }) => open ? <div role="dialog">{children}</div> : null,
}));

describe('SalutWidgetTitle', () => {
    it('SalutWidgetTitle_quanEstaCarregant_mostraElsSkeletons', () => {
        // Comprova que el títol del widget entra en mode placeholder mentre encara s'està carregant.
        const { container } = render(<SalutWidgetTitle loading={true} />);

        expect(container.querySelectorAll('.MuiSkeleton-root').length).toBeGreaterThan(0);
    });

    it('SalutWidgetTitle_quanRepApp_mostraElNomIElLogo', () => {
        // Comprova que el títol del widget mostra el nom i el logo de l'aplicació agrupada.
        render(
            <SalutWidgetTitle
                app={{ nom: 'Comanda', logo: 'YmFzZTY0' } as any}
                loading={false}
            />
        );

        expect(screen.getByText('Comanda')).toBeInTheDocument();
        expect(screen.getByAltText('Logo Comanda')).toBeInTheDocument();
    });

    it('SalutWidgetTitle_quanNoHiHaAppNiEntorn_mostraElTextPerDefecte', () => {
        // Verifica que el component usa el títol per defecte quan no hi ha agrupació activa.
        render(<SalutWidgetTitle loading={false} />);

        expect(screen.getByText('Sense agrupació')).toBeInTheDocument();
    });

    it('SalutWidgetTitle_quanLaAgrupacioEsPerEntorn_mostraElNomDelEntorn', () => {
        // Comprova que el títol del widget també suporta agrupacions per entorn quan no hi ha app agrupada.
        render(
            <SalutWidgetTitle
                entorn={{ nom: 'Producció', codi: 'PRO' } as any}
                loading={false}
            />
        );

        expect(screen.getByText('Producció')).toBeInTheDocument();
    });
});

describe('SalutWidgetContent', () => {
    it('SalutWidgetContent_quanEstaCarregant_mostraElsSkeletonsDelContingut', () => {
        // Verifica que el contingut del widget mostra placeholders quan encara no hi ha dades disponibles.
        const { container } = render(
            <SalutWidgetContent
                {...baseSalutWidgetContentProps}
                loading={true}
            />
        );

        expect(container.querySelectorAll('.MuiSkeleton-root').length).toBeGreaterThan(0);
    });

    it('SalutWidgetContent_quanNoEstaExpandit_mostraElsGraficsiElBotoDexpandir', () => {
        // Comprova que el component renderitza els gràfics principals i el botó per expandir el llistat.
        const setExpanded = vi.fn();
        render(
            <SalutWidgetContent
                {...baseSalutWidgetContentProps}
                setExpanded={setExpanded}
                salutLastItems={[{ appEstat: 'UP' } as any]}
            />
        );

        expect(screen.getByText('1')).toBeInTheDocument();
        expect(screen.getByText('BarChart:HORA')).toBeInTheDocument();
        fireEvent.click(screen.getByTestId('KeyboardArrowDownIcon').closest('button') as HTMLButtonElement);
        expect(setExpanded).toHaveBeenCalledWith(true, expect.any(String));
    });

    it('SalutWidgetContent_quanEstaExpandit_mostraElDataGrid', () => {
        // Verifica que l'estat expandit inclou el llistat detallat de dades.
        render(
            <SalutWidgetContent
                {...baseSalutWidgetContentProps}
                expanded={true}
                salutLastItems={[{ appEstat: 'UP' } as any]}
            />
        );

        expect(screen.getByText('DataGrid')).toBeInTheDocument();
    });

    it('SalutWidgetContent_quanNoHiHaItems_mostraElComptadorAZero', () => {
        // Verifica que el resum visual continua funcionant quan no hi ha cap item de salut.
        render(
            <SalutWidgetContent
                {...baseSalutWidgetContentProps}
                isGroupingDisabled={true}
            />
        );

        expect(screen.getByText('0')).toBeInTheDocument();
    });

    it('SalutWidgetContent_quanLagrupacioEstaDesactivada_noMostraElBotoDexpandir', () => {
        // Comprova que quan no hi ha agrupació el widget força l’estat expandit i oculta el control d’expansió.
        render(
            <SalutWidgetContent
                {...baseSalutWidgetContentProps}
                isGroupingDisabled={true}
                salutLastItems={[{ appEstat: 'UP' } as any]}
            />
        );

        expect(screen.getByText('DataGrid')).toBeInTheDocument();
        expect(screen.queryByTestId('KeyboardArrowDownIcon')).not.toBeInTheDocument();
    });
});

describe('SalutLlistat', () => {
    it('SalutLlistat_quanNoHiHaGrups_noRenderitzaCapContingut', () => {
        // Comprova que el llistat retorna buit si no hi ha grups o metadades mínimes.
        const { container } = render(
            <SalutLlistat
                salutGroups={[]}
                setExpanded={() => undefined}
                isExpanded={() => false}
            />
        );

        expect(container).toBeEmptyDOMElement();
    });

    it('SalutLlistat_quanHiHaGrups_renderitzaUnBlocPerCadaGrup', () => {
        // Verifica que el component crea una targeta per a cada grup de salut disponible.
        render(
            <SalutLlistat
                salutGroups={[
                    {
                        groupedApp: { nom: 'APP 1' },
                        groupedEntorn: null,
                        salutLastItems: [{ appEstat: 'UP' }],
                        estats: {},
                        entornApps: [],
                    },
                    {
                        groupedApp: { nom: 'APP 2' },
                        groupedEntorn: null,
                        salutLastItems: [{ appEstat: 'WARN' }],
                        estats: {},
                        entornApps: [],
                    },
                ] as any}
                grupsDates={['2026-03-13']}
                agrupacio="HORA"
                setExpanded={() => undefined}
                isExpanded={() => false}
            />
        );

        expect(screen.getByText('APP 1')).toBeInTheDocument();
        expect(screen.getByText('APP 2')).toBeInTheDocument();
    });

    it('SalutLlistat_quanNoHiHaAgrupacio_renderitzaElBlocExpanditSenseControl', () => {
        // Comprova que un grup sense app ni entorn agrupats es mostra directament expandit.
        render(
            <SalutLlistat
                salutGroups={[
                    {
                        groupedApp: null,
                        groupedEntorn: null,
                        salutLastItems: [{ appEstat: 'UP' }],
                        estats: {},
                        entornApps: [],
                    },
                ] as any}
                grupsDates={['2026-03-13']}
                agrupacio="HORA"
                setExpanded={() => undefined}
                isExpanded={() => false}
            />
        );

        expect(screen.getByText('Sense agrupació')).toBeInTheDocument();
        expect(screen.getByText('DataGrid')).toBeInTheDocument();
        expect(screen.queryByTestId('KeyboardArrowDownIcon')).not.toBeInTheDocument();
    });
});
