-- =============================================
-- Module: comanda-ms-configuracio
-- =============================================

-- Table: com_entorn
CREATE TABLE com_entorn (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(16 CHAR) NOT NULL,
    nom VARCHAR2(255 CHAR)
);

-- Table: com_app
CREATE TABLE com_app (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(16 CHAR) NOT NULL,
    nom VARCHAR2(100 CHAR) NOT NULL,
    descripcio VARCHAR2(1000 CHAR),
    activa NUMBER(1),
    logo BLOB,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_entorn_app
CREATE TABLE com_entorn_app (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    entorn_id NUMBER(38) NOT NULL,
    app_id NUMBER(38) NOT NULL,
    info_url VARCHAR2(200 CHAR) NOT NULL,
    info_data TIMESTAMP,
    salut_url VARCHAR2(200 CHAR) NOT NULL,
    salut_auth NUMBER(1) DEFAULT 0 NOT NULL,
    estadistica_info_url VARCHAR2(200 CHAR),
    estadistica_url VARCHAR2(200 CHAR),
    estadistica_cron VARCHAR2(40 CHAR),
    estadistica_auth NUMBER(1) DEFAULT 0 NOT NULL,
    versio VARCHAR2(10 CHAR),
    jdk_version VARCHAR2(10 CHAR),
    revisio VARCHAR2(64 CHAR),
    compactable NUMBER(1) DEFAULT 0 NOT NULL,
    compactacio_setmanal NUMBER(19),
    compactacio_mensual NUMBER(19),
    eliminacio NUMBER(19),
    activa NUMBER(1),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_integracio
CREATE TABLE com_integracio (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(32 CHAR) NOT NULL,
    nom VARCHAR2(255 CHAR) NOT NULL,
    logo BLOB,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_app_integracio
CREATE TABLE com_app_integracio (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    integracio_id NUMBER(38) NOT NULL,
    entorn_app_id NUMBER(38) NOT NULL,
    activa NUMBER(1),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_app_subsistema
CREATE TABLE com_app_subsistema (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(64 CHAR) NOT NULL,
    nom VARCHAR2(255 CHAR) NOT NULL,
    actiu NUMBER(1),
    entorn_app_id NUMBER(38) NOT NULL,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Creació de taula: com_app_context
CREATE TABLE com_app_context (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    created_by       VARCHAR2(64 CHAR)    NOT NULL,
    created_date     TIMESTAMP            NOT NULL,
    lastmod_by       VARCHAR2(64 CHAR),
    lastmod_date     TIMESTAMP,
    v                NUMBER(19),
    codi             VARCHAR2(64 CHAR)    NOT NULL,
    nom              VARCHAR2(255 CHAR)   NOT NULL,
    path             VARCHAR2(255 CHAR)   NOT NULL,
    api              VARCHAR2(255 CHAR),
    actiu            NUMBER(1)            NOT NULL,
    entorn_app_id    NUMBER(19),
    CONSTRAINT com_app_context_pk PRIMARY KEY (id),
    CONSTRAINT com_app_context_actiu_ck CHECK (actiu IN (0,1))
);

-- Creació de taula: com_app_ctx_manual
CREATE TABLE com_app_ctx_manual (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    nom        VARCHAR2(128 CHAR)   NOT NULL,
    path       VARCHAR2(255 CHAR)   NOT NULL,
    app_ctx_id NUMBER(19)           NOT NULL,
    CONSTRAINT com_app_ctx_manual_pk PRIMARY KEY (id)
);

-- Creació de taula: com_parametre
CREATE TABLE com_parametre
(
    id             NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    grup           VARCHAR2(128) NOT NULL,
    subgrup        VARCHAR2(128) NOT NULL,
    tipus          VARCHAR2(16) NOT NULL,
    codi           VARCHAR2(128) NOT NULL,
    nom            VARCHAR2(128) NOT NULL,
    nom_key        VARCHAR2(128),
    descripcio     VARCHAR2(1024),
    descripcio_key VARCHAR2(128),
    valor          VARCHAR2(255),
    editable       NUMBER(1),
    grup_key       VARCHAR2(128),
    subgrup_key    VARCHAR2(128)
);

-- =============================================
-- Module: comanda-ms-salut
-- =============================================

-- Table: com_salut
CREATE TABLE com_salut (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    entorn_app_id NUMBER(38) NOT NULL,
    data TIMESTAMP NOT NULL,
    app_estat VARCHAR2(20 CHAR) NOT NULL,
    app_latencia NUMBER(10),
    bd_estat VARCHAR2(20 CHAR),
    bd_latencia NUMBER(10),
    tipus_registre VARCHAR2(10 CHAR) DEFAULT 'MINUT' NOT NULL,
    app_count_up NUMBER(19) DEFAULT 0,
    app_count_warn NUMBER(19) DEFAULT 0,
    app_count_degraded NUMBER(19) DEFAULT 0,
    app_count_down NUMBER(19) DEFAULT 0,
    app_count_error NUMBER(19) DEFAULT 0,
    app_count_maintenance NUMBER(19) DEFAULT 0,
    app_count_unknown NUMBER(19) DEFAULT 0,
    bd_count_up NUMBER(19) DEFAULT 0,
    bd_count_warn NUMBER(19) DEFAULT 0,
    bd_count_degraded NUMBER(19) DEFAULT 0,
    bd_count_down NUMBER(19) DEFAULT 0,
    bd_count_error NUMBER(19) DEFAULT 0,
    bd_count_maintenance NUMBER(19) DEFAULT 0,
    bd_count_unknown NUMBER(19) DEFAULT 0,
    app_latencia_mitjana NUMBER(19),
    app_latencia_num_elements NUMBER(19),
    bd_latencia_mitjana NUMBER(19),
    bd_latencia_num_elements NUMBER(19),
    data_app TIMESTAMP,
    num_elements NUMBER(19),
    peticio_error NUMBER(1) NOT NULL
);

-- Table: com_salut_integracio
CREATE TABLE com_salut_integracio (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(32 CHAR) NOT NULL,
    estat VARCHAR2(20 CHAR) NOT NULL,
    latencia NUMBER(10),
    total_ok NUMBER(10) NOT NULL,
    total_error NUMBER(10) NOT NULL,
    salut_id NUMBER(38) NOT NULL,
    count_up NUMBER(19) DEFAULT 0,
    count_warn NUMBER(19) DEFAULT 0,
    count_degraded NUMBER(19) DEFAULT 0,
    count_down NUMBER(19) DEFAULT 0,
    count_error NUMBER(19) DEFAULT 0,
    count_maintenance NUMBER(19) DEFAULT 0,
    count_unknown NUMBER(19) DEFAULT 0,
    estat_num_elements NUMBER(19),
    latencia_mitjana NUMBER(19),
    latencia_num_elements NUMBER(19),
    total_tempsmig NUMBER(19) NOT NULL,
    pet_ok_ultperiode NUMBER(19) NOT NULL,
    pet_error_ultperiode NUMBER(19) NOT NULL,
    temps_mig_ultperiode NUMBER(19) NOT NULL,
    endpoint VARCHAR2(255 CHAR),
    pare_id NUMBER(38, 0)
);

-- Table: com_salut_subsistema
CREATE TABLE com_salut_subsistema (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(64 CHAR) NOT NULL,
    estat VARCHAR2(20 CHAR) NOT NULL,
    latencia NUMBER(10),
    total_ok NUMBER(10) NOT NULL,
    total_error NUMBER(10) NOT NULL,
    salut_id NUMBER(38) NOT NULL,
    count_up NUMBER(19) DEFAULT 0,
    count_warn NUMBER(19) DEFAULT 0,
    count_degraded NUMBER(19) DEFAULT 0,
    count_down NUMBER(19) DEFAULT 0,
    count_error NUMBER(19) DEFAULT 0,
    count_maintenance NUMBER(19) DEFAULT 0,
    count_unknown NUMBER(19) DEFAULT 0,
    estat_num_elements NUMBER(19),
    latencia_mitjana NUMBER(19),
    latencia_num_elements NUMBER(19),
    total_tempsmig NUMBER(19) NOT NULL,
    pet_ok_ultperiode NUMBER(19) NOT NULL,
    pet_error_ultperiode NUMBER(19) NOT NULL,
    temps_mig_ultperiode NUMBER(19) NOT NULL
);

-- Table: com_salut_missatge
CREATE TABLE com_salut_missatge (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    data TIMESTAMP NOT NULL,
    nivell VARCHAR2(10 CHAR) NOT NULL,
    missatge VARCHAR2(2048 CHAR),
    salut_id NUMBER(38) NOT NULL
);

-- Table: com_salut_detall
CREATE TABLE com_salut_detall (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(10 CHAR) NOT NULL,
    nom VARCHAR2(100 CHAR) NOT NULL,
    valor VARCHAR2(1024 CHAR),
    salut_id NUMBER(38) NOT NULL
);

-- =============================================
-- Module: comanda-ms-estadistica
-- =============================================

-- Table: com_est_dimensio
CREATE TABLE com_est_dimensio (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(32 CHAR) NOT NULL,
    nom VARCHAR2(64 CHAR) NOT NULL,
    descripcio VARCHAR2(1024 CHAR),
    entorn_app_id NUMBER(38) NOT NULL
);

-- Table: com_est_dimensio_valor
CREATE TABLE com_est_dimensio_valor (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    valor VARCHAR2(255 CHAR),
    dimensio_id NUMBER(38) NOT NULL,
    agrupable NUMBER(1) DEFAULT 0 NOT NULL,
    valor_agrupacio VARCHAR2(255 CHAR)
);

-- Table: com_est_indicador
CREATE TABLE com_est_indicador (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi VARCHAR2(32 CHAR) NOT NULL,
    nom VARCHAR2(64 CHAR) NOT NULL,
    descripcio VARCHAR2(1024 CHAR),
    entorn_app_id NUMBER(38) NOT NULL,
    format VARCHAR2(64 CHAR),
    compactable NUMBER(1) DEFAULT 1 NOT NULL,
    tipus_compactacio VARCHAR2(64 CHAR) DEFAULT 'SUMA',
    compactacio_indicador_id NUMBER(38, 0)
);

-- Table: com_est_temps
CREATE TABLE com_est_temps (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    data DATE NOT NULL,
    anualitat NUMBER(10) NOT NULL,
    trimestre NUMBER(10) NOT NULL,
    mes NUMBER(10) NOT NULL,
    setmana NUMBER(10) NOT NULL,
    dia NUMBER(10) NOT NULL,
    dia_setmana VARCHAR2(2 CHAR) NOT NULL
);

-- Table: com_est_fet
CREATE TABLE com_est_fet (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    temps_id NUMBER(38) NOT NULL,
    dimensions_json VARCHAR2(4000 CHAR),
    indicadors_json VARCHAR2(4000 CHAR),
    entorn_app_id NUMBER(38) NOT NULL,
    tipus VARCHAR2(64 CHAR) DEFAULT 'DIARI' NOT NULL,
    num_dies NUMBER(19) DEFAULT 1 NOT NULL
);

-- Table: com_est_widget
CREATE TABLE com_est_widget (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    widget_type VARCHAR2(16 CHAR) NOT NULL,
    titol VARCHAR2(64 CHAR) NOT NULL,
    descripcio VARCHAR2(1024 CHAR),
    app_id NUMBER(38) NOT NULL,
    periode_mode VARCHAR2(32 CHAR),
    preset_periode VARCHAR2(32 CHAR),
    preset_count NUMBER,
    relatiu_punt_referencia VARCHAR2(32 CHAR),
    relatiu_count NUMBER,
    relatiu_unitat VARCHAR2(32 CHAR),
    relatiu_alineacio VARCHAR2(32 CHAR),
    absolut_tipus VARCHAR2(32 CHAR),
    absolut_data_inici DATE,
    absolut_data_fi DATE,
    absolut_any_referencia VARCHAR2(32 CHAR),
    absolut_any_valor NUMBER,
    absolut_periode_unitat VARCHAR2(32 CHAR),
    absolut_periode_inici NUMBER,
    absolut_periode_fi NUMBER,
    indicador_id NUMBER(38),
    tipus_grafic VARCHAR2(16 CHAR),
    tipus_dades VARCHAR2(32 CHAR),
    tipus_valors VARCHAR2(16 CHAR),
    temps_agrupacio VARCHAR2(16 CHAR),
    descomposicio_dimensio_id NUMBER(38),
    agrupar_dimensio_descomposicio NUMBER(1),
    llegenda_x VARCHAR2(64 CHAR),
    llegenda_y VARCHAR2(64 CHAR),
    unitat VARCHAR2(64 CHAR),
    agrupament_dimensio_id NUMBER(38),
    agrupament_dimensio_titol VARCHAR2(64 CHAR),
    comparar_periode_anterior NUMBER(1) DEFAULT 0,
    atributs_visuals VARCHAR2(4000 CHAR),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_est_widget_dim_valor
CREATE TABLE com_est_widget_dim_valor (
    widget_id NUMBER(38) NOT NULL,
    dimensio_valor_id NUMBER(38) NOT NULL
);

-- Table: com_est_indicador_table
CREATE TABLE com_est_indicador_table (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    indicador_id NUMBER(38) NOT NULL,
    widget_id NUMBER(38) NOT NULL,
    agregacio VARCHAR2(16 CHAR),
    unitat_agregacio VARCHAR2(16 CHAR),
    titol VARCHAR2(64 CHAR),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_est_dashboard
CREATE TABLE com_est_dashboard (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    titol VARCHAR2(64 CHAR) NOT NULL,
    descripcio VARCHAR2(1024 CHAR),
    app_id NUMBER(19),
    entorn_id NUMBER(19),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_est_dashboard_item
CREATE TABLE com_est_dashboard_item (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pos_x NUMBER(10) NOT NULL,
    pos_y NUMBER(10) NOT NULL,
    width NUMBER(10) NOT NULL,
    height NUMBER(10) NOT NULL,
    dashboard_id NUMBER(38) NOT NULL,
    widget_id NUMBER(38) NOT NULL,
    entorn_id NUMBER(38) NOT NULL,
    atributs_visuals VARCHAR2(4000 CHAR),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- Table: com_est_dashboard_titol
CREATE TABLE com_est_dashboard_titol (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    dashboard_id NUMBER(38) NOT NULL,
    titol VARCHAR2(255 CHAR) NOT NULL,
    subtitol VARCHAR2(255 CHAR),
    pos_x NUMBER(10) NOT NULL,
    pos_y NUMBER(10) NOT NULL,
    width NUMBER(10) NOT NULL,
    height NUMBER(10) NOT NULL,
    color_titol VARCHAR2(8 CHAR),
    mida_font_titol NUMBER(10),
    color_subtitol VARCHAR2(8 CHAR),
    mida_font_subtitol NUMBER(10),
    color_fons VARCHAR2(8 CHAR),
    mostrar_vora NUMBER(1),
    color_vora VARCHAR2(8 CHAR),
    ample_vora NUMBER(10),
    created_by VARCHAR2(50 CHAR),
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(50 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38)
);

-- =============================================
-- Module: comanda-ms-monitor
-- =============================================

-- Table: com_monitor
CREATE TABLE com_monitor (
    id NUMBER(38) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    entorn_app_id NUMBER(38),
    codi VARCHAR2(16 CHAR) NOT NULL,
    tipus VARCHAR2(255 CHAR) NOT NULL,
    data TIMESTAMP NOT NULL,
    url VARCHAR2(255 CHAR),
    operacio VARCHAR2(255 CHAR) NOT NULL,
    temps_resposta NUMBER(38),
    estat VARCHAR2(255 CHAR) NOT NULL,
    codi_usuari VARCHAR2(64 CHAR),
    error_descripcio VARCHAR2(1024 CHAR),
    excepcio_msg VARCHAR2(1024 CHAR),
    excepcio_stacktrace VARCHAR2(4000 CHAR)
);

-- =============================================
-- Module: comanda-ms-avisos
-- =============================================

CREATE TABLE com_avis
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    app_id        NUMBER(38, 0) NOT NULL,
    entorn_id     NUMBER(38, 0) NOT NULL,
    identificador VARCHAR2(64 CHAR) NOT NULL,
    tipus         VARCHAR2(16 CHAR) NOT NULL,
    nom           VARCHAR2(255 CHAR) NOT NULL,
    descripcio    VARCHAR2(1024 CHAR),
    data_inici    date,
    data_fi       date,
    url VARCHAR2(255 CHAR),
    responsable VARCHAR2(128 CHAR),
    grup VARCHAR2(128 CHAR),
    created_by    VARCHAR2(64 CHAR) NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    lastmod_by    VARCHAR2(64 CHAR),
    lastmod_date  TIMESTAMP,
    v             NUMBER(38, 0),
    CONSTRAINT com_avis_pk PRIMARY KEY (id)
);

CREATE TABLE com_avis_usuari (
    avis_id NUMBER(38, 0) NOT NULL,
    usuari VARCHAR2(255 CHAR),
    CONSTRAINT com_avis_usuari_pk PRIMARY KEY (avis_id, usuari)
);

CREATE TABLE com_avis_grup (
    avis_id NUMBER(38, 0) NOT NULL,
    grup VARCHAR2(255 CHAR),
    CONSTRAINT com_avis_grup_pk PRIMARY KEY (avis_id, grup)
);

-- =============================================
-- Module: comanda-ms-tasques
-- =============================================

CREATE TABLE com_tasca
(
    id             NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id  NUMBER(38, 0) NOT NULL,
    app_id         NUMBER(38, 0) NOT NULL,
    entorn_id      NUMBER(38, 0) NOT NULL,
    identificador  VARCHAR2(64 CHAR) NOT NULL,
    tipus          VARCHAR2(64 CHAR) NOT NULL,
    nom            VARCHAR2(255 CHAR) NOT NULL,
    descripcio     VARCHAR2(1024 CHAR),
    estat          VARCHAR2(16 CHAR) NOT NULL,
    estat_desc     VARCHAR2(1024 CHAR),
    prioritat      VARCHAR2(16 CHAR),
    data_inici     date,
    data_fi        date,
    data_caducitat date,
    url            VARCHAR2(255 CHAR) NOT NULL,
    responsable    VARCHAR2(128 CHAR),
    grup           VARCHAR2(128 CHAR),
    created_by     VARCHAR2(64 CHAR) NOT NULL,
    created_date   TIMESTAMP NOT NULL,
    lastmod_by     VARCHAR2(64 CHAR),
    lastmod_date   TIMESTAMP,
    v              NUMBER(38, 0),
    CONSTRAINT com_tasca_pk PRIMARY KEY (id)
);

CREATE TABLE com_tasca_usuari
(
    tasca_id NUMBER(38, 0) NOT NULL,
    usuari   VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT com_tasca_usuari_pk PRIMARY KEY (tasca_id, usuari)
);

CREATE TABLE com_tasca_grup
(
    tasca_id NUMBER(38, 0) NOT NULL,
    grup     VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT com_tasca_grup_pk PRIMARY KEY (tasca_id, grup)
);

-- =============================================
-- Module: comanda-ms-ususaris
-- =============================================

CREATE TABLE com_usuari
(
    id           NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codi         VARCHAR2(64 CHAR) NOT NULL,
    nom          VARCHAR2(255 CHAR) NOT NULL,
    nif          VARCHAR2(10 CHAR),
    email        VARCHAR2(255 CHAR),
    created_by   VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by   VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v            NUMBER(38, 0)
);

-- =============================================
-- Module: comanda-ms-permisos
-- =============================================

CREATE TABLE com_objecte
(
    id            NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    tipus         VARCHAR2(64 CHAR) NOT NULL,
    nom           VARCHAR2(255 CHAR) NOT NULL,
    identificador VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE com_acces
(
    id    NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    acces VARCHAR2(64 CHAR)
);

CREATE TABLE com_permis
(
    id            NUMBER(38, 0) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    usuari        VARCHAR2(64 CHAR),
    grup          VARCHAR2(64 CHAR),
    objecte_id    NUMBER(38, 0) NOT NULL,
    created_by    VARCHAR2(64 CHAR) NOT NULL,
    created_date  TIMESTAMP NOT NULL,
    lastmod_by    VARCHAR2(64 CHAR),
    lastmod_date  TIMESTAMP,
    v             NUMBER(38, 0)
);

CREATE TABLE com_permis_acces
(
    permis_id NUMBER(38, 0) NOT NULL,
    acces_id  NUMBER(38, 0) NOT NULL,
    CONSTRAINT com_permis_acces_pk PRIMARY KEY (permis_id, acces_id)
);

CREATE TABLE com_permis_hereus
(
    permis_id NUMBER(38, 0) NOT NULL,
    hereu_id  NUMBER(38, 0) NOT NULL,
    CONSTRAINT com_permis_hereus_pk PRIMARY KEY (permis_id, hereu_id)
);
