-- PARAMETRES
-- Compactar monitor
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'BOOLEAN', 'es.caib.comanda.monitor.buidat.actiu', 'Activar buidat periòdic de dades del monitor', null, null, null, 'true', 1, null, null);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'NUMERIC', 'es.caib.comanda.monitor.buidat.retencio.dies', 'Quants dies s''han de mantenir les dades del monitor en BBDD', null, null, null, '3', 1, null, null);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Monitor', 'Borrat', 'NUMERIC', 'es.caib.comanda.monitor.buidat.periode.minuts', 'Cada quants minuts executar el procés de buidat de dades del monitor', null, null, null, '60', 1, null, null);

-- Compactar estadistiques
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Estadístiques', 'Borrat', 'BOOLEAN', 'es.caib.comanda.stats.compactar.actiu', 'Activar compactat periòdic de dades estadístiques', null, null, null, 'false', 1, null, null);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Estadístiques', 'Borrat', 'CRON', 'es.caib.comanda.stats.compactar.cron', 'Quan executar el procés de compactat de dades estadístiques (CRON)', null, null, null, '0 0 3 * * *', 1, null, null);

-- Scheduler
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.scheduler.pool.size', 'Mida del pool de fils del planificador de tasques en segon pla', NULL, 'Defineix el nombre de fils disponibles al planificador de tasques en segon pla. Aquest component no executa la càrrega pesada, sinó que s’encarrega d’orquestrar i programar quan s’han de llançar les tasques cap al pool de executadors. Un valor massa baix pot provocar retards en la planificació si hi ha molts esdeveniments a la vegada, mentre que un valor massa alt pot consumir recursos innecessaris', NULL, '64', 0, NULL, NULL);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.worker.pool.size', 'Nombre de fils del pool de executors de tasques en segon pla', NULL, 'Indica quants fils poden executar tasques en paral·lel dins el pool d''executors. Cada fil pot processar una tasca alhora, de manera que aquest paràmetre determina la capacitat de processament simultani de l’aplicació. Si el valor és massa baix, les tasques quedaran en cua esperant torn; si és massa alt, es poden crear massa fils i saturar els recursos del servidor. Cal ajustar-lo segons la potència de la màquina i la càrrega de treball prevista, per aconseguir un equilibri entre rendiment i ús eficient dels recursos', NULL, '4', 0, NULL, NULL);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Scheduler', 'Pool', 'NUMERIC', 'es.caib.comanda.worker.queue.size', 'Capacitat de la cua de tasques pendents', NULL, 'Estableix quantes tasques poden quedar en cua quan tots els fils del pool de executors estan ocupats. Aquesta cua actua com a coixí entre la càrrega d’entrada i la capacitat real de processament. Si la cua és massa petita i arriben moltes peticions, es poden rebutjar tasques amb errors de saturació. Si és massa gran, es poden acumular moltes tasques pendents i augmentar la latència de processament. El valor òptim depèn del volum de feina i del temps mitjà d’execució de cada tasca, i s’ha d’ajustar per evitar tant la pèrdua de peticions com l’acumulació excessiva', NULL, '200', 0, NULL, NULL);

-- Borrat tasques i avisos
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Tasques', 'Borrat', 'NUMERIC', 'es.caib.comanda.tasca.borrat.dies', 'Número de dies que hem de mantenir les tasques finalitzades en el sistema', NULL, 'Un valor menor que 0 indica que no es borren les tasques finalitzades', NULL, '10', 1, NULL, NULL);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Tasques', 'Borrat', 'NUMERIC', 'es.caib.comanda.tasca.pendent.borrat.dies', 'Número de dies que hem de mantenir les tasques NO finalitzades en el sistema', NULL, 'El valor 0 indica que no es borren les tasques no finalitzades', NULL, '90', 1, NULL, NULL);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Avisos', 'Borrat', 'NUMERIC', 'es.caib.comanda.avis.borrat.dies', 'Número de dies que hem de mantenir els avisos en el sistema', NULL, 'El valor 0 indica que no es borren els avisos', NULL, '10', 1, NULL, NULL);

-- Logs estat aplicacio
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, NOM_KEY, DESCRIPCIO, DESCRIPCIO_KEY, VALOR, EDITABLE, GRUP_KEY, SUBGRUP_KEY) VALUES ('Salut', 'Logs', 'BOOLEAN', 'es.caib.comanda.salut.log.report', 'Generació de report d''estat en el logs', NULL, 'Activar generació de report periòdic d''estat del sistema en el logs de l''aplicació', NULL, 'true', 1, NULL, NULL);

-- Autenticació
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, VALOR, EDITABLE) VALUES ('Estadístiques', 'autenticacio', 'TEXT', 'es.caib.comanda.stats.auth.usuari', 'Usuari', '', 0);
INSERT INTO COM_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, VALOR, EDITABLE) VALUES ('Estadístiques', 'autenticacio', 'PASSWORD', 'es.caib.comanda.stats.auth.password', 'Contrasenya', '', 0);
