-- Changeset db/changelog/changes/salut/0.1.2/0.1.2_salut_002.yaml::salut-historic-estat-1::codex
-- Crear taula d'històric de canvis d'estat de salut per entorn
CREATE TABLE com_salut_hist
(
    id            NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    data          TIMESTAMP NOT NULL,
    app_estat     VARCHAR2(20 CHAR) NOT NULL,
    peticio_error NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT com_saluthist_pk PRIMARY KEY (id)
);

CREATE INDEX com_saluthist_entdat_i ON com_salut_hist(entorn_app_id, data);

GRANT SELECT, UPDATE, INSERT, DELETE ON com_salut_hist TO WWW_COMANDA;
