-- Añadir la columna 'notificacio_finalitzada' a la configuración de alarmas para indicar si debe enviarse una notificación cuando finaliza la alarma
ALTER TABLE com_alarma_config ADD notificacio_finalitzada NUMBER(1) DEFAULT 1;
-- Añadir las columnas rule_version y rule_json para la configuración de condiciones múltiples en las alarmas
ALTER TABLE com_alarma_config ADD rule_version INTEGER;
ALTER TABLE com_alarma_config ADD rule_json CLOB;

-- Afegir camp ordre a la taula alarma_config
ALTER TABLE com_alarma_config ADD ordre NUMBER(38, 0);
CREATE INDEX com_alarma_config_ordre ON com_alarma_config(ordre);

-- Afegir camp aturar_avaluacio_posteriors a la taula alarma_config
ALTER TABLE com_alarma_config ADD aturar_avaluacio_posteriors NUMBER(1) DEFAULT 0;

-- Creació de la taula avis_llegit per a enregistrar si un avis ha estat llegit per un usuari
CREATE TABLE com_avis_llegit (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    avis_id NUMBER(38, 0) NOT NULL,
    usuari VARCHAR2(255) NOT NULL,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_avis_llegit_pk PRIMARY KEY (id)
);
ALTER TABLE com_avis_llegit ADD CONSTRAINT com_avis_llegit_avis_fk FOREIGN KEY (avis_id) REFERENCES com_avis (id) ON DELETE CASCADE;
ALTER TABLE com_avis_llegit ADD CONSTRAINT com_avis_llegit_avis_usuari_uk UNIQUE (usuari, avis_id);
CREATE INDEX com_avis_llegit_avis_idx ON com_avis_llegit(avis_id, usuari);

-- ESTADISTIQUES
-- Crear paletes de colors independents per a plantilles de dashboard
CREATE TABLE com_est_color_palette (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR2(128 CHAR) NOT NULL,
    descripcio VARCHAR2(1024 CHAR),
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_est_cpal_pk PRIMARY KEY (id)
);
ALTER TABLE com_est_color_palette ADD CONSTRAINT com_est_cpal_nom_uk UNIQUE (nom);

-- Crear colors ordenats dins cada paleta
CREATE TABLE com_est_color_palette_color (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    palette_id NUMBER(38, 0) NOT NULL,
    posicio INTEGER NOT NULL,
    valor VARCHAR2(64 CHAR) NOT NULL,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_est_cpalcol_pk PRIMARY KEY (id)
);
ALTER TABLE com_est_color_palette_color ADD CONSTRAINT com_est_cpalcol_pal_fk FOREIGN KEY (palette_id) REFERENCES com_est_color_palette (id);
ALTER TABLE com_est_color_palette_color ADD CONSTRAINT com_est_cpalcol_pos_uk UNIQUE (palette_id, posicio);
CREATE INDEX com_est_cpalcol_pal_i ON com_est_color_palette_color(palette_id);

-- Crear plantilles d'estil de dashboard amb prefix del modul estadistica
CREATE TABLE com_est_dashboard_style_template (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR2(128 CHAR) NOT NULL,
    mostrar_vora NUMBER(1),
    ample_vora INTEGER,
    mida_font_titol VARCHAR2(64 CHAR),
    mida_font_descripcio VARCHAR2(64 CHAR),
    icona VARCHAR2(64 CHAR),
    mida_font_valor INTEGER,
    mida_font_unitats INTEGER,
    mida_font_canvi_percentual INTEGER,
    mostrar_reticula NUMBER(1),
    bar_stacked NUMBER(1),
    bar_horizontal NUMBER(1),
    line_show_points NUMBER(1),
    area NUMBER(1),
    line_smooth NUMBER(1),
    line_width INTEGER,
    outer_radius INTEGER,
    pie_donut NUMBER(1),
    inner_radius INTEGER,
    pie_show_labels NUMBER(1),
    label_size INTEGER,
    gauge_min INTEGER,
    gauge_max INTEGER,
    gauge_rangs VARCHAR2(1000 CHAR),
    heatmap_min_value INTEGER,
    heatmap_max_value INTEGER,
    mostrar_capcalera NUMBER(1),
    mostrar_alternancia NUMBER(1),
    mostrar_vora_taula NUMBER(1),
    ample_vora_taula INTEGER,
    mostrar_separador_horitzontal NUMBER(1),
    ample_separador_horitzontal INTEGER,
    mostrar_separador_vertical NUMBER(1),
    ample_separador_vertical INTEGER,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_est_dstpl_pk PRIMARY KEY (id)
);
ALTER TABLE com_est_dashboard_style_template ADD CONSTRAINT com_est_dstpl_nom_uk UNIQUE (nom);

-- Assignar dues paletes a cada grup de tema de plantilla
CREATE TABLE com_est_dashboard_template_palette_group (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id NUMBER(38, 0) NOT NULL,
    group_type VARCHAR2(32 CHAR) NOT NULL,
    widget_palette_id NUMBER(38, 0) NOT NULL,
    chart_palette_id NUMBER(38, 0) NOT NULL,
    ordre INTEGER,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_est_tpalgrp_pk PRIMARY KEY (id)
);

ALTER TABLE com_est_dashboard_template_palette_group ADD CONSTRAINT com_est_tpalgrp_tpl_fk FOREIGN KEY (template_id) REFERENCES com_est_dashboard_style_template (id);
ALTER TABLE com_est_dashboard_template_palette_group ADD CONSTRAINT com_est_tpalgrp_wpal_fk FOREIGN KEY (widget_palette_id) REFERENCES com_est_color_palette (id);
ALTER TABLE com_est_dashboard_template_palette_group ADD CONSTRAINT com_est_tpalgrp_cpal_fk FOREIGN KEY (chart_palette_id) REFERENCES com_est_color_palette (id);
ALTER TABLE com_est_dashboard_template_palette_group ADD CONSTRAINT com_est_tpalgrp_type_uk UNIQUE (template_id, group_type);
CREATE INDEX com_est_tpalgrp_tpl_i ON com_est_dashboard_template_palette_group(template_id);
CREATE INDEX com_est_tpalgrp_wpal_i ON com_est_dashboard_template_palette_group(widget_palette_id);
CREATE INDEX com_est_tpalgrp_cpal_i ON com_est_dashboard_template_palette_group(chart_palette_id);

-- Crear propietats visuals de widget basades en posicions de paleta
CREATE TABLE com_est_widget_style_property (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    template_id NUMBER(38, 0) NOT NULL,
    scope VARCHAR2(32 CHAR) NOT NULL,
    property_name VARCHAR2(64 CHAR) NOT NULL,
    value_type VARCHAR2(32 CHAR) NOT NULL,
    palette_role VARCHAR2(16 CHAR),
    palette_index INTEGER,
    scalar_value VARCHAR2(1000 CHAR),
    default_property NUMBER(1) DEFAULT 0,
    ordre INTEGER,
    created_by VARCHAR2(64 CHAR) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    lastmod_by VARCHAR2(64 CHAR),
    lastmod_date TIMESTAMP,
    v NUMBER(38, 0),
    CONSTRAINT com_est_wstprop_pk PRIMARY KEY (id)
);
ALTER TABLE com_est_widget_style_property ADD CONSTRAINT com_est_wstprop_tpl_fk FOREIGN KEY (template_id) REFERENCES com_est_dashboard_style_template (id);
ALTER TABLE com_est_widget_style_property ADD CONSTRAINT com_est_wstprop_name_uk UNIQUE (template_id, scope, property_name);
CREATE INDEX com_est_wstprop_tpl_i ON com_est_widget_style_property(template_id);

-- Enllacar dashboards amb la nova taula de plantilles d'estil
ALTER TABLE com_est_dashboard ADD plantilla_id NUMBER(38, 0);
ALTER TABLE com_est_dashboard ADD CONSTRAINT com_est_dash_tpl_fk FOREIGN KEY (plantilla_id) REFERENCES com_est_dashboard_style_template (id);
CREATE INDEX com_est_dash_tpl_i ON com_est_dashboard(plantilla_id);

-- Afegir tipus d'estil als titols de dashboard
ALTER TABLE com_est_dashboard_titol ADD tipus_titol VARCHAR2(32 CHAR) DEFAULT 'TIPUS_1';

-- Afegir configuracio de presentacio per items de dashboard
ALTER TABLE com_est_dashboard_item ADD destacat NUMBER(1) DEFAULT 0;
ALTER TABLE com_est_dashboard_item ADD plantilla_id NUMBER(38, 0);
ALTER TABLE com_est_dashboard_item ADD CONSTRAINT com_dboard_item_tpl_fk FOREIGN KEY (plantilla_id) REFERENCES com_est_dashboard_style_template (id);
CREATE INDEX com_dboard_item_tpl_i ON com_est_dashboard_item(plantilla_id);

-- Afegir configuracio de presentacio per titols de dashboard
ALTER TABLE com_est_dashboard_titol ADD destacat NUMBER(1) DEFAULT 0;
ALTER TABLE com_est_dashboard_titol ADD plantilla_id NUMBER(38, 0);
ALTER TABLE com_est_dashboard_titol ADD CONSTRAINT com_dboard_titol_tpl_fk FOREIGN KEY (plantilla_id) REFERENCES com_est_dashboard_style_template (id);
CREATE INDEX com_dboard_titol_tpl_i ON com_est_dashboard_titol(plantilla_id);

-- Afegir camp personalitzat per items de dashboard
ALTER TABLE com_est_dashboard_item ADD personalitzat NUMBER(1) DEFAULT 0;

-- SALUT
-- Permet valors null a mètriques opcionals de salut d'integracions i subsistemes
ALTER TABLE com_salut_integracio MODIFY total_ok NULL;
ALTER TABLE com_salut_integracio MODIFY total_error NULL;
ALTER TABLE com_salut_integracio MODIFY total_tempsmig NULL;
ALTER TABLE com_salut_integracio MODIFY pet_ok_ultperiode NULL;
ALTER TABLE com_salut_integracio MODIFY pet_error_ultperiode NULL;
ALTER TABLE com_salut_integracio MODIFY temps_mig_ultperiode NULL;
ALTER TABLE com_salut_subsistema MODIFY total_ok NULL;
ALTER TABLE com_salut_subsistema MODIFY total_error NULL;
ALTER TABLE com_salut_subsistema MODIFY total_tempsmig NULL;
ALTER TABLE com_salut_subsistema MODIFY pet_ok_ultperiode NULL;
ALTER TABLE com_salut_subsistema MODIFY pet_error_ultperiode NULL;
ALTER TABLE com_salut_subsistema MODIFY temps_mig_ultperiode NULL;

-- Crear taula d'històric de canvis d'estat de salut per entorn
CREATE TABLE com_salut_hist (
    id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entorn_app_id NUMBER(38, 0) NOT NULL,
    data TIMESTAMP NOT NULL,
    app_estat VARCHAR2(20 CHAR) NOT NULL,
    peticio_error NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT com_saluthist_pk PRIMARY KEY (id)
);
CREATE INDEX com_saluthist_entdat_i ON com_salut_hist(entorn_app_id, data);

-- Modificacio mida de codis
ALTER TABLE com_salut_integracio MODIFY codi VARCHAR2(100 CHAR);
ALTER TABLE com_salut_subsistema MODIFY codi VARCHAR2(100 CHAR);