-- Changeset db/changelog/changes/conf/0.1.2/0.1.2_con_002.yaml::con-change-0.1.2.002-1::limit
-- Afegir paràmetres LDAP de PluginsIB UserInformation a la taula de paràmetres
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.security_authentication', 'Autenticació LDAP', 'Mecanisme d''autenticació utilitzat per connectar amb el servidor LDAP.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.prefix_role_match_memberof', 'Prefix de rol per a memberOf', 'Prefix emprat per identificar els rols dins l''atribut memberOf de LDAP.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.memberof', 'Atribut de pertinença a grups', 'Nom de l''atribut LDAP que indica els grups o rols als quals pertany l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.department', 'Atribut del departament', 'Nom de l''atribut LDAP que conté el departament de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.telephone', 'Atribut del telèfon', 'Nom de l''atribut LDAP que conté el número de telèfon de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.surname2', 'Atribut del segon llinatge', 'Nom de l''atribut LDAP que conté el segon llinatge de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.surname1', 'Atribut del primer llinatge', 'Nom de l''atribut LDAP que conté el primer llinatge de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.surname', 'Atribut dels llinatges', 'Nom de l''atribut LDAP que conté els llinatges de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.name', 'Atribut del nom', 'Nom de l''atribut LDAP que conté el nom de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.administration_id', 'Atribut de l''identificador administratiu', 'Nom de l''atribut LDAP que conté l''identificador administratiu de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.mail', 'Atribut del correu electrònic', 'Nom de l''atribut LDAP que conté l''adreça de correu electrònic de l''usuari.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.attribute.username', 'Atribut del nom d''usuari', 'Nom de l''atribut LDAP que conté el nom d''usuari o identificador d''accés.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.host_url', 'URL del servidor LDAP', 'Adreça URL del servidor LDAP utilitzat per obtenir la informació dels usuaris.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.security_principal', 'Usuari de connexió LDAP', 'Identificador de l''usuari emprat per establir la connexió amb el servidor LDAP.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'PASSWORD', 'es.caib.comanda.pluginsib.userinformation.ldap.security_credentials', 'Contrasenya de connexió LDAP', 'Credencial o contrasenya de l''usuari emprat per connectar amb el servidor LDAP.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.suffix_role_match_memberof', 'Sufix de rol per a memberOf', 'Sufix emprat per identificar els rols dins l''atribut memberOf de LDAP.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.users_context_dn', 'DN del context d''usuaris', 'Nom distingit base dins LDAP on es cercaran els usuaris.', 0);
INSERT INTO com_PARAMETRE (GRUP, SUBGRUP, TIPUS, CODI, NOM, DESCRIPCIO, EDITABLE) VALUES ('PluginsIB', 'UserInformation', 'TEXT', 'es.caib.comanda.pluginsib.userinformation.ldap.search_scope', 'Àmbit de cerca LDAP', 'Àmbit de cerca utilitzat per localitzar usuaris dins el directori LDAP.', 0);